### ISSUE TITLE
sed2py: 2d parameter scan

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/tellurium#100]
The following Python program should work, but does not.  The SED-ML seems to be created properly:
```
import tellurium as te

antimonyStr = '''
// Created by libAntimony v2.9
model *BorisEJB()

  // Compartments and Species:
  compartment compartment_;
  species MKKK in compartment_, MKKK_P in compartment_, MKK in compartment_;
  species MKK_P in compartment_, MKK_PP in compartment_, MAPK in compartment_;
  species MAPK_P in compartment_, MAPK_PP in compartment_;

  // Reactions:
  J0: MKKK => MKKK_P; (J0_V1*MKKK)/((1 + (MAPK_PP/J0_Ki)^J0_n)*(J0_K1 + MKKK));
  J1: MKKK_P => MKKK; (J1_V2*MKKK_P)/(J1_KK2 + MKKK_P);
  J2: MKK => MKK_P; (J2_k3*MKKK_P*MKK)/(J2_KK3 + MKK);
  J3: MKK_P => MKK_PP; (J3_k4*MKKK_P*MKK_P)/(J3_KK4 + MKK_P);
  J4: MKK_PP => MKK_P; (J4_V5*MKK_PP)/(J4_KK5 + MKK_PP);
  J5: MKK_P => MKK; (J5_V6*MKK_P)/(J5_KK6 + MKK_P);
  J6: MAPK => MAPK_P; (J6_k7*MKK_PP*MAPK)/(J6_KK7 + MAPK);
  J7: MAPK_P => MAPK_PP; (J7_k8*MKK_PP*MAPK_P)/(J7_KK8 + MAPK_P);
  J8: MAPK_PP => MAPK_P; (J8_V9*MAPK_PP)/(J8_KK9 + MAPK_PP);
  J9: MAPK_P => MAPK; (J9_V10*MAPK_P)/(J9_KK10 + MAPK_P);

  // Species initializations:
  MKKK = 90;
  MKKK_P = 10;
  MKK = 280;
  MKK_P = 10;
  MKK_PP = 10;
  MAPK = 280;
  MAPK_P = 10;
  MAPK_PP = 10;

  // Compartment initializations:
  compartment_ = 1;

  // Variable initializations:
  J0_V1 = 2.5;
  J0_Ki = 9;
  J0_n = 1;
  J0_K1 = 10;
  J1_V2 = 0.25;
  J1_KK2 = 8;
  J2_k3 = 0.025;
  J2_KK3 = 15;
  J3_k4 = 0.025;
  J3_KK4 = 15;
  J4_V5 = 0.75;
  J4_KK5 = 15;
  J5_V6 = 0.75;
  J5_KK6 = 15;
  J6_k7 = 0.025;
  J6_KK7 = 15;
  J7_k8 = 0.025;
  J7_KK8 = 15;
  J8_V9 = 0.5;
  J8_KK9 = 15;
  J9_V10 = 0.5;
  J9_KK10 = 15;

  // Other declarations:
  const compartment_, J0_V1, J0_Ki, J0_n, J0_K1, J1_V2, J1_KK2, J2_k3, J2_KK3;
  const J3_k4, J3_KK4, J4_V5, J4_KK5, J5_V6, J5_KK6, J6_k7, J6_KK7, J7_k8;
  const J7_KK8, J8_V9, J8_KK9, J9_V10, J9_KK10;
end
'''

phrasedmlStr = '''
  model_3 = model "borisejb.xml"
  sim_repeat = simulate steadystate
  task_1 = run sim_repeat on model_3
  repeatedtask_1 = repeat task_1 for J1_KK2 in [1, 5, 10, 50, 60, 70, 80, 90, 100]
  repeatedtask_2 = repeat repeatedtask_1 for J4_KK5 in uniform(1, 40, 100)
  plot repeatedtask_2.J4_KK5 vs repeatedtask_2.MKK, repeatedtask_2.MKK_P
'''

exp = te.experiment(antimonyStr, phrasedmlStr)
exp.execute()
```

**Comment by matthiaskoenig** [comment]
I already started working on the new sedml generation (see #95) in branch mkoenig.
Will try to provide a quick bugfix for the old scripts today. 
If not possible it will take a few days until I finish the new tesedml.
Same for #99, #98, #97

**Comment by matthiaskoenig** [comment]
@luciansmith All the `*` missing in the antimony strings of #97, #98, #99. #100
This could be a antimony bug in copy pasting strings.

Please add any phrasedml example you have to
```
tellurium/exampes/tellurium-files/phrasedml
``` 
I already added the 
```
oneStep.py
parameterScan1D.py
parameterScan2D.py
repeatedStochasticTest.py
```
corresponding to #97, #98, #99, #100

This has 2 main advantages:
* All python files in the example folders are executed by the test suite. I.e. as soon as you put an example file in the example folders there is a new test_case which tests if the example can be executed. This is a very big thing, because you can always be sure that all the examples are working with every commit.
From time to time there will be minor changes to the API which require updates of the example code. You can than easily update your phrasedml tutorial examples from the updated examples in the tellurium repository. 
Even better: you can create your documentation directly from the example files (this is what I am doing, than I am always sure that all code in the documentation can be executed)

* examples can be imported from within tellurium (and there are more examples !)

Currently the 4 tests for the 4 phrasedml examples fail. These are all due to recent changes in the roadrunner API, so all no big issues.

This is for every problem with tellurium but also for examples you want to run in the future
=> Just add an example file with the problem/code to tellurium/examples/tellurium-files

**Comment by kirichoi** [comment]
Apart from missing * in antimony string, the SEDML files translated from phrasedml string seems to be invalid when using phrasedml 1.0 Could you double check this?

**Comment by luciansmith** [comment]
It looks like github itself is interpreting the *'s as markup for italics, which is unfortunate, but anyway.  I'll edit the one in the example.

As far as the SED-ML string, I get the following:
---
<?xml version="1.0" encoding="UTF-8"?>

<sedML xmlns="http://sed-ml.org/sed-ml/level1/version2" level="1" version="2">
  <listOfSimulations>
    <steadyState id="sim_repeat"/>
  </listOfSimulations>
  <listOfModels>
    <model id="model_3" language="urn:sedml:language:sbml.level-3.version-1" source="borisejb.xml"/>
  </listOfModels>
  <listOfTasks>
    <task id="task_1" modelReference="model_3" simulationReference="sim_repeat"/>
    <repeatedTask id="repeatedtask_1" range="vector_for_J1_KK2" resetModel="false">
      <listOfRanges>
        <vectorRange id="vector_for_J1_KK2">
          <value> 1 </value>
          <value> 5 </value>
          <value> 10 </value>
          <value> 50 </value>
          <value> 60 </value>
          <value> 70 </value>
          <value> 80 </value>
          <value> 90 </value>
          <value> 100 </value>
        </vectorRange>
      </listOfRanges>
      <listOfChanges>
        <setValue range="vector_for_J1_KK2" modelReference="model_3" target="/sbml:sbml/sbml:model/descendant::*[@id='J1_KK2']">
          <math xmlns="http://www.w3.org/1998/Math/MathML">
            <ci> vector_for_J1_KK2 </ci>
          </math>
        </setValue>
      </listOfChanges>
      <listOfSubTasks>
        <subTask order="0" task="task_1"/>
      </listOfSubTasks>
    </repeatedTask>
    <repeatedTask id="repeatedtask_2" range="uniform_linear_for_J4_KK5" resetModel="false">
      <listOfRanges>
        <uniformRange id="uniform_linear_for_J4_KK5" start="1" end="40" numberOfPoints="100" type="linear"/>
      </listOfRanges>
      <listOfChanges>
        <setValue range="uniform_linear_for_J4_KK5" modelReference="model_3" target="/sbml:sbml/sbml:model/descendant::*[@id='J4_KK5']">
          <math xmlns="http://www.w3.org/1998/Math/MathML">
            <ci> uniform_linear_for_J4_KK5 </ci>
          </math>
        </setValue>
      </listOfChanges>
      <listOfSubTasks>
        <subTask order="0" task="repeatedtask_1"/>
      </listOfSubTasks>
    </repeatedTask>
  </listOfTasks>
  <listOfDataGenerators>
    <dataGenerator id="plot_0_0_0" name="repeatedtask_2.J4_KK5">
      <listOfVariables>
        <variable id="repeatedtask_2_____J4_KK5" target="/sbml:sbml/sbml:model/descendant::*[@id='J4_KK5']" taskReference="repeatedtask_2" modelReference="model_3"/>
      </listOfVariables>
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <ci> repeatedtask_2_____J4_KK5 </ci>
      </math>
    </dataGenerator>
    <dataGenerator id="plot_0_0_1" name="repeatedtask_2.MKK">
      <listOfVariables>
        <variable id="repeatedtask_2_____MKK" target="/sbml:sbml/sbml:model/descendant::*[@id='MKK']" taskReference="repeatedtask_2" modelReference="model_3"/>
      </listOfVariables>
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <ci> repeatedtask_2_____MKK </ci>
      </math>
    </dataGenerator>
    <dataGenerator id="plot_0_1_1" name="repeatedtask_2.MKK_P">
      <listOfVariables>
        <variable id="repeatedtask_2_____MKK_P" target="/sbml:sbml/sbml:model/descendant::*[@id='MKK_P']" taskReference="repeatedtask_2" modelReference="model_3"/>
      </listOfVariables>
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <ci> repeatedtask_2_____MKK_P </ci>
      </math>
    </dataGenerator>
  </listOfDataGenerators>
  <listOfOutputs>
    <plot2D id="plot_0">
      <listOfCurves>
        <curve logX="false" logY="false" xDataReference="plot_0_0_0" yDataReference="plot_0_0_1"/>
        <curve logX="false" logY="false" xDataReference="plot_0_0_0" yDataReference="plot_0_1_1"/>
      </listOfCurves>
    </plot2D>
  </listOfOutputs>
</sedML>
---

There was a problem with the 'sedml' string in the program, since I was claiming that it was 'oscli' that was that model, not 'borisEJB'.  I'll update the example.

With that fix, is this what you get, too?

**Comment by 0u812** [comment]
Just escape it with triple backticks to enclose a block of formatted code.

On February 25, 2016 1:53:57 PM PST, Lucian Smith <notifications@github.com> wrote:
>It looks like github itself is interpreting the *'s as markup for
>italics, which is unfortunate, but anyway.  I'll edit the one in the
>example.
>
>As far as the SED-ML string, I get the following:
>---
><?xml version="1.0" encoding="UTF-8"?>
>
><sedML xmlns="http://sed-ml.org/sed-ml/level1/version2" level="1"
>version="2">
>  <listOfSimulations>
>    <steadyState id="sim_repeat"/>
>  </listOfSimulations>
>  <listOfModels>
><model id="model_3"
>language="urn:sedml:language:sbml.level-3.version-1"
>source="borisejb.xml"/>
>  </listOfModels>
>  <listOfTasks>
><task id="task_1" modelReference="model_3"
>simulationReference="sim_repeat"/>
><repeatedTask id="repeatedtask_1" range="vector_for_J1_KK2"
>resetModel="false">
>      <listOfRanges>
>        <vectorRange id="vector_for_J1_KK2">
>          <value> 1 </value>
>          <value> 5 </value>
>          <value> 10 </value>
>          <value> 50 </value>
>          <value> 60 </value>
>          <value> 70 </value>
>          <value> 80 </value>
>          <value> 90 </value>
>          <value> 100 </value>
>        </vectorRange>
>      </listOfRanges>
>      <listOfChanges>
><setValue range="vector_for_J1_KK2" modelReference="model_3"
>target="/sbml:sbml/sbml:model/descendant::*[@id='J1_KK2']">
>          <math xmlns="http://www.w3.org/1998/Math/MathML">
>            <ci> vector_for_J1_KK2 </ci>
>          </math>
>        </setValue>
>      </listOfChanges>
>      <listOfSubTasks>
>        <subTask order="0" task="task_1"/>
>      </listOfSubTasks>
>    </repeatedTask>
><repeatedTask id="repeatedtask_2" range="uniform_linear_for_J4_KK5"
>resetModel="false">
>      <listOfRanges>
><uniformRange id="uniform_linear_for_J4_KK5" start="1" end="40"
>numberOfPoints="100" type="linear"/>
>      </listOfRanges>
>      <listOfChanges>
><setValue range="uniform_linear_for_J4_KK5" modelReference="model_3"
>target="/sbml:sbml/sbml:model/descendant::*[@id='J4_KK5']">
>          <math xmlns="http://www.w3.org/1998/Math/MathML">
>            <ci> uniform_linear_for_J4_KK5 </ci>
>          </math>
>        </setValue>
>      </listOfChanges>
>      <listOfSubTasks>
>        <subTask order="0" task="repeatedtask_1"/>
>      </listOfSubTasks>
>    </repeatedTask>
>  </listOfTasks>
>  <listOfDataGenerators>
>    <dataGenerator id="plot_0_0_0" name="repeatedtask_2.J4_KK5">
>      <listOfVariables>
><variable id="repeatedtask_2_____J4_KK5"
>target="/sbml:sbml/sbml:model/descendant::*[@id='J4_KK5']"
>taskReference="repeatedtask_2" modelReference="model_3"/>
>      </listOfVariables>
>      <math xmlns="http://www.w3.org/1998/Math/MathML">
>        <ci> repeatedtask_2_____J4_KK5 </ci>
>      </math>
>    </dataGenerator>
>    <dataGenerator id="plot_0_0_1" name="repeatedtask_2.MKK">
>      <listOfVariables>
><variable id="repeatedtask_2_____MKK"
>target="/sbml:sbml/sbml:model/descendant::*[@id='MKK']"
>taskReference="repeatedtask_2" modelReference="model_3"/>
>      </listOfVariables>
>      <math xmlns="http://www.w3.org/1998/Math/MathML">
>        <ci> repeatedtask_2_____MKK </ci>
>      </math>
>    </dataGenerator>
>    <dataGenerator id="plot_0_1_1" name="repeatedtask_2.MKK_P">
>      <listOfVariables>
><variable id="repeatedtask_2_____MKK_P"
>target="/sbml:sbml/sbml:model/descendant::*[@id='MKK_P']"
>taskReference="repeatedtask_2" modelReference="model_3"/>
>      </listOfVariables>
>      <math xmlns="http://www.w3.org/1998/Math/MathML">
>        <ci> repeatedtask_2_____MKK_P </ci>
>      </math>
>    </dataGenerator>
>  </listOfDataGenerators>
>  <listOfOutputs>
>    <plot2D id="plot_0">
>      <listOfCurves>
><curve logX="false" logY="false" xDataReference="plot_0_0_0"
>yDataReference="plot_0_0_1"/>
><curve logX="false" logY="false" xDataReference="plot_0_0_0"
>yDataReference="plot_0_1_1"/>
>      </listOfCurves>
>    </plot2D>
>  </listOfOutputs>
></sedML>
>---
>
>There was a problem with the 'sedml' string in the program, since I was
>claiming that it was 'oscli' that was that model, not 'borisEJB'.  I'll
>update the example.
>
>With that fix, is this what you get, too? 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/tellurium/issues/100#issuecomment-189003180

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by luciansmith** [comment]
Hey, that worked!  Thanks.

**Comment by matthiaskoenig** [comment]
Is closed.
See https://github.com/sys-bio/tellurium/issues/95
@luciansmith steadyState scan does not work on the MAPK model due to the oscillations. I did the identical 2D parameterScan with uniform() instead in the examples.
2D steady state scan work on models which reach steady state
