### ISSUE TITLE
draw() command should bail if graphviz is not found

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/tellurium#101]
Some of the current implementation of draw() command should bail out if graphviz is not installed. At least on windows, graphviz is not prepackaged with Tellurium, and there is no plan to prepackage it in the future.

**Comment by kirichoi** [comment]
Successfully integrated graphviz into windows version of tellurium

**Comment by hsauro** [comment]
Nice, be interested to see how this works.

H

**Comment by matthiaskoenig** [comment]
This sounds closed to me. 
@kirichoi you should close the issue if finished

**Comment by kirichoi** [comment]
Fixed the issue on Windows. However, I am not sure how things work when you install graphviz on Mac or Linux.
