### ISSUE TITLE
Test kisao in tesedml

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/tellurium#103]
Test various kisao using tesedml. Add tests related to various algorithms.

**Comment by matthiaskoenig** [comment]
@ Kiri
I created the new tesedml implementation (currently in branch mkoenig).
Implements everything the old tesedml did, some additional new things & fixes a lot of bugs I found on the way.

I would like to merge this with master and than implement the kisao test.
I think I can get a complete SEDML support over the weekend.

The Kisaos are very clean in the new implementation and are directly translated into the keys of the integrators.
Currently supported are in the new implementation.

If there is something missing let me know.
Otherwise I would right tests for all these.
```

if kid == 'KISAO:0000209':
    key = 'relative_tolerance'
elif kid == 'KISAO:0000211':
    key = 'relative_tolerance'
elif kid == 'KISAO:0000220':
    key = 'maximum_bdf_order'
elif kid == 'KISAO:0000219':
    key = 'maximum_adams_order'
elif kid == 'KISAO:0000415':
    key = 'maximum_num_steps'
elif kid == 'KISAO:0000467':
    key = 'maximum_time_step'
elif kid == 'KISAO:0000485':
    key = 'minimum_time_step'
elif kid == 'KISAO:0000332':
    key = 'initial_time_step'
elif kid == 'KISAO:0000107':
    key = 'variable_step_size'
elif kid == 'KISAO:0000486':
    key = 'maximum_iterations'
elif kid == 'KISAO:0000487':
    key = 'maximum_damping'
elif kid == 'KISAO:0000488':
    key = 'seed'

```
The integrators are mapped to

```
# cvode & steady state are mapped to cvode
if kid in ['KISAO:0000433', 'KISAO:0000019', 'KISAO:0000407']:
    return 'cvode'
elif kid == 'KISAO:0000241':
    return 'gillespie'
elif kid == 'KISAO:0000032':
    return 'rk4'
elif kid in ['KISAO:0000435', 'KISAO_0000064']:
    return 'rk45'
```
And the supported integrators for the various simulation types are

```
supported = []
if simType == libsedml.SEDML_SIMULATION_UNIFORMTIMECOURSE:
    supported = ['KISAO:0000433', 'KISAO:0000019', 'KISAO:0000241', 'KISAO:0000032', 'KISAO:0000435', 'KISAO_0000064']
elif simType == libsedml.SEDML_SIMULATION_ONESTEP:
    supported = ['KISAO:0000433', 'KISAO:0000019', 'KISAO:0000241', 'KISAO:0000032', 'KISAO:0000435', 'KISAO_0000064']
elif simType == libsedml.SEDML_SIMULATION_STEADYSTATE:
    supported = ['KISAO:0000099', 'KISAO:0000407']
```

Just give me the okay, than I merge the code with master.
I think I can fix all the sedml related issues until Monday/Tuesday.

**Comment by kirichoi** [comment]
@matthiaskoenig : Thanks for the heads up. One thing you might want to check out is the list of kisao I added to the script. That is the list Lucian gave me that roadrunner supports. One thing that is missing is 'stiff' flag for CVODE which chooses b/w BDF and adams-moulton.

**Comment by matthiaskoenig** [comment]
Yes. Will add these.

**Comment by luciansmith** [comment]
For what it's worth, here ar all the Kisao values which should basically translate to 'stochastic' (from phrasedml/src/simulation.cpp:

  case 29:
  case 319:
  case 274:
  case 241: //our default
  case 333:
  case 329:
  case 323:
  case 331:
  case 27:
  case 82:
  case 324:
  case 350:
  case 330:
  case 28:
  case 38:
  case 39:
  case 48:
  case 74:
  case 81:
  case 45:
  case 351:
  case 84:
  case 40:
  case 46:
  case 3:
  case 51:
  case 335:
  case 336:
  case 95:
  case 22:
  case 76:
  case 15:
  case 75:
  case 278:


and here are the ones that I found to be 'steady state':
  case 407:
  case 437:
  case 274:
  case 408:
  case 413:
  case 432:
  case 355:
  case 356:
  case 283:
  case 412:
  case 282:
  case 411:
  case 409:
  case 410:

In general, the purpose behind the KiSAO ontology terms are to say "This is what I did specificially; if you want to reproduce it, do something similar'.  This means that if you don't match something exactly, it's OK; you just grab the closest algorithm that basically does the same thing, and try that.  If it doesn't work, you know where to start looking for the problem, but if it does work, you're good to go.

**Comment by matthiaskoenig** [comment]
@luciansmith 
Just for understanding: phrasedml always writes KISAO IDS in the SED-ML files, never strings like "BDF" or "CVODE", ...

If one does for instance in phrasedml
```
sim1.algorithm = rk4
sim1.algorithm = kisao.32
```
this will always be translated to KISAO terms by phrasedml.

**Comment by luciansmith** [comment]
Correct.  Certain KiSAO terms are recognized by phrasedml itself, and it will automatically translate the ID to a keyword, but SED-ML itself has no keyword system; it's all IDs.

**Comment by matthiaskoenig** [comment]
Just finished the tests. Two things I noticed:
[1]
I cannot find the following settings mentioned in the phrasedml tutorial for any roadrunner integrator:
- **maximum_iterations** (486; the maximum number of iterations the algorithm should take before exiting)
- **minimum_damping** (487; minimum damping value) 
[2]
`stiff` is currently not  a supported keyword in phrasedml 
see https://sourceforge.net/p/phrasedml/tickets/17/

**Comment by luciansmith** [comment]
Looks like the online phrasedml Tutorial is old; I'll update.

As far as 'stiff' goes, there's discussion on your ticket, but it was decided that in KiSAO, 'stiff' was a characteristic of the algorithm itself, and not a parameter that could be applied to an algorithm.  Basically, any given specific algorithm can be analyzed to see if it's stiff or not (or if it's both, as LSODA is).

**Comment by hsauro** [comment]
Strictly speaking stiff is a characteristic of the model.

Herbert

**Comment by luciansmith** [comment]
True, but then you use different algorithms to solve the two types, correct?

Also, not sure if you saw this, but 'maximum_iterations' and 'minimum_damping' are algorithm parameters in roadrunner of the steadystate algorithm.

**Comment by hsauro** [comment]
"but then you use different algorithms to solve the two types, correct?"

Yes you do though you can use a solver that has the ability to solve stiff
systems on any problem, stiff or non-stiff."

Yes I think I knew about the steady state tuning parameters, but not sure
why it matters?

H

**Comment by luciansmith** [comment]
The steady state tuning parameters were for Mattias--he had posted that he couldn't find the options in roadrunner.

The ultimate question about stiff algorithms is that there is a roadrunner option 'stiff' that you can set to be 'true' or 'false'.  From what I understand, setting that parameter one way or the other modifies what algorithm is used by roadrunner 'under the hood'.  Is this the case?

**Comment by 0u812** [comment]
Yes that's correct

On March 8, 2016 12:02:32 PM PST, Lucian Smith <notifications@github.com> wrote:
>The steady state tuning parameters were for Mattias--he had posted that
>he couldn't find the options in roadrunner.
>
>The ultimate question about stiff algorithms is that there is a
>roadrunner option 'stiff' that you can set to be 'true' or 'false'. 
>From what I understand, setting that parameter one way or the other
>modifies what algorithm is used by roadrunner 'under the hood'.  Is
>this the case?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/tellurium/issues/103#issuecomment-193944630

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by matthiaskoenig** [comment]
Just for understanding:
maximum_iterations & minimum_damping are steadyState Solver Parameters ?
If yes, how do I see a list of the available steadyState solver parameters and how do I set these parameters in roadrunner?

And yes "stiff" is a parameter on the cvode solver which is set via
r.getIntegrator().setSetting('stiff', True)
So I would naturally want to encode this with a SEDML AlgorithmParameter on the cvode Algorithm.

**Comment by 0u812** [comment]
You can call r.steadyStateSolver.settingsPyDictRepr(). I'll add it to 
the steady state solver repr in a future release.

**Comment by luciansmith** [comment]
I used 
http://sys-bio.github.io/roadrunner/python_docs/using_roadrunner.html#solvers
to find the various settings, namely:

r.setIntegrator('steadystate')
r.getIntegrator().getSettings()

which returns a vector of possible parameters you can set.  It worked when I tried it last; hopefully it's still a going concern.

For 'stiff', as noted, you cannot do what you want to do.  Instead, you have to query the KiSAO ID of the algorithm itself.  If it is a stiff CVODE algorithm, you must then set the solver to CVODE, and set 'stiff' to 'true'.  If it is a non-stiff CVODE algorithm, you must then set the solver to 'CVODE' and set 'stiff' to 'false'.  If it is an algorithm that uses both stiff and non-stiff methods to produce the solution (like LSODA), you have to do your best, based on the capabilities of roadrunner.

**Comment by matthiaskoenig** [comment]
The syntax for the steadyState solvers is 
```
print(r.getRegisteredSteadyStateSolverNames()) # get available solvers
r.setSteadyStateSolver('nleq') # set solver
solver = r.getSteadyStateSolver() # get solver
print(solver.settingsPyDictRepr()) # solver settings
```
The following is not working (probably should not work)
```
r.setIntegrator('steadystate')
```
This info is not really available in the roadrunner documentation
see https://github.com/sys-bio/roadrunner/issues/311

@luciansmith 
will handle the stiff like you proposed

**Comment by matthiaskoenig** [comment]
The steadyStateSolver settings and stiff/nonstiff integrator are now implemented in tesedml.
