### ISSUE TITLE
Problem with relative imports

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#108]
On Linux, I usually use Tellurium via adding it to the PYTHONPATH, which means I can easily update Tellurium by doing a git pull. I don't like installing to Python's site packages directory because 1) I have remember to remove/overwrite it each time I update and 2) installing to site-packages unnecessarily adds a step to using Tellurium. Now that there are relative imports I get the following error:
```
Traceback (most recent call last):
  File "bistable-stochastic.py", line 1, in <module>
    import tellurium as te
  File "/home/poltergeist/devel/src/tellurium-gh/tellurium/tellurium.py", line 16, in <module>
    from .sedml import tephrasedml
ValueError: Attempted relative import in non-package
```

Are there alternatives to using relative imports here? If at all possible I'd like to stick with the PYTHONPATH solution.

**Comment by matthiaskoenig** [comment]
Yes. Should be possible with absolute impots. Will fix this

**Comment by matthiaskoenig** [comment]
Fixed.
The import was not even used. 
There should be no other relative imports in the code base. If anyone finds relative imports please change to absolute imports.
