### ISSUE TITLE
This plotting code no longer works

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#111]
This code no longer works, can't set axes labels.

import tellurium as te
import pylab

r = te.loada ('''
   $Xo -> S1; k1*Xo;
   S1 -> $X1; k2*S1;
   k1 = 0.2; k2 = 0.4; Xo = 1; S1 = 0.5;
''')

m = r.simulate (0, 50, 100, ["time", "S1"]);
pylab.ylim ((0,1))
pylab.xlabel ('Time')
pylab.ylabel ('Concentration')
pylab.title ('My First Plot ($y = x^2$)')
r.plot (m)

File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\tellurium\tellurium.py", line 772, in plot
    plt.xlabel(xlabel)

TypeError: 'str' object is not callable

[('tellurium', '1.3.1'),
 ('roadrunner',
  '1.4.3; Compiler: Microsoft Visual Studio 2013, C++ version: 199711; JIT Compiler: LLVM-3.5; Date: Feb 18 2016, 16:23:04; LibSBML Version: 5.11.0'),
 ('antimony', 'v2.8.0'),
 ('snbw_viewer', 'No information for sbnw viewer'),
 ('libsbml', '5.12.0'),
 ('libsedml', '300'),
 ('phrasedml', 'v0.5 beta')]

**Comment by kirichoi** [comment]
The issue is solved in version 1.3.2

**Comment by hsauro** [comment]
I confirm it works.

Herbert

**Comment by kirichoi** [comment]
@0u812: Please double check it works on mac as well.
