### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#112]
I installed (windows) the latest version 1.3.2 this morning, at the end of the installation I selected the view the readme file and got this error:

![image](https://cloud.githubusercontent.com/assets/1054990/13682709/da2524a6-e6b7-11e5-976e-631f521b069e.png)

**Comment by kirichoi** [comment]
Oops, didn't realized that README.txt is no longer used. Updated installer will go up soon.

**Comment by kirichoi** [comment]
Fixed
