### ISSUE TITLE
Editors doesn't display & characters

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#122]
In my version of tellurium 1.3.2, if I type the & character in a string or out side a string in the editor the & is invisible. I tried other characters and they seem ok except ` and ~, they are also invisible.

Looks like its a font problem. I picked another font and the character is visible.

**Comment by kirichoi** [comment]
Can you tell me which type of font is problematic? The default font set for Tellurium works fine.

**Comment by hsauro** [comment]
Most work ok, I've switched anyway to another one. This is  spyder issue so
I don't think we should worry about it at this stage.

Herbert
