### ISSUE TITLE
Allow plot style in sedml translation to be changed

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/tellurium#126]
Allow plot style in sedml translation to be changed (i.e. markers, linewidth, etc.)

**Comment by matthiaskoenig** [comment]
Not part of SED-ML L1V3. This will be implemented with the SED-ML L1V4 changes to plots.
So won't fix for now.

**Comment by matthiaskoenig** [comment]
Closing this for now. This will be part of the SED-ML L1V4 implementation after COMBINE.
