### ISSUE TITLE
Export SBML and SEDML directly from experiment object

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/tellurium#127]
Export SBML and SEDML directly from experiment object which is based on antimony and phrasedml

**Comment by matthiaskoenig** [comment]
Hi Kiri,
could you explain what you mean with this? Is this still relevant or is the experiment object obsolete/deprecated in the meanwhile?
M

**Comment by kirichoi** [comment]
This is an obsolete issue. I'm closing it.
