### ISSUE TITLE
Return array data from simulation when executing sedml directly

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/tellurium#128]
Return array data from simulation when executing sedml directly.
Current implementation returns plots and reports but there is no simple way to access the raw data.

**Comment by matthiaskoenig** [comment]
Yes, there is. 

Was before `tesedml.executeOMEX`, is now `tesedml.executeCombineArchive`. You just send in a CombineArchive and get back all the DataGenerators with the raw data. I am using this to convert the raw data to JSON and sending to browser.

Part of the latest merge.
