### ISSUE TITLE
Something is wrong with newlines in the docs/_build directory

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#132]
git is complaining about line endings in the docs/_build directory and making it really hard for me to do any sort of git work. It looks like auto-generated html, which probably shouldn't be versioned anyway. Is it okay if I just delete it? I will also docs/_build to the .gitignore.

Please let me know now if you need this directory, otherwise it is going away.

**Comment by luciansmith** [comment]
Line endings have only been a problem since the 80s, so it makes sense that git can't handle them yet.
