### ISSUE TITLE
Create tellurium logo

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#138]
I could not find any tellurium logo.
We should create a logo for outreach & and to be recognizable (put on slides, web pages, ...)

**Comment by matthiaskoenig** [comment]
Just created a simple button as placeholder until something final is decided

![te](https://cloud.githubusercontent.com/assets/900538/19279234/e2e9c704-8fe0-11e6-89be-fe5f8a5907d5.png)

**Comment by luciansmith** [comment]
I made a logo ages ago--the orange triangle.  It should be in the source
code--could you not find it?  There are both filled and empty versions.

-Lucian

**Comment by luciansmith** [comment]
The files that seem to be still checked in are:

https://github.com/sys-bio/tellurium/tree/master/spyder_mod/img_src
https://github.com/sys-bio/tellurium/blob/master/spyder_mod/favicon.ico

I also have the original versions of those files, which might be worth
checking in if we want to create new versions for stuff.  I can also look
up what font 'Tellurium' is.

-Lucian

**Comment by matthiaskoenig** [comment]
@luciansmith Perfect. Could you checkin the original files at
`/docs/images`
@kirichoi You should add the logo on http://tellurium.analogmachine.org/ in the heading,
I will add here in the README.md

@all Is there a phrasedml logo?

**Comment by luciansmith** [comment]
https://sourceforge.net/p/phrasedml/code/HEAD/tree/trunk/doc/phrasedml_logo.png

It's not an icon like the Tellurium one, though.  My thought was that you
could use the script 'p' if you needed something like that, but it never
came up.

-Lucian

**Comment by kirichoi** [comment]
Tellurium website is updated (logo in the main page and the site icon) Let me know if there's any other place that I should put the logo on.
Also, I am attaching much more versatile png version of the logo that I generated if anyone needs it.
![favicon](https://cloud.githubusercontent.com/assets/7672320/19371125/795ea1e8-9165-11e6-8364-1d406ef8e938.png)

**Comment by matthiaskoenig** [comment]
Put it in the /docs/images and on the README.md.
