### ISSUE TITLE
Support Spyder 3

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/tellurium#140]
Adding support to Spyder 3.0.0 requires several changes to Spyder modification and Spyder plugins.

**Comment by 0u812** [comment]
Why? Are they dropping 2.x?

**Comment by kirichoi** [comment]
Spyder 3.0.0 is not Python 3 nor PyQt5 specific and came out of beta for some time. I think it fixed many bugs and starting to add support for it is a good idea.

**Comment by matthiaskoenig** [comment]
Yes, please support. 
Spyder 3.0.0 is already the default on Ubuntu 16.04 and using it there.

**Comment by kirichoi** [comment]
Finally got some plugins working again. Now that the Spyder plugins are modularized, we need a separate repository for each of them, complete with setup script so that these can be easily deployed. Or should we go with everything integrated in a single repo perhaps so that installing once will install all and every plugins?

**Comment by 0u812** [comment]
I would prefer separate repos for each plugin.

**Comment by kirichoi** [comment]
So far, Import, RateLaw, and openSBML plugins are fixed. They are located in my own repo but soon will be forked to sys-bio. Might put these up on PyPI as well.

**Comment by kirichoi** [comment]
Current Spyder version 3.1.3 has some issues with Python console. According to Spyder devs, Python console will be removed and replaced entirely by IPython console by Spyder 3.2.0. Might be wise to wait a bit.

**Comment by matthiaskoenig** [comment]
Spyder 3.2.4 is out.

**Comment by kirichoi** [comment]
Tellurium 2.0.3 and onward support Spyder 3+
