### ISSUE TITLE
sbmlToCellML not working for user

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/tellurium#147]
I've been working with a user to try to get our translations to work, and her latest report looks like a bug in tellurium itself:

import tellurium as te
cellml_model = te.sbmlToCellML("BIOMD0000000001.xml")

gives
AttributeError: 'module' object has no attribute 'getCellMLString'

At a guess, this is because the version she's using was not compiled with CellML support, so those functions were not included.  Should I point her to the latest version instead?  She's using linux.

**Comment by 0u812** [comment]
I think it's a team communication issue. I added an issue to the tracker so we can formalize CellML support. Please see #148.
