### ISSUE TITLE
draw() does not execute even when graphviz is on the system

### ISSUE THREAD

**Issue by djinnome** [sys-bio/tellurium#151]
Referencing line https://github.com/sys-bio/tellurium/blob/master/tellurium/tellurium.py#L734

When I try to execute tellurium.draw(), I get the following error:

"Graphviz is not installed in your machine. 'draw' command cannot produce a diagram",

However, I do have graphviz installed:
```bash
$ which dot
/usr/local/bin/dot
```
therefore, instead of platform-specific checks for a directory named graphviz:
       ` elif sys.platform == 'darwin' and 'graphviz' not in os.environ['PATH']:`
I recommend the following:
      ` if any([ os.access( os.path.join( p, 'dot' ), os.X_OK ) for p in os.environ['PATH'].split( os.pathsep )]):`

**Comment by 0u812** [comment]
Good to hear from you Jeremy! I just pushed your suggested fix to the master branch.

**Comment by djinnome** [comment]
Hey Kyle,  

Wow, that was quick! Thanks for the lightning fast turnaround.

Jeremy

**Comment by 0u812** [comment]
Happy to help! I don't know if you are using the Anaconda installation or your own checkout of the source, but just fyi we will be switching to pip soon because it was requested in some reviews of our manuscript. I will make a new release here on GitHub when it's ready.
