### ISSUE TITLE
Broken link in Tellurium Documentation

### ISSUE THREAD

**Issue by djinnome** [sys-bio/tellurium#152]
Hi folks,

The [Test Models](http://svn.code.sf.net/p/libroadrunnerdocs/code/tellurium/html/group_testmodels.html) link on the [Tellurium Documentation](http://svn.code.sf.net/p/libroadrunnerdocs/code/tellurium/html/modules.html) Modules page is broken.

**Comment by kirichoi** [comment]
We have updated the [documentation](https://tellurium.readthedocs.io/en/latest/).
