### ISSUE TITLE
New Archive Type: .tea

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#155]
I'm going to implement a new feature for reproducibility. I want to address reproducibility within Tellurium itself. When the version of a package changes, the behavior can also change.

A .tea archive contains all the files required for running a script and will record the exact versions of all packages used by the script so that the behavior can be reproduced exactly. See https://github.com/sys-bio/tellurium/wiki/.tea-Archive-Specification.

**Comment by hsauro** [comment]
ok
