### ISSUE TITLE
Get Zenodo DOIs

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#158]
Need to get Zenodo DOIs for Tellurium and possibly RoadRunner/Antimony.

**Comment by matthiaskoenig** [comment]
This is very easy and I did it for some repositories. There is a zenodo-github integration via release hooks.
The important part is to register a repo branch with zenodo once, afterwards there is a zenodo archive created automatically for every new release of the registered branch:

see
https://guides.github.com/activities/citable-code/

Takes probably 5 minutes.
