### ISSUE TITLE
Add wrapper for bifurcation tool

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#159]
The bifurcation tool is pretty nice but it lacks an easy-to-use interface. I want to create one before the paper submission.

**Comment by hsauro** [comment]
What kind of user interface do you mean?

Herbert

**Comment by 0u812** [comment]
I haven't completely firmed it up yet, but we currently need all this code just to plot a bifurcation diagram (this example comes from [here](https://github.com/sys-bio/tellurium-examples/blob/master/bifurcationExample.py)):
```python
# Setup properties
auto.setProperty("SBML", readAllText(sbmlModel))

# Bifurcation specific properties
auto.setProperty("ScanDirection", "Positive")    
auto.setProperty("PrincipalContinuationParameter", "A")
auto.setProperty("PCPLowerBound", 10)
auto.setProperty("PCPUpperBound", 150)
    
# Set maximum numberof points
auto.setProperty("NMX", 5000)  
       
# execute the plugin
auto.execute()
         
# plot Bifurcation diagram
pts     = auto.BifurcationPoints
lbls    = auto.BifurcationLabels
biData  = auto.BifurcationData    
biData.plotBifurcationDiagram(pts, lbls) 
```

Whereas we could add another layer to accomplish that in one line:
```python
import tellurium as te
te.plotBifurcation('/path/to/sbml','A',10,150)
```

If you want to scan in reverse or change the maximum number of points, you could pass keyword arguments:
```python
te.plotBifurcation('/path/to/sbml','A',10,150,scan='reverse') # maxpoints=123, etc.
```
Also, we could have a sister function to just get the data without plotting it:
```python
points, labels, data = te.bifurcation('/path/to/sbml','A',10,150)
# Should be equivalent to the following:
# ... boilerplate for setting up the auto plugin goes here
points     = auto.BifurcationPoints
labels     = auto.BifurcationLabels
data       = auto.BifurcationData   
```

The old way would still remain, of course. This would just be a convenience wrapper.

**Comment by 0u812** [comment]
One more thought: For the functions I just proposed, i.e. `plotBifurcation` and `bifurcation`, the first argument is the path to an SBML file. For the sake of convenience, I think it would be great to also allow anything that can be converted to an SBML model to be passed instead. Examples:
* The path to an Antimony model (should end in extension `.sb` for this to work)
* The SBML XML content as a string
* The Antimony code as a string
* A roadrunner model (which can be converted to SBML via RoadRunner.[getSBML](http://sys-bio.github.io/roadrunner/python_docs/api_reference.html#RoadRunner.RoadRunner.getSBML))
