### ISSUE TITLE
Unable to ship with libSBML Arrays package

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#160]
Just fyi I ran [into a problem](https://github.com/NuML/NuML/issues/6) trying to build some of our dependencies. I think this will require a fix upstream. For now, the best I can do is disable the arrays package as a work-around. I don't think anyone here is using the arrays package ATM, but we might in the future.

**Comment by 0u812** [comment]
Never mind, looks like there is a workaround

**Comment by 0u812** [comment]
Never mind, looks like there is a workaround

**Comment by 0u812** [comment]
It turns out we can't build the entire software stack with Arrays support (https://github.com/sbmlteam/libCombine/issues/7), so we might as well not enable it at all. It would be really confusing for users if Arrays worked in libSBML but the moment they try to put them in a Combine archive everything crashes. I'm disabling Arrays support for now.

**Comment by matthiaskoenig** [comment]
I think the array package becomes only required as soon as roadrunner supports it. So should be no problem disabling it.

**Comment by 0u812** [comment]
Got a workaround thanks to Frank. Arrays should be working in my [wheels](https://github.com/sys-bio/wheelhouse).
