### ISSUE TITLE
Telluirum API docs are out of date. 

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#163]
The Tellurium API docs are out of date, not only that but we seem to have to versions of the doc, one doxygen and another readthedocs. Readthedocs has pretty pictures but little actual documentation. Doxygen has only one pretty picture but has docuemtation text.

The docs needs to be resovled.

**Comment by kirichoi** [comment]
Tellurium readthedocs should point to `master` branch instead of `mkoenig` branch

**Comment by matthiaskoenig** [comment]
I will fix the issues with the docs next week.

**Comment by matthiaskoenig** [comment]
If there is missing information which should be added to the documentation let me know. I will update the tutorials/examples in the next few days.
Things I wanted to add where
- more about steady state analysis
- promoting local parameters
- more about sensitivity analysis 
- more about setting model settings & resetting (even I don't understand what the different reset functions are doing and is a lot of trial and error for me)

Anything which should be redone/updated post in this issue.
