### ISSUE TITLE
Move code into separate repos?

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#165]
A lot of the tellurium code is currently in submodules, e.g. analysis, notebooks, sedml etc. For some of the larger submodules like sedml, it might make sense to split them off into their own separate repos and PyPI packages which depend on tellurium. I could make a tellurium-complete PyPI package that installs everything.

**Comment by matthiaskoenig** [comment]
Please not. It is much easier to have everything in one repository for now instead of fragmenting the information.
This can be closed from my side.
