### ISSUE TITLE
Add importers for other Python libraries supporting SBML

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#166]
I realized that in order to convince the reviewers of our manuscript that this tool is broadly useful for the whole community, it might be necessary to support converting from other Python libraries to a RoadRunner instance (provided those libraries support exporting as SBML). Will add libraries here as I think of them:
* PySB

**Comment by matthiaskoenig** [comment]
I don't understand this issue. For me SBML is the exchange format between tools (or combine archives). So why do we need another importer? and for what file format?

**Comment by hsauro** [comment]
Agreed, don't quite understand kyle's comment. If pysb can export sbml
there there isn't an issue. Question is can it?

Herbert

**Comment by matthiaskoenig** [comment]
Closing this. Nothing to do here. Please reopen if there is an issue.
