### ISSUE TITLE
r.model.getConservedMoietyIds() should be surfaced to r..getConservedMoietyIds()

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#185]
getConservedMoietyIds() is currently under model, surface it so that it can be accessed by:

r.getConservedMoietyIds()

**Comment by 0u812** [comment]
Sorry - I meant to fix this already. The change I just pushed should fix it. Curiously, the conserved totals already have names like `cm_0_UUID`, `cm_1_UUID`, so they already have the indexing. Perhaps the UUID is necessary to resolve some ambiguity. Let me see if the change I just made breaks the test suite. If it doesn't, I think it's safe.

**Comment by 0u812** [comment]
And it broke. Let me take a look.

**Comment by 0u812** [comment]
It turns out the reason the build broke had nothing to do with this (something changed with the Travis VM I guess). Anyway, I fixed this issue and the Travis build issue. The test suite passes so I'm working on producing a release now.

**Comment by hsauro** [comment]
ok good, let me know when you have a set of windows binaries I can try.

Don't forget to update the documentation.

H

**Comment by 0u812** [comment]
Do you know if you are still on the 32-bit binaries? If so, I can send the binaries to Kiri who can update Tellurium. Alternatively, I can send the binaries directly to you and you can run `python setup.py install`, which would be a little faster. Please let me know which you would prefer.

**Comment by hsauro** [comment]
Update Tellurium and I'll install a new tellurium.

H

**Comment by kirichoi** [comment]
Tellurium is updated. Use this [link](https://sourceforge.net/projects/pytellurium/files/Tellurium-1.3/1.3.6/Tellurium-1.3.6-Python-2.7-win32-portable-setup.exe/download) to download.

@hsauro I did not bump the version number so you will have to remove the pre-existing version first before installing the updated version.

I'm closing this issue assuming the bug is fixed.
