### ISSUE TITLE
Unique names for conserved totals is becoming a problem.

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#186]
Conserved totals get names that look like:

cm_0_80289de0_508b_11e7_a90e_6c626de50893

Unfortunately they change every time a model is run. This means that any code that uses the name must be updated *everytime* the program is run. This is very annoying and time consuming. For example when computing the response coefficient of a variable with respect to a conserved total, the cosnerved total names has to be updated every time. 

Make a change to the naming convention for conserved totals, to use something like:

CSUM1, CSUM2, etc

One could use

_CSUM1, _CSUM2

to avoid potential clashes with user names.

Question, should numbering start at 1 or 0? If matrices such as the conserved matrix are indexed from 0 then I guess use CSUM0

**Comment by 0u812** [comment]
I just pushed a change that should fix this. I used 0-indexing because the matrices are indexed from zero.
