### ISSUE TITLE
libnuml needed as dependency for SED-ML data support

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#189]
Hi all,

for SED-ML data support the numl python functionality is needed in tellurium.
This means the following python package should be added in the wheelhouse and the tellurium dependencies
https://github.com/NuML/NuML/tree/master/libnuml

Currently, the numl functions are exposed via libsedml python bindings, but do not work
see https://github.com/fbergmann/libSEDML/issues/48

For python package of libnuml see also
https://github.com/NuML/NuML/issues/8

Matthias

**Comment by hsauro** [comment]
Agreed

Herbert

**Comment by matthiaskoenig** [comment]
Hi all, 
pip packages are available and I added them to the requirements.txt and setup.py.
Please make sure to package libnuml also in the notebook and spyder versions.
M

**Comment by matthiaskoenig** [comment]
@0u812 
I am adding the python-libnuml back into the requirements (saw you removed this in the latest commits).
Needing this for the SED-ML L1V3 data support. If this is not working you should create a tenuml package.

**Comment by matthiaskoenig** [comment]
@kirichoi and @0u812 
Are you packaging this with spyder and notebook version? The data parts of SED-ML require this dependency.

**Comment by 0u812** [comment]
Thanks Matthias. I will create a tenuml binary wheel.

**Comment by kirichoi** [comment]
I don't think it's packaged with Spyder version but should be easy since I already have built it somewhere for libSEDML

**Comment by matthiaskoenig** [comment]
@0u812 Any chance to make this happen?

The tellurium SED-ML data support is basically implemented, but having lots of issues with libnuml not being build the same way like the other packages (lots of segmentation faults, invalid pointers, ..., depending on import oder of libnuml with other packages).

I want to get out the SED-ML data support this week, so we can accept SED-ML L1V3 before COMBINE. This issue is a bottleneck right now and something I cannot solve.

**Comment by matthiaskoenig** [comment]
Here some examples of the problems: You can see that the symbols are overwritten by the NuML import, also the python interpreter just dies unexpectedly. 
```
try:
    import libcombine
except ImportError:
    import tecombine as libcombine


print(dir())
time1 = libcombine.OmexDescription.getCurrentDateAndTime()
print(type(time1))

import libnuml
time2 = libcombine.OmexDescription.getCurrentDateAndTime()
print(type(time2))

import imp
imp.reload(libcombine)
time3 = libcombine.OmexDescription.getCurrentDateAndTime()
print(type(time3))

print("end")
```
Results in:
```
/home/mkoenig/envs/tellurium/bin/python /home/mkoenig/git/tellurium/tellurium/tests/sedml/test_import.py
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'libcombine']
<class 'tecombine.libcombine.Date'>
<class 'libnuml.Date'>
<class 'libnuml.Date'>
end

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by 0u812** [comment]
That is indeed a problem. I will get right on this. Sorry for the delay.

**Comment by 0u812** [comment]
Before I can produce the binaries, I need Frank to [add the PYTHON_USE_DYNAMIC_LOOKUP flag to libnuml](https://github.com/NuML/NuML/issues/12) as he has with other libraries. He's usually very quick, so I anticipate this will be fixed shortly and I will continue at that point.

**Comment by 0u812** [comment]
Binaries for numl are available on PyPI for all three platforms. Installation:
```
pip install tenuml
```

**Comment by matthiaskoenig** [comment]
Thanks for this. Is now in master branch.
