### ISSUE TITLE
Switching readthedocs latest branch to master

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#197]
If it's okay, I'm going to switch the latest branch on readthedocs to master for now (so latest will be the same as stable), since it has the latest changes for 2.0 and it should be the one that the reviewers will see. If someone wants to change it to a bleeding-edge branch after the reviews are back, that's fine, but please make sure it contains the latest changes from master. I'm also trying to move all the docs from WP (tellurium.analogmachine.org) over to readthedocs.

**Comment by matthiaskoenig** [comment]
I think this can be closed. Already done by Kyle
@0u812 ?

**Comment by 0u812** [comment]
Correct, can be closed.
