### ISSUE TITLE
Troubleshooting with tellurium

### ISSUE THREAD

**Issue by doppioandante** [sys-bio/tellurium#198]
Hi, I'm trying to use tellurium on a debian stretch vm.
I can't get cells to run inside the notebook (the cell execution indicator remains [*] for the whole time).
The terminal doesn't report anything except the usual starting text:
```
Gtk-Message: Failed to load module "canberra-gtk-module"
[22:48:33:0878] [info] args { _: [],
  version: false,
  v: false,
  help: false,
  h: false,
  kernel: 'python3',
  k: 'python3',
  '$0': '/opt/Tellurium/tellurium',
  verbose: undefined }
[22:48:34:0051] [info] launching an empty notebook by default
```
FWIW the installation had some hiccups (javascript errors on the first run) but everything seems to load correctly now except for python.
How can I debug this?

**Comment by 0u812** [comment]
Hi Enrico, sorry to hear you are having trouble. I tested it on a Debian 8 VM and I hoped it would just work on newer distros, but alas! Tellurium keeps its local Python under `~/.config/Tellurium`. Can you try the following in Bash and post the output/errors here?

```bash
~/.config/Tellurium/telocal/python-3.6.1/bin/python3 -c 'import tellurium'
```

**Comment by doppioandante** [comment]
Hi Kyle, no worries.
This is what I get:
```
~/.config/Tellurium/telocal/python-3.6.1/bin/python3 -c 'import tellurium'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/enrico/.config/Tellurium/telocal/python-3.6.1/lib/python3.6/site-packages/tellurium/__init__.py", line 89, in <module>
    from .analysis.parameterestimation import ParameterEstimation
  File "/home/enrico/.config/Tellurium/telocal/python-3.6.1/lib/python3.6/site-packages/tellurium/analysis/parameterestimation.py", line 4, in <module>
    from scipy.optimize import differential_evolution
  File "/home/enrico/.config/Tellurium/telocal/python-3.6.1/lib/python3.6/site-packages/scipy/optimize/__init__.py", line 233, in <module>
    from ._minimize import *
  File "/home/enrico/.config/Tellurium/telocal/python-3.6.1/lib/python3.6/site-packages/scipy/optimize/_minimize.py", line 30, in <module>
    from .lbfgsb import _minimize_lbfgsb
  File "/home/enrico/.config/Tellurium/telocal/python-3.6.1/lib/python3.6/site-packages/scipy/optimize/lbfgsb.py", line 44, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "/home/enrico/.config/Tellurium/telocal/python-3.6.1/lib/python3.6/site-packages/scipy/sparse/__init__.py", line 241, in <module>
    from .csgraph import cs_graph_components
ImportError: cannot import name 'cs_graph_components'
```
It seems a weird error to me, but it's right:
```
wc -c /home/enrico/.config/Tellurium/telocal/python-3.6.1/lib/python3.6/site-packages/scipy/sparse/csgraph/__init__.py 
0 /home/enrico/.config/Tellurium/telocal/python-3.6.1/lib/python3.6/site-packages/scipy/sparse/csgraph/__init__.py
```
The csgraph submodule is empty... how this happened I have no idea, should I try to reinstall the package?

**Comment by 0u812** [comment]
Hi Enrico, that is indeed an odd error. Please wipe the app data dir using 
```bash
rm -rf ~/.config/Tellurium
```
and re-launch the Tellurium app. On the first startup, it will create this directory and copy the Python environment into it (you should see a loading screen that says "performing first-time initialization"). After it is done copying, it will open a new notebook for you. Make sure it doesn't get interrupted before it finishes copying.

Also, I can confirm that the csgraph should not be empty:
```bash
wc -c ~/.config/Tellurium/telocal/python-3.6.1/lib/python3.6/site-packages/scipy/sparse/csgraph/__init__.py 
7646 /home/poltergeist/.config/Tellurium/telocal/python-3.6.1/lib/python3.6/site-packages/scipy/sparse/csgraph/__init__.py
```

**Comment by doppioandante** [comment]
Ok so this made the errors I was talking about reappear: [screenshot](https://imgur.com/AndWOqg)
There are two javascript errors that go away when clicking okay, but the other message closes tellurium if I close the dialog.
The console doesn't report anything.
I'll take a closer look tomorrow.

**Comment by 0u812** [comment]
Hi Enrico, this looks like errors I used to see in early alpha releases. Are you using the latest .deb from [here](https://github.com/sys-bio/tellurium/releases/download/2.0.0-alpha9/Tellurium_2.0.0_amd64.deb)?

**Comment by doppioandante** [comment]
@0u812 Hi, I've checked today and I'm sure it was the latest deb available (alpha9).
I would debug this myself but I don't know where to look, the fact that tellurium is a bundled binary (AFAICT) doesn't help. I think I'll wait for the next alpha to see if it works again.

In the meantime I'm trying with pip, but I doubt this would give problems.

**Comment by 0u812** [comment]
I'll try to look into this on a vm for Debian 9.

**Comment by 0u812** [comment]
Btw Enrico, if you would like to try troubleshooting this, you can get the source for the notebook viewer [here](https://github.com/0u812/nteract) (please checkout the `bundle-python3.6` branch). You can simply run `npm install && npm run start` to start the viewer. Unfortunately, the source is webpacked, so even if you get line numbers for those exceptions it will be in one giant js file. I'm afraid this might be difficult to debug, which is why I will try it in a vm, but if you would like to work on this any insight you can provide would be welcome.

**Comment by doppioandante** [comment]
Hi Kyle, wait before testing if you haven't already, I'm now thinking that it's probably a case of full disk, this would also explain why those files were missing. I'm trying again with a bigger disk size.

**Comment by 0u812** [comment]
Okay, thanks for letting me know!

**Comment by doppioandante** [comment]
Ok, this was indeed the case. I was mislead by the fact that there still was space in the disk, but I realized the home folder was in a separate partition that was too small. A new VM with everything under the same partition worked.
