### ISSUE TITLE
Add function to bundle additional files with COMBINE archives

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#206]
Kiri had the suggestion that we should support some way of bundling additional files with COMBINE archives in order to preserve as much information as possible about the study, similar in spirit to Martin Scharm's [COMBINE showcase](https://figshare.com/articles/COMBINE_Archive_Show_Case/3427271). The extra files might be e.g. simulation results, plots, pdfs, or the entire notebook. Of course, these files will not be readable by other software, but they might be useful as a reference for future researchers trying to reproduce the entire study.

For this issue, I want to add a top-level function to Tellurium to allow bundling these various files and document it.

**Comment by 0u812** [comment]
The files all need to have associated format information, e.g. `http://purl.org/NET/mediatypes/image/png`, `http://purl.org/NET/mediatypes/text/plain`.

**Comment by kirichoi** [comment]
Primarily, this is to answer the concern about not being able to exchange narratives in COMBINE format. If other software does not support it, they are the one lacking features.

**Comment by matthiaskoenig** [comment]
Yes, this should be an option. 

I.e. one should be able to execute an omex or simulation experiment and get all the results and generated python code in the combine archive.
But make it an option, i.e. the user can just execute the simulation result which will not change the archive or execute and store the information (i.e. outputs and generated code, notebook, ...) in the archive.

**Comment by matthiaskoenig** [comment]
Just adding:
Just saw https://github.com/sys-bio/tellurium/issues/155 which is related to this.
In my opinion it should be possible to add this .tea information in a subfolder in the combine archive. Don't create another archive type, but store the information in the combine archive
