### ISSUE TITLE
API doc is incomplete

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/tellurium#210]
API doc located [here](https://tellurium.readthedocs.io/en/latest/_apidoc/tellurium.html) is incomplete.

**Comment by 0u812** [comment]
Agreed. I think it's due to autodoc crashing because it can't import roadrunner (https://github.com/sys-bio/roadrunner/issues/399).

**Comment by 0u812** [comment]
What link did you click on to get to that page? Appears to be different from API doc [here](https://tellurium.readthedocs.io/en/latest/API.html).

**Comment by 0u812** [comment]
Also, API autodoc now works, so this can be closed.
