### ISSUE TITLE
Problem with bioservices as dependency

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#218]
We currently have bioservices as a dependency. It's used to automatically download biomodels given the model ID in `temiriam.getSBMLFromBiomodelsURN`. It's used in the docs in [this example](http://tellurium.readthedocs.io/en/latest/notebooks.html#sed-ml-l1v2-specification-example).

The problem is that I believe installing it requires compilation of c/c++ sources, which requires a compiler. This isn't a problem for Mac/Linux users, but Windows users have to install Visual Studio before they can install bioservices. If we keep it as a dependency, Windows users will have to install a compiler before they can install Tellurium via pip. Not ideal. I think the best solution would be to remove it as a dependency and then add a `te.installPackage('bioservices')` for that specific example in the docs to try to install bioservices before running the example.

**Comment by 0u812** [comment]
Actually, on second thought, it would be trivially easy to convert the example to not use bioservices, as in [this example](http://tellurium.readthedocs.io/en/latest/notebooks.html#model-loading-from-biomodels).

**Comment by matthiaskoenig** [comment]
I think I already implemented a fallback some time ago if bioservices is
not available.

**Comment by matthiaskoenig** [comment]
https://github.com/sys-bio/tellurium/pull/220
addresses this

**Comment by 0u812** [comment]
Fixed by #220
