### ISSUE TITLE
Is experiment class deprecated?

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#222]
Is the content of `tephrasedml.py` deprecated? or is this still used? Mainly the experiment class.
With the latest tellurium changes I am not sure if this has been replaced.

If this is replaced, what is the new way to run phrasedml with sbml?

**Comment by 0u812** [comment]
I think all of the use-cases for the experiment class are covered by inline OMEX strings. I updated the [examples in the docs to use inline OMEX](http://tellurium.readthedocs.io/en/latest/notebooks.html#inline-omex-and-combine-archives). I would be in favor of deprecating the experiment class (it was originally hacked together for a demo and seems rather limited IMO).

**Comment by matthiaskoenig** [comment]
Yes, I strongly agree and would remove it. Than I can rewrite the tests for the new inline omex.

Same question for `tellurium.tecombine.py`. Looks also completely deprecated. 
It would help a lot to remove this also if it is not used anymore.

**Comment by 0u812** [comment]
Sounds good to me. Anyone else using these?

**Comment by matthiaskoenig** [comment]
I think with major release 2.0.0 we can remove all the deprecated things.
Especially because replacement functions exist.

**Comment by matthiaskoenig** [comment]
`tellurium.phrasedml.py` and `tellurium.tecombine.py` will be removed. 
If functionality is required this will be ported.
