### ISSUE TITLE
SED-ML L1V3 data support (csv & numl)

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#225]
Support for data based on L1V3 spec. 

See also
https://github.com/SED-ML/sed-ml/issues/12
https://github.com/SED-ML/sed-ml/issues/41

**Comment by matthiaskoenig** [comment]
The following test archives have been added to test implementation. JWS must save their non-standard data after this is implemented.
```    
    # data not supported: FIXME: https://github.com/sys-bio/tellurium/issues/225
    'specification/L1V3/L1V3_plotting-data.omex',
    'specification/L1V3/L1V3_reading-data-numl.omex',
    'specification/L1V3/L1V3_reading-data-csv.omex',

    # non-standard data implementation: FIXME: https://github.com/matthiaskoenig/tellurium-web/issues/53
    'jws/omex/adlung2017_fig2g.sedx',
    'jws/omex/adlung2017_fig2bto2e.sedx',
    'jws/omex/adlung2017_fig2f.sedx',
    'jws/omex/bachmann2011.sedx',
    'jws/omex/kouril3_experiment-user.sedx',
    'jws/omex/penkler2aa_experiment-user.sedx',
    'jws/omex/perelson1996_fig1b_top.sedx',
    'jws/omex/stafford2000_fig2.sedx',
```

**Comment by matthiaskoenig** [comment]
I finished the implementation, i.e., we have full SED-ML L1V3 support in tellurium. 
But to be able to merge this with master and bring this in the next release I would need the latest `libsedml` and `libnuml` releases as `tesedml`( #231 ) and `tenuml` ( #189 ).

We will release the L1V3 SED-ML spec at the end of next week, i.e. before COMBINE. It would be great if we can make a release of tellurium which supports the new spec until than.

**Comment by hsauro** [comment]
This is excellent news. Yes we should do a release before combine.

Herbert
