### ISSUE TITLE
How to reference/cite tellurium?

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#229]
Is there a reference for tellurium right now I could cite?
If not could we submit the current paper version as preprint to get a citeable document/DOI?

**Comment by matthiaskoenig** [comment]
Found this one, but is very old
https://www.biorxiv.org/content/early/2016/05/21/054601
https://doi.org/10.1101/054601

The pre-print should be updated with the latest paper draft. 
Please make sure my name is spelled correctly "Matthias König" and orcid id is added for me orcid.org/0000-0003-1725-179X.

**Comment by hsauro** [comment]
I'm not sure about updating the copy on biorxiv because the content is
quite different compared to the new one. I would submit the reproducibility
paper as a new biorxiv paper. Kiri is writing up an updated version of the
current biorxiv paper.

Herbert

**Comment by matthiaskoenig** [comment]
@hsauro biorxiv is perfect. Just let me know when there is a version, so I can update the reference

**Comment by matthiaskoenig** [comment]
Hi all, 
is there any update on this?

I need a bibtex reference for tellurium which I can reference in the SED-ML specification. Last possibility to make a change to the spec document is this Friday. So I would a new reference until than. Otherwise I will go with the old biorxviv from above.

M

**Comment by hsauro** [comment]
Unfortunately, the only thing we currently have is the bioxriv reference.

Herbert
