### ISSUE TITLE
Update tesedml to include bugfix for plot2D attribute 'logX/Y' & format attribute

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#231]
Update tesedml to include the following bugfix:
https://github.com/fbergmann/libSEDML/issues/47

which solves all the warnings/errors of type:
```
 line 260: (01015 [Error]) Missing a required XML attribute. The plot2D attribute 'logX' is required.
  line 260: (01015 [Error]) Missing a required XML attribute. The plot2D attribute 'logY' is required.
  line 260: (01015 [Error]) Missing a required XML attribute. The plot2D attribute 'logX' is required.
```

**Comment by matthiaskoenig** [comment]
There were some last minute changes to L1V3, mainly
- an additional `format` attribute on `DataDescription` to support multiple data formats like NuML or CSV
These are already in the latest `libsedml` release, but not yet available in `tesedml`.

Updating `tesedml` is required to support the format attribute and fix the logX/Y issue reported above.

**Comment by matthiaskoenig** [comment]
@0u812 The tesedml update would be the only thing I need before COMBINE. Unfortunately, I can't do this myself.

Thanks for updating all the other libraries already.

**Comment by 0u812** [comment]
I updated tesedml to 0.43.0 (based on latest commit). I uploaded the Linux binaries. Still working on other platforms.

**Comment by matthiaskoenig** [comment]
@0u812 Thanks a lot for this. 
Just make sure that after building one of the dependencies that all tests pass and if not just fix the dependency to the latest version which worked via exact versioning.

In this case the update of tesedml broke some code, i.e. 
- update dependency
- quick check if tests pass
- if failing tests change in `setup.py` and `requirements.txt` to exact version which passes
`tesedml==0.4.2` and report issue
The master branch must always pass all tests and be as stable as possible.

Just finishing fixing the failing tests.

**Comment by matthiaskoenig** [comment]
This was solved by latest merge.
