### ISSUE TITLE
Shortcut has wrong path under Debian

### ISSUE THREAD

**Issue by doppioandante** [sys-bio/tellurium#238]
The tellurium.desktop file reads
```
Exec=/opt/tellurium/tellurium %U
```
But the actual path is /opt/Tellurium/tellurium (the first Tellurium is with capital T).
I would suggest just
```
Exec=tellurium %U
```
because there already is a symlink in /usr/local/bin which is inside PATH.

**Comment by 0u812** [comment]
Thanks for reporting this Enrico! I actually already [fixed the capitalization issue](https://github.com/0u812/nteract/blob/bundle-python3.6/package.json#L99) and I thought the fix made it into the latest .deb, but it appears it didn't. I will rebuild the deb and let you know when the new one is ready.

**Comment by doppioandante** [comment]
Thanks, closing.
