### ISSUE TITLE
Get accurate download count (Binaries should not be downloadable from github)

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#243]
I noticed that the notebook versions for Windows and Mac are being downloaded from github. This doesn't count downloads are effectively as sourceforge. As assume we can't do anything about pip installations but I suspect that we won't get as many downloads from pip anyway, the bulk will come from the ready made binaries. 

Before the PLoS paper is submitted all exe binaries should be moved to sourceforge. Sames goes for the IDE Mac version which I noticed is also on github. I know everyone likes to work with new shinny things, but in the real world we have to justify our existence. One of the reasons we got the new R01 was because the reviewers commented on the good number of downloads we have with Tellurium IDE.

**Comment by matthiaskoenig** [comment]
I think the real issue is to get a accurate download count (changed the topic). This can be easily done with github via
https://help.github.com/articles/getting-the-download-count-for-your-releases/

See some use of this for instance in
http://www.somsubhra.com/github-release-stats/?username=sys-bio&repository=tellurium

I could submit a script to the repo which on every push gets the latest stats and stores them in a text file which than can easily be displayed on the webpage and in the repo.
Currently, pypi download stats are deactivated, but as soon as they are back up these could also be displayed in such a script which would create some JSON output or similar thing
```
{
Total downloads: 123
Github downloads: 90
pypi installations: 33
...
by version
...
by time
...
```

Personally I think sourceforge is `evil` and would at all costs avoid to host anything there. There were a lot of issues in the past like advertisement overload, packaging maleware with downloads (I think with gimp), a lot of downtime, ...
Also things would be hosted at two repositories which is bad practise.

**Comment by matthiaskoenig** [comment]
Just to add. With such a solution you could also display the download stats on
http://tellurium.analogmachine.org/
One would just need a few lines of javascript to read the stats from the JSON and display them on the page. You could even make a time-dependent plot from the JSON data.

**Comment by matthiaskoenig** [comment]
Here some example code I just wrote:
https://github.com/sys-bio/tellurium/commit/0f5de2ed43949e1a42776fe9b3ece85f7c8151bf

One could just call this on every pull and automatically update the latest stats on the webpage.

![tellurium_github_downloads](https://user-images.githubusercontent.com/900538/30806241-47943366-a1f5-11e7-8b2c-45b6d8d9a80e.png)

Looks exponential to me ;)

**Comment by kirichoi** [comment]
I think the problem with github DL count is that they do not offer any detailed statistics (e.g. monthly downloads, downloads by country, etc.) I would like to transition away from SourceForge as well but I also have to admit that github's implementation is not ideal.

**Comment by hsauro** [comment]
The main problem is that someone has to maintain the script in the future.
With sourcegorge ther eis no maintenance at all and as a iresult I have
numbers going back 15 years.

I still want the binaries on soruceforge. You guys come and go but I have
to stick around and I don't want to be left with a script I don't
understand or want to understand.

Herbert

**Comment by matthiaskoenig** [comment]
Ok, that makes sense. Did not know about the advanced download statistics in sourceforge.

So we continue making releases on github (code releases which are uploaded to pypi), but just without providing any binaries for download. Is this correct? 
The binaries are than hosted somewhere were advanced download statistics exist.

**Comment by hsauro** [comment]
I want to make sure that the links from the main web page go to
sourceforge. There will be other download areas which we can't count but
I'll live with that. I don't want to the most common acces to to be the
github release page.

Herbert

**Comment by 0u812** [comment]
Just fyi I think PyPI might have the highest number. Roadrunner has 28170 total downloads and 12521 since May of this year. Some of these are CIs (including our own), but ostensibly not all.

**Comment by hsauro** [comment]
I find it hard to believe that roadrunner had had 28K downloads, are you
sure its not some kind of bot that is doing this. Something similar was
happenning to sbol

Herbert

PS If someone is knowlegeable in the class tomorrow and they want to
install tellurium IDE on the Mac what is the pip install way?

**Comment by 0u812** [comment]
It does seem hard to believe those stats, doesn't it? However, Google says it's true so it must be 😉 (I basically just followed the procedure [here](https://kirankoduru.github.io/python/pypi-stats.html) to get those numbers)

As for installing Tellurium via pip, they can run the following via a terminal:
```
sudo pip install tellurium
```
Then they can `import tellurium as te` from inside the Python interpreter. `pip` is usually tied to Python 2, - if they want to install for Python 3 they can do this:
```
sudo python3 -m pip install tellurium
```

The `sudo` is sometimes required and sometimes not depending on the setup, so I left it in to be safe.

**Comment by hsauro** [comment]
Ask Bryan how they determined that a lof of the sbol downloads was due to a
bot.

Herbert

**Comment by hsauro** [comment]
PS Looking at the link you gave, I think that's how the sbol team did the
count. You need to look at where did the downloading, then you might see
some non-human activity, then filter that out to get more likely human
downloads.

H

**Comment by kirichoi** [comment]
I do remember seeing a huge number of request from a bot or two when checking PyPI download statistics for pySBOL which seemed to check the integrity of the wheel or something. But I expect to see at least few thousand downloads for roadrunner.

**Comment by matthiaskoenig** [comment]
I am doing pypi downloads of roadrunner in many continous integrations. So
at least a few 1000 are from me alone.
