### ISSUE TITLE
Delete all the stale branches

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#247]
I would like to remove all the stale branches from github. This would make it clearer where development is happening. Most of the things are either merged or so out of date (2-4 years) that there is no sense in trying to merge this.

This would include:
* `2.0` already merged
* `events` 4 years ago, 1200 commits behind
* `tesedml` 2 years ago, this was already completely refactored, no need for this 
* `v1.3.2` 2 years ago, we are already on 2.0.2
* `conda-pkg2`, already merged
* `fix-omex-import`, 10 month old; we switched to libcombine, completly refactored
* `2.0-cutdown`, 5 month ago, we already did the 2.0 

Just give me a quick ok, than I would clean this up.

In general, after you merge a feature/bugfix with master remove the branch so it is clear that this is finished.

**Comment by matthiaskoenig** [comment]
Any opinion on this? 
Otherwise I will just go forward and remove the stale branches.

To clarify: This will just not display this old branches anymore, if one wants he/she can still recover them from the git history. But will remove clutter, and clear up where development is happening.

**Comment by kirichoi** [comment]
I don't mind removing the old unused branches.

**Comment by matthiaskoenig** [comment]
cleaned this up
