### ISSUE TITLE
Matplotlib Agg backend

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#258]
For notebook builds of Tellurium, the Agg backend of Matplotlib needs to be used. However, it was commented out in 2caf23f56309c475bb52f5422c9e0a84ebf2f66f. Can we find a way to resolve this without commenting out the Agg selection, e.g. by detecting whether Python was compiled with Tk? I can't even import Tellurium without Agg because it tries to import Tk which doesn't exist and it crashes everything. The Notebook app doesn't have Tk enabled for some platforms because it's not needed and would greatly complicate the build process.

**Comment by 0u812** [comment]
Here's one possibility:
```python
try:
    import Tkinter
except ImportError:
    if not SPYDER:
        matplotlib.use('Agg')
```

**Comment by 0u812** [comment]
Actually, I think it would be better to check if we're in IPython, because I think the above code might still try to make a window pop up if Tkinter is installed even if we're in a notebook (unless %matplotlib inline is specified).

```python
try:
    get_ipython()
except:
    if not SPYDER:
        matplotlib.use('Agg')
```

**Comment by 0u812** [comment]
Improved version. If we're in a notebook, Agg will be used. Otherwise, if Tkinter is not available, Agg will be used. For all other cases, regular backend will be used.
```python
try:
    get_ipython()
    if not SPYDER:
        matplotlib.use('Agg')
except:
    try:
        import Tkinter
    except ImportError:
        if not SPYDER:
          matplotlib.use('Agg')
```

**Comment by matthiaskoenig** [comment]
Looks good to me

**Comment by 0u812** [comment]
This fix seems to be working.
