### ISSUE TITLE
Incorrect download information on webpage

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#264]
Hi all, 

when googling for "tellurium download", one gets as first hit this outdated page
http://tellurium.analogmachine.org/stuff/

This is very confusing, shows a wrong version and outdated info.
Please remove this site from the server.

Best Matthias

**Comment by 0u812** [comment]
I added an automatic redirect from that page to the new download instructions. I also removed the old info and downloads. I think it would be best not to delete the page at that url right now, as anyone coming from Google would just get a 404.

**Comment by matthiaskoenig** [comment]
Is it possible to setup a permanent 301 redirect in your .htaccess file which lets search engines and others know that an old link has been replaced by a new one. It's the recommended method for directing traffic from an existing page.
With the current method the site will still get the hits and google won't update to the current one. With the 301 redirect it should pick this up.

**Comment by 0u812** [comment]
Done.
