### ISSUE TITLE
Latest downloads not on sourceforge and downloads are outdated

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#265]
Hi all, 
there are some issues with the downloads, i.e., on
https://github.com/sys-bio/tellurium#installation-instructions

The notebook versions all link to 
`Tellurium_2.0.0-alpha9` with downloads on github. 
If there is a new release also the downloads have to be updated.
In addition the downloads for the notebooks must be uploaded to sourceforge (see #243, currently all notebook downloads go via download of outdated git versions)

I.e. there must be `Tellurium-notebook-2.0.5-win`, `Tellurium-notebook-2.0.5-mac`, `Tellurium-notebook-2.0.5-linux` on sourceforge and linked correctly, in addition the 
`Tellurium-spyder-2.0.5-win`, `Tellurium-spyder-2.0.5-mac`.

Also the tellurium-spyder for mac is still 1.3.5 and was not updated to 2.0.5.

I will give a course based on tellurium in mid of November and need all course participants to install latest notebook versions (and if possible also the spyder versions for mac & win). These are basically biologist and clinicians so the installation of the latest version should be as easy as possible.

Best Matthias

**Comment by 0u812** [comment]
I'm currently working on the notebooks. We discontinued the Mac version of Spyder for Tellurium. It had upstream problems from Spyder that caused problems with newer versions of Mac OS X. Those problems seemed to be getting more and more frequent, so we decided that Mac users would be better off using either Tellurium Notebook or the pip packages. I'll try to make it more clear in the docs that Spyder for Tellurium is in legacy mode on the Mac.

**Comment by hsauro** [comment]
I'm not convinced that we can't get the Mac spider version working, I'd
Iike us try again once we find some time in the next 6 months.

Herbert

**Comment by matthiaskoenig** [comment]
@0u812 Yes, some clearing up will solve this. I was not aware that the Mac spyder version has such issues from the docs.

**Comment by matthiaskoenig** [comment]
I gave the README and the installation instructions an update
https://github.com/sys-bio/tellurium
Also added lots of additional badges and updated the usage image to a current image.

**Comment by matthiaskoenig** [comment]
I am happy how how things are documented now. When new notebook versions are released this can be closed.

**Comment by 0u812** [comment]
New notebooks available, should be safe to close this.
