### ISSUE TITLE
How to generate new pypi package and pypi access

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#270]
@0u812 For the pypi package we can have a very fast release cycle and basically put up a new minor version after bug fixes. 
Could you send me access to be able to upload to pypi and the information where/how you build the py2-py3 any wheel (email)? Than I could also update the info for the pypi package on Pypi and would be able to release bug fixes I need in a quick manner without having to bother you.

The front-end version releases should be only after major changes/fixes because they make much more work for you and Kiri.

Best M

**Comment by 0u812** [comment]
@matthiaskoenig can you send me your PyPI user name? Just fyi I'm currently still using the old PyPI at https://pypi.python.org.

For building releases, I run `python setup.py bdist_wheel --universal` from the tellurium directory and use `twine upload -s --sign-with gpg2 -i 9BE0E97B ./dist/tellurium-x.y.z-py2.py3-none-any.whl` to upload the release. I've been signing them with my GPG key (sort of futile at the moment but my hope is that pip will check GPG signatures at some point in the future).

You also need the following in you `~/.pypirc` file:

```
[distutils]
index-servers=
    pypi
    staging

[staging]
repository = https://testpypi.python.org/pypi
username = 0u812
password = ...

[pypi]
repository = https://upload.pypi.org/legacy/
username = 0u812
password = ...
```

**Comment by matthiaskoenig** [comment]
@0u812 Thanks for this.
My pypi account is `matthiaskoenig`. I wanted to give this a try in the next few days.

**Comment by 0u812** [comment]
I added you to the project on PyPI. Please check in before pushing a release, though. I had to revert the `process_trace` stuff in the 2.0.6 branch, as it was breaking the plots in the notebook viewer. I'm all in favor of replacing `process_trace` with something better, but I just want to make sure it doesn't break anything that the manuscript reviewers might test. 

Also, feel free to use the staging PyPI site `https://testpypi.python.org/pypi` for pushing tentative releases (esp. if there's a chance it might break something).

**Comment by matthiaskoenig** [comment]
@0u812 ok. Already have some very elegant replacement for the process_trace stuff and implemented it up to the data_gennerators, just have to fix some things in the plotting code.
Only thing breaking should be the plotting stuff, everything else is covered by tests.
