### ISSUE TITLE
Faq updated

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#282]
I noticed on the tellurium FAQ there are is the question

Does Tellurium support constraint-based modeling

The answer refers to tellurium notebook only, for the ide version tellurium comes with cobrapy already installed.

The FAQ should be updated to reflect this fact. I'm making this a priority issue because it users try the instructions given I assume they will get an error message or does the install method works on the ide version too?

**Comment by 0u812** [comment]
I think the install method will work on either the notebook or IDE version. If cobra is already installed, it's a no-op, so no harm done.

**Comment by 0u812** [comment]
Fixed.
