### ISSUE TITLE
Only Windows installers for 2.x.x - Mac Version has vanished

### ISSUE THREAD

**Issue by draeger** [sys-bio/tellurium#288]
I reinstalled my Tellurium 2.0.x by following the instructions in the Readme. I then noticed that the "new" version is 1.0.2. Browsing through the SourceForge repository reveals that only Windows installers are available for newer versions. The Mac version that I had before has vanished.

**Comment by 0u812** [comment]
Sorry! I previously had the idea to use the same version number for the notebook viewer and the tellurium Python package, but I realized that just made things more confusing. The old Mac version (which was actually just an alpha release) is [here](https://github.com/sys-bio/tellurium/releases/download/2.0.0-alpha4/Tellurium-2.0.0.dmg).

**Comment by draeger** [comment]
Thanks, this works and I got my previous environment back! Excellent. Now, it sometimes shows an error message (as a pink box at the top right) when launching:
>Error Exectuing
>no parent message id on message

But this quickly dissapears and the program works fine.

**Comment by 0u812** [comment]
That actually means the kernel is not ready yet. I changed the error message to say that in newer version of the notebook viewer, currently [1.0.2](https://sourceforge.net/projects/pytellurium/files/notebook/Tellurium-1.0.2.dmg/download). Sorry for the confusion regarding the version name - [1.0.2](https://sourceforge.net/projects/pytellurium/files/notebook/Tellurium-1.0.2.dmg/download) is the latest version of the notebook viewer, whereas [2.0.7](https://pypi.python.org/pypi/tellurium/2.0.7) is the latest version of the tellurium package. Previously, I was using the same version number for both, but that ended up being a bad way to track changes in one vs. the other. I promise not to make any more confusing versioning mistakes!

**Comment by 0u812** [comment]
For the error you're seeing, if you wait a few seconds it should go away and you will be able to execute notebook cells.

**Comment by draeger** [comment]
I would suggest to increase both version numbers to 2.0.7, maybe this would be easier.

**Comment by luciansmith** [comment]
I tend to agree--I would update everything with 'tellurium' in the name to have the same version number.  (I originally had QTAntimony and libantimony on different version numbers, but this ended up being too difficult to keep track of for similar reasons, and it ended up being clearer when everything just used the same numbering system.)

**Comment by 0u812** [comment]
Okay will do. Thanks for the feedback!
