### ISSUE TITLE
'NoneType' object has no attribute 'getNumReactions'

### ISSUE THREAD

**Issue by draeger** [sys-bio/tellurium#290]
The following code leads to an error in Tellurium 1.0.2 for macOS:
```
import tesbml as libsbml

doc = libsbml.SBMLReader().readSBML(path2sbml)
model = doc.getModel()
model.getNumReactions()
```

>AttributeError                            Traceback (most recent call last)
&lt;ipython-input-21-7d0940330f53> in &lt;module>()
----> 1 model.getNumReactions()
>
>AttributeError: 'NoneType' object has no attribute 'getNumReactions'

**Comment by hsauro** [comment]
The libsbml issue is causing some problems for me too, I can't run pysces
on telluirum because pysces expects to find libsbml not tesbml. Hence I
can't load sbml model into pysces under tellurium.

Herbert

**Comment by 0u812** [comment]
These seem to be slightly different issues. I resolved the first issue with @draeger via email. For @hsauro, I moved the issue to #291. Please feel free to continue the discussion there.
