### ISSUE TITLE
pysces expects libsbml, not tesbml

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#291]
From @hsauro in @290. The libsbml issue is causing some problems for me too, I can't run pysces on tellurium because pysces expects to find libsbml not tesbml. Hence I can't load sbml models into pysces under tellurium.

**Comment by 0u812** [comment]
One potential solution is to actually install the `python-libsbml` package via pip. This is the safest option, as it is what pysces expects. libsbml can be compiled with many different flags and settings, and the various versions don't always get along.

**Comment by 0u812** [comment]
The other solution of course would be to change the name of the tesbml directory. If we do that in the official release, that will prevent other people from installing `python-libsbml` as suggested above, so we would need to make absolutely sure tesbml works as a drop-in replacement for python-libsbml in 100% of the cases.

**Comment by hsauro** [comment]
But will ordinary users will know they have to do that, particularly when we claim that we ship libsbml with Tellurium until Sarah fixes what ever issue libsbml has.

**Comment by 0u812** [comment]
For testing, it is possible to create a .pth file in the site-packages directory that points to tesbml.

**Comment by hsauro** [comment]
What is the difference between installing python-libsmbl and shipping our
own copy? Why would I want to install python-libsbml?

One option is to provide two versions of Tellurium, a stripped down version
for people who want to tailor it to their needs (for experts) and a second
version targeted at the bulk of users (like me) who just want something to
work out of the box.

H

**Comment by kirichoi** [comment]
To me, both solutions sounds good. Both will solve any issues related to not being able to find libsbml.

@hsauro: python-libsbml is official PyPI version of libsbml. Basically soltions results in either 1) have two different libsbml with different names (libsbml and tesbml), 2) rename tesbml to libsbml. Regardless of which solution we choose, users will be able to import libsbml by `import libsbml`

**Comment by 0u812** [comment]
The official `python-libsbml` package can't be used with our stack, because it is compiled with different flags. However, other packages - pysces, pysb, etc. might rely on flags present in the official build. There's also the experimental vs. stable branch problem...

**Comment by 0u812** [comment]
@kirichoi I'm still not sure if we can get away with overriding the official libsbml, because afaik no one has tested the third-party python packages I mentioned to see if they work with our binaries or not.

**Comment by kirichoi** [comment]
@0u812 : That is a valid concern. Two libsbml packages may be the safer way to go.

**Comment by kirichoi** [comment]
BTW, could libsedml and other packages might have this kind of issues as well?

**Comment by 0u812** [comment]
Indeed. It applies to the whole libsbml/libsedml/libcombine stack. I created te- versions of each of them, and they all get along because they're all compiled and linked with the same set of flags.

**Comment by 0u812** [comment]
One thing we could do for now, which would solve Herbert's original problem, is to add a function to Tellurium which writes out .pth files for each of those libraries:
```python
import tellurium as te
te.configureShortcuts() # writes out .pth files
```

**Comment by hsauro** [comment]
Its not just my problem because we claim that users can install pysces into
tellurium.

H

**Comment by kirichoi** [comment]
I think he would like to see some out of the box solution (which I can do once we decide how to solve this). 

For libsedml, libcombine, etc. I feel like we should not worry about it until there is a realistic scenario of someone/some package trying to access these packages. I was simply wondering whether we know of any.

**Comment by hsauro** [comment]
It is possible that we could wait for the libsbml fix from Sarah, see
emails from Matthias about this (some months away). In the mean time you'll
need bold instructions on the web page on how users can acess libsbml etc
via the tesbml etc name.

Its not a great situtation to be in.

Herbert

**Comment by matthiaskoenig** [comment]
Personally, I would prefer the following solution:

> The other solution of course would be to change the name of the tesbml directory. If we do that in the official release, that will prevent other people from installing python-libsbml as suggested above, so we would need to make absolutely sure tesbml works as a drop-in replacement for python-libsbml in 100% of the cases.

> One potential solution is to actually install the python-libsbml package via pip. This is the safest option, as it is what pysces expects. 
I think this will create problems and is not a solution, because symbols are overwritten with the python-libsbml package. I am pretty sure this will break things. Just try to install python-libsbml and run the tests, I would bet on segmentation faults and the python interpreter to die.

> libsbml can be compiled with many different flags and settings, and the various versions don't always get along.

Personally I don't think this is an issue as long as we package all the stable sbml extensions which are part of python-libsbml. The important thing is that the interface is identical, i.e. the API to access things which it is.

I would highly prefer just to package tesbml and the other te* packages with the original naming, than all the symbols are available via their original names.
