### ISSUE TITLE
Latest notebook deb not working on ubuntu 16.04

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#293]
I just tried to install the latest notebook version to test another issue and installed on linux
https://sourceforge.net/projects/pytellurium/files/notebook/Tellurium_1.0.2_amd64.deb/download

Now the notebook is not working any more on Linux Ubuntu
> The Tellurium Python kernel failed to start. It may be missing or non-functional. Your Tellurium installation may be corrupt.

I purged the install via
`sudo dpkg - P tellurium`
and reinstalled, but still the same issue.

**Comment by 0u812** [comment]
Andreas also ran into this. Please remove the directory `~/.config/Tellurium`, as it will still contain the old Python 3.6.1, whereas the new notebook viewer is expecting 3.6.3. [More info](https://github.com/sys-bio/tellurium/wiki/FAQ#after-installing-tellurium-notebook-a-second-time-i-get-a-message-saying-the-tellurium-python-kernel-failed-to-start-it-may-be-missing-or-non-functional-your-tellurium-installation-may-be-corrupt). I also improved the error message in the next release.

**Comment by matthiaskoenig** [comment]
Thanks. Solved.
