### ISSUE TITLE
How to install additional packages in tellurium notebook?

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#295]
How can I install additional packages with pip in the tellurium notebook version?
For instance`sympy` is not installed, also other packages missing users could want to use for analysis.

What I tried to do was to install the packages into the virtualenv which is distributed with tellurium. 
Because there is no activate script I tried the following:
```
cd /opt/Tellurium/resources/telocal/
sudo virtualenv python-3.6.3 --distribute --python=python3.6
source python-3.6.3/bin/activate
(python-3.6.3) sudo pip install sympy
```
but this is overwriting the python interpreter and does not install sympy in the virtualenv but the local environment??

So how can I install an additional package? Is it possible to ship a full virtualenv with the jupyter notebook? Currently the activate scripts are missing, so I can not really active the virtualenv and install anything in it?

Or is it possible to point the notebook executable to another local virtualenv easily? I.e. use a different kernel in the notebook version

Best M

**Comment by 0u812** [comment]
I haven't tried virtual environments for the Python that comes bundled with the notebook viewer, but I would try to make them off of the `~/.config/Tellurium/telocal/python-x.y.z` distribution, not the one in `/opt`. Theoretically, you could replace the `~/.config/Tellurium/telocal/python-x.y.z` directory with your own Python distribution and install the `tellurium` and `temagics` packages, but, of course, they are both designed to work with a specific notebook viewer version. I don't currently have a way to configure the kernel search path from the application, maybe in a future release...

**Comment by 0u812** [comment]
Also, if all you want to do is just install new packages (without a virtualenv), there's a convenience function:
```python
import tellurium as te
te.installPackage('cobra')
```
If the package needs a C compiler before it can be installed, you'll have to install it using pip on the command line.

**Comment by draeger** [comment]
I tried `pip install sympy` and afterwards also `pip3 install sympy` as superuser. Afterwards I launched Tellurium and typed `!pip list` which, among other packages, listed `sympy (1.1.1)` to be installed. However, the following commands both fail with the same error:
```
import sympy as sp
```

and
```
from sympy import *
```

>ModuleNotFoundError                       Traceback (most recent call last)
&lt;ipython-input-3-a03f9816da30> in &lt;module>()
----> 1 from sympy import *
>
>ModuleNotFoundError: No module named 'sympy'

Question: what can I do to use `sympy` within the Tellurium notebook (version 1.0.2 on macOS)?

**Comment by 0u812** [comment]
There is a convenience function for installing packages (it just delegates to pip):
```python
import tellurium as te
te.installPackage('sympy')
```
After running the above code, `import sympy` should work. I just tested in on the Mac and it worked, so please let me know if you still have problems.

For some older distutils-type packages which compile C code when you `pip install` them, you may need to quit out of the notebook viewer and run `~/Library/Application\ Support/Tellurium/telocal/python-3.6.3/bin/python3 -m pip install <package-name>`. However, `sympy` is not one of these packages, so the above convenience function should work.

**Comment by 0u812** [comment]
Also, just to clarify, this code is intended to be run in a notebook cell:
```python
import tellurium as te
te.installPackage('sympy')
```
And in the next cell:
```python
import sympy
```

**Comment by draeger** [comment]
Excellent, this worked! Maybe it would be nice to have this in the FAQ as well. Thanks a lot!

**Comment by matthiaskoenig** [comment]
Yes, this is central piece of information. We should add this prominently to the docs/FAQ.
I will add the documentation and close this afterwards.

**Comment by 0u812** [comment]
I actually had it [here](http://tellurium.readthedocs.io/en/latest/tellurium_methods.html?highlight=installPackage#installing-packages), but maybe not prominent enough.

**Comment by matthiaskoenig** [comment]
No is good, was just not rtfm

**Comment by matthiaskoenig** [comment]
No is good, was just not rtfm

**Comment by matthiaskoenig** [comment]
No is good, was just not rtfm
