### ISSUE TITLE
Notebook versioning

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#296]
Just fyi, following the discussion in #288, I'm using the same version number for both the notebook viewer and the tellurium package. Thus, the version jumped from 1.0.2->2.0.8 with the latest release.

**Comment by matthiaskoenig** [comment]
Yes please. 

The package and the tellurium-notebook version should be build from the same code commit if possible (or at least as close as possible, same for spyder versions). That will make it much easier to debug and test issues, i.e. knowing that the pip package and all GUIs have the same tellurium code if the version is identical.
