### ISSUE TITLE
ERROR_KERNEL_LAUNCH_FAILED

### ISSUE THREAD

**Issue by draeger** [sys-bio/tellurium#297]
What can be done if the error message `newKernel needs a kernelSpec` appears upon launching Tellurium notebook?

**Comment by 0u812** [comment]
This sounds like the possibly a problem with kernel, e.g. it didn't finish installing. Does the message persist, even after giving the kernel few minutes to start up? What happens when you try to execute a cell?

**Comment by draeger** [comment]
It does not execute anything. Interestingly, this happend only with a few notebooks that we originally created in Jupyter (last year) and than opened in Tellurium. My solution was to copy/paste the content cell by cell into a new Tellurium notebook and this could then be nicely evaluated.

**Comment by 0u812** [comment]
I see, the older notebooks were probably created with a Python 2 kernel. It is possible to replace the kernel with Tellurium's built-in Python 3 kernel [as shown here](http://tellurium.readthedocs.io/en/latest/walkthrough.html#problem-cannot-load-kernel).

**Comment by draeger** [comment]
Thanks! This works!
