### ISSUE TITLE
Request for IDE Walkthrough

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#300]
This isn't high priority, since the IDE isn't mentioned in the manuscript, but @kirichoi if you or someone could write a [walkthrough for the IDE for this doc page](http://tellurium.readthedocs.io/en/latest/walkthrough.html#ide-walkthrough) at some point, it would help new users. Just cover the basics, e.g. how to import models, simulate, run code, navigate the IDE. The docs are generated from [this file](https://github.com/sys-bio/tellurium/blob/develop/docs/walkthrough.rst).

Please do it in the develop branch.

**Comment by kirichoi** [comment]
Sounds good.
