### ISSUE TITLE
Very strange libCombine bug?

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#301]
I was doing some testing on my Debian 8 VM and I noticed that [extractEntryToString](https://sbmlteam.github.io/libCombine/html/class_combine_archive.html#a06187efd1e1c8270fee1eb9a19a15c1d) only works when the archive is in the cwd. Anyone else run into this? It only seems to occur on this specific version of Linux.

@matthiaskoenig, since you're running Ubuntu, I was wondering if you are able to import the attached COMBINE archive using `Import` -> `Import Combine Archive (OMEX)...` from the cell creator bar in the notebook (latest ver 2.0.8). Please let me know if it fails or not.

Attached archive (can rename to .omex or keep as-is):
[ca-export.zip](https://github.com/sys-bio/tellurium/files/1459554/ca-export.zip)

**Comment by 0u812** [comment]
The problem seems to be that you need write access to the working directory when importing a combine archive - not sure if that is because of my code or libCombine, but tellurium does create temp files when importing.

**Comment by 0u812** [comment]
The initial cwd for the kernel is `/opt/Tellurium`, which is read-only, so can't import.

**Comment by matthiaskoenig** [comment]
Hi Kyle, 
I can run the example without problems on Ubuntu 16.04 via `Import -> Import Archive`

Also executing the archive directly works
te.executeCombineArchive("/home/mkoenig/Desktop/ca-export.omex");

I don't have write access as user to `/opt/Tellurium` so not sure what is going on there.
Normally the files should be created in the system tmp directory (this is where the archives are extracted to work with them), so probably the permissions to the `tmp` directory are incorrect on the machine.
My permissions on /tmp are
```
drwxrwxrwt 19 root    root    450560 Nov 10 08:56 .
```
i.e. everybody can read, write, execute in the tmp dir. Check if this is the same on the system.
Best M

**Comment by 0u812** [comment]
Thanks for testing this in your setup. I still have the problem where the `extractEntryToString` function in libCombine only works if the user has read/write access to the cwd, as shown in the attached notebook. It would be easy enough to fix in Tellurium by simply changing the cwd to /tmp before importing an archive, then changing back again.

[libcombine-test.ipynb.zip](https://github.com/sys-bio/tellurium/files/1461565/libcombine-test.ipynb.zip)

**Comment by luciansmith** [comment]
I got this test running with normal 'libcombine', and now get:

```
********************************************************************************
Print archive: C:\Users\Lucian\Downloads\ca-export.zip
********************************************************************************
  metadata for '.':
     Created : 2017-11-09T22:42:55Z
     Modified : 2017-11-09T22:42:55Z
     # Creators: 1
       user 
Num Entries: 2
 0: location: ./experiment/Calzone2007-simulation-figure-1B.xml format: http://identifiers.org/combine.specifications/sed-ml
  no metadata for './experiment/Calzone2007-simulation-figure-1B.xml'
b'<?xml vers'
 1: location: ./model/BIOMD0000000144.xml format: http://identifiers.org/combine.specifications/sbml
  no metadata for './model/BIOMD0000000144.xml'
b'<?xml vers'
```

So I think this is resolved?  At any rate, we don't use our own 'tecombine' any more, anyway.
