### ISSUE TITLE
Show version / make version accesible in Tellurium notebook

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#302]
It would be great if the version could be displayed in the Tellurium splash on startup, i.e.
`Tellurium-v2.0.8`
and would be available via an 
`about` page in the menu.

Or is there any other easy way to find out the version of the notebook while running the notebook version?

Working on multiple machines, have to give support to multiple people in course. Would be great to have an easy way to check this in a second.

**Comment by hsauro** [comment]
I requested an about box some time ago but it hasn't been implemented.

Herbert

**Comment by kirichoi** [comment]
I think this is fixed.
