### ISSUE TITLE
Plotting with logarithmic axes

### ISSUE THREAD

**Issue by draeger** [sys-bio/tellurium#304]
The documentation says that `xscale` and `yscale` can be used to produce plots using a scale other than linear (http://tellurium.readthedocs.io/en/latest/_notebooks/core/tellurium_plotting.html?highlight=xscale). Assuming the `xscale` attribute is to be used with a `String` value, I tried `xscale="log"`, which did not work.
The example in the documentation shows instead use of the attributes `logx=True`, which also does not work. What is the correct way to produce a plot with a logarithmic axis scale (either x- or y-axis)?

**Comment by hsauro** [comment]
Not sure, I've a feeling that plotting support is as complete as in the IDE
version. Need to see what Kyle says.

Herbett

**Comment by matthiaskoenig** [comment]
xscale is only applied on the matplotlib backend, no effect on plotly
currently.

**Comment by 0u812** [comment]
@draeger sorry, there was a typo in the plotting code. I'll release a new version today that fixes this.

**Comment by draeger** [comment]
@0u812: Thanks a lot!

**Comment by draeger** [comment]
Interestingly, I found that it does not behave like this when switching the default plotting library to `matplotlib` before plotting and trying to safe:
```
import matplotlib.pyplot as plt
te.setDefaultPlottingEngine('matplotlib') # change the plotting engine
```
For some reason, afterwards the Tellurium file can be saved including results. Does the default plotting library cause the trouble?

**Comment by 0u812** [comment]
I was able to follow up with Andreas via email about this. Posting workaround here in case anyone else runs into this. Unfortunately, [a known issue with Plotly](http://tellurium.readthedocs.io/en/latest/walkthrough.html#problem-saving-the-notebook-takes-forever) causes it to take a long time to save very large plots (with a large number of traces or points). Here are some workarounds:

* Change the plotting engine to matplotlib using te.setDefaultPlottingEngine('matplotlib')

* Reduce the number of points in the simulation (10^3 seems to work)

* Clear the output before saving the notebook by selecting `Language` -> `Restart and Clear All Cells` from the menu

**Comment by 0u812** [comment]
I uploaded Tellurium 2.0.10 which fixes the log plotting. To enable log axes, please pass `logx=True` or `logy=True` to `plot`, e.g. [this example](http://tellurium.readthedocs.io/en/latest/_notebooks/core/tellurium_plotting.html) should work:

```python
import tellurium as te
te.setDefaultPlottingEngine('matplotlib')
r = te.loadTestModel('feedback.xml')
r.integrator.variable_step_size = True
s = r.simulate(0, 50)
r.plot(s, logx=True, xlim=[10E-4, 10E2],
      title="Logarithmic x-Axis with grid", ylabel="concentration");
```

I will fix the docs to change xscale/yscale to logx/logy.

**Comment by draeger** [comment]
Excellent! I tried it and it is just great, super quick, even for large simulation times. Thanks!

**Comment by 0u812** [comment]
My pleasure!
