### ISSUE TITLE
Tellurium frontend becomes unresponsive when saving files with large variables

### ISSUE THREAD

**Issue by draeger** [sys-bio/tellurium#305]
When doing complex calculations, the frontend of Tellurium often does not respond anymore and can also not be closed (using macOS). That usually happens when I do a simulation that produces variables with larger tables. Then Tellurium becomes unreactive, i.e., scrolling does no longer work, it does not save the file, and I cannot close the program anymore. In this situation, I can only kill the application entirely, hence also resetting my calculation. Is there a way to circumvent this?

**Comment by hsauro** [comment]
Might be worth checking if this happens in the IDE version to see if it's a
tellurium problem or a notebook problem.

Herbert

**Comment by 0u812** [comment]
Hi Andreas, there are several things which could cause this. If the output contains very large tables or plots with many traces then it may take a long time to save. You can clear the outputs by choosing `Language` -> `Reset and Clear All Cells`, but then the notebook will be saved without outputs. If you could send me an example notebook via email (with the outputs cleared), I could try to provide more specific advise.

**Comment by kirichoi** [comment]
If the model or output is really really large, it could cause a problem like this. From my experiences, if you wait a bit until the function executes, the program will become responsive again. This could be an issue with how Python deals with frontends in general. 
However, this could also be a bug so we should probably check it.

**Comment by draeger** [comment]
Thanks! So, my previous comment was in the wrong thread https://github.com/sys-bio/tellurium/issues/304#issuecomment-344741801. When changing the plot library, I can even save very large outputs and Tellurium is not unresponsive. However, it might then take a bit before the plot is actually drawn, but that's fine. Maybe it would make sense to notify the authors of the default plot library about the problem with the unresponsiveness?

**Comment by 0u812** [comment]
That's certainly a fair point. I have been meaning to do some testing to confirm whether the problem is with Plotly, or if this is just a consequence of trying to save large amounts of JSON data (in which case they wouldn't be able to do anything about it).
