### ISSUE TITLE
tellurium notebook `name cwd not defined` when loading COMBINE archive

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#307]
When trying to import the following COMBINE archive 
https://sed-ml.github.io/examples/L1V3/L1V3_repressilator.omex
in tellurium notebook on Ubuntu I get

```
ERROR IMPORTING ARCHIVE
`name cwd not defined`
```

**Comment by 0u812** [comment]
Thanks for catching this. Fixed in 2.0.12. You can do an in-place upgrade with `~/.config/Tellurium/telocal/python-3.6.3/bin/python3 -m pip upgrade tellurium`. No need to reinstall the entire notebook.
