### ISSUE TITLE
Got caught with the libsbml is not libsbml issue this morning

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#309]
Couldn't figure out again how to load libsbml, after some searching found a clue, Anyone else will not have any chance in getting libsbml to load. 

To avoid this can we put 

import tesbml as libsbml 

at the start when tellurium is imported? It will help a little since peopel still peopel wil stil try to import libsbml. 

This is such an annoying 'feature'!

**Comment by kirichoi** [comment]
I think we have agreed upon changing tesbml back to libsbml? If so, the changes won't be necessary and in the next release you should be able to do `import libsbml`.

**Comment by hsauro** [comment]
ok, good because it is really annoying to have to remember to use tesbml
and yesterday I even had to llook up what the name on in the docs.

Herbert
