### ISSUE TITLE
Bug in tellurium.py that's avaialble on Github

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#311]
I downloaded tellurium.py from github so I could access the new functions but when I tryied to us it I got the error message:

import tellurium as te
Traceback (most recent call last):

  File "<ipython-input-1-a1d15ad2750a>", line 1, in <module>
    import tellurium as te

  File "C:\Tellurium-Winpython\python-2.7.13.amd64\lib\site-packages\tellurium\__init__.py", line 113, in <module>
    from .tellurium import (

ImportError: cannot import name addFileToCombineArchive

**Comment by kirichoi** [comment]
Cannot reproduce. Seems like it's a issue on your local machine. You should make sure you are getting codes from the master branch. You should also make sure to replace everything under tellurium folder. Function addFileToCombineArchive was introduced only to select few branches as shown [here](https://github.com/sys-bio/tellurium/commit/5687c08afea5a17d4ff876c700842c13744e7f60).

**Comment by hsauro** [comment]
Once I added addFileToCombineArchive, it worked again.

This function is missing from the copy of telluirum.py on github.

Herbert
