### ISSUE TITLE
Error when using tellurium.py from github

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#312]
I tried to use the telluirum.py from github but there was an error when I imported tellurium, it said that the following function was missing ( I found it in my current copy of tellurium.py):

def addFileToCombineArchive(archive_path, file_name, entry_location, file_format, master, out_archive_path):
    """ Add a file to an existing COMBINE archive on disk and save the result as a new archive.

    :param archive_path: The path to the archive.
    :param file_name: The name of the file to add.
    :param entry_location: The location to store the entry in the archive.
    :param file_format: The format of the file. Can use tecombine.KnownFormats.lookupFormat for common formats.
    :param master: Whether the file should be marked master.
    :param out_archive_path: The path to the output archive.
    """
    import tecombine
    archive = tecombine.CombineArchive()
    if not archive.initializeFromArchive(archive_path):
        raise RuntimeError('Failed to initialize archive')
    archive.addFile(file_name, entry_location, file_format, master)
    archive.writeToFile(out_archive_path)

**Comment by kirichoi** [comment]
You should NOT find that function in tellurium.py. I am pretty sure you are getting your files from branches other than `master`.

**Comment by kirichoi** [comment]
[This](https://github.com/sys-bio/tellurium/blob/master/tellurium/tellurium.py) is the Tellurium file under the branch you should be using. No function called `addFileToCombineArchive` here. Any other branches there's no guarantee it will work since people might have been testing something and abandoned halfway through it.

**Comment by hsauro** [comment]
I just go tot github, find readrunner and assume that the code we use.

Herbert

**Comment by hsauro** [comment]
PS This the url I use:

https://github.com/sys-bio/tellurium

**Comment by kirichoi** [comment]
I have no idea how you are getting files from branches other than master. Could you try to get the files from [this link](https://github.com/sys-bio/tellurium/archive/master.zip)? Also, you should make sure to remove everything inside the tellurium folder (not just tellurium.py) before copying files over.

**Comment by hsauro** [comment]
I've no idea either.

H
