### ISSUE TITLE
Tellurium splash needs updating

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#32]
Spyder displays init messages in white. The splash has a white bg. It's white on white:
https://github.com/sys-bio/tellurium/blob/master/spyder_mod/img_src/Tellurium_splash.png

**Comment by 0u812** [comment]
I think we should use a dark background on the splash to avoid having to change the default Spyder font from white to black (manually tweaking Spyder for each and every release isn't a viable long-term option).

**Comment by kirichoi** [comment]
Visual-wise, white background will look the most clean. However, we can add a bar at the bottom of the splash screen where the letters appear. I vote for the same color as the tellurium logo (orange).

**Comment by luciansmith** [comment]
Another option is to simply change the font color of the text itself to
black.  Will that work for people?

-Lucian

**Comment by 0u812** [comment]
Unfortunately, changing the font color requires manually modifying the Spyder Python source, which we are trying to avoid since it has to be done for each release.
