### ISSUE TITLE
how to degrade only what's present in Antimony?

### ISSUE THREAD

**Issue by yarden** [sys-bio/tellurium#321]
Hello,

Is there a way to write a degradation reaction that is only "active" when there's something to be degraded in Antimony?

Consider this model where ``A`` leads to degradation of ``B``:

```
const deg_k = 0.01
var A = 10.0
var B = 2.0
// A degrades B
A + B -> A; deg_k * A
```

This allows values of ``B`` to become negative. I'd like to instead make it so ``B`` is only "deleted" if it's present. I tried to bake this, using events, into the rate of the degradation reaction:

```
const deg_k = 0.01
var A = 10.0
var B = 2.0
var B_present = 1.0

// indicator variable for whether B is present
at (B > 0): B_present = 1.0;
at (B <= 0): B_present = 0.0;

// A degrades B
A + B -> A; deg_k * A * B_present
```

Is there a better way to say it in Antimony?
(I know I can make the reaction proportional to abundance of B but I have other reasons not to do that). 
Thank you and happy new year!

**Comment by hsauro** [comment]
Did the event approach work?

Herbert

**Comment by yarden** [comment]
Not completely. If I start with ``B`` being non-zero, it appears to work:

```
MODEL_STR = '''
const deg_k = 0.01
var A = 2.0
var B = 1.0
var B_present = 1.0

at (B > 0.0): B_present = 1.0;
at (B <= 0.0): B_present = 0.0;

// A degrades B
A + B -> A; deg_k * A * B_present
'''

model = te.loada(MODEL_STR)
t_start = 0.0
t_end = 300.0
result = model.simulate(start=t_start, end=t_end)
var_names = model.timeCourseSelections
plt.figure()
for var in var_names:
    if var == "time": continue
    plt.plot(result["time"], result[var], label=var)
plt.axhline(y=0.0, linestyle='--')
plt.legend()
```

giving:

![test_bnonzero](https://user-images.githubusercontent.com/96318/34445428-a658986e-eca1-11e7-8cdb-150c26f76779.png)

But if B is 0.0 to begin with, it fails to trigger the event, so this:

```
MODEL_STR = '''
const deg_k = 0.01
var A = 2.0
var B = 0.0
var B_present = 1.0

at (B > 0.0): B_present = 1.0;
at (B <= 0.0): B_present = 0.0;

// A degrades B
A + B -> A; deg_k * A * B_present
'''
```

gives:

![test_bzero](https://user-images.githubusercontent.com/96318/34445478-e39b8b96-eca1-11e7-932e-66b68cb8ae01.png)

**Comment by hsauro** [comment]
This is one for Lucian I think. I'm not sure what the best way is for this.

What happens if you did this:

A + B -> A; deg_k * A * B

B is only degraded is there is B, no B and nothing happens.

Herbert

**Comment by yarden** [comment]
Thanks. Sure, what you proposed would work - that's what I was getting with making the reaction "proportional to abundance of B" in original post, but that also changes the dynamics of degradation.

**Comment by hsauro** [comment]
Ok I see, was wondering why you hadn't done that.  This is probably a
question for Lucian.  If I think of something else I'll let you know.

Herbert

**Comment by luciansmith** [comment]
The simplest way to accomplish what you want is just:

A + B -> A; deg_k * A * (B>0)


The only problem is that using a Boolean in a numeric context is only legal
in SBML L3v2.  However, it will work anyway in roadrunner/tellurium.  If
you want a valid l3v1 or l2 model, you'll have to turn this into a
'piecewise' function:

A + B -> A; deg_k * A * piecewise(1,B>0,0)


The reason the event approach didn't quite work is that events fire when
the trigger *changes* from false to true.  If if starts off 'true', it will
never fire.  Your approach could work anyway, but you have to set B_present
to its correct value to start with:

var B_present = B>0; # (or the piecewise function again: piecewise(1,B>0,0) )

at (B > 0.0): B_present = 1.0;
at (B <= 0.0): B_present = 0.0;



In this approach, B starts off correct, and gets updated appropriately by
the events when that changes.

Another way would be to declare that both triggers started off as 'false'
at t0:

var B_present = 1.0

at (B > 0.0), t0=false: B_present = 1.0;
at (B <= 0.0), t0=false: B_present = 0.0;



In this approach, the underlying SBML sets the 'initialValue' attribute on
both Trigger elements to 'false', so whichever is true at the start of the
simulation is seen to 'change' from false to true, causing the event to
fire.

That's three ways to solve the problem when you only wanted one, but
hopefully the other methods will come in handy in some other situation ;-)

-Lucian

**Comment by hsauro** [comment]
We should move this thread to the discussiun forum.

Herbert

**Comment by yarden** [comment]
Thanks Lucian! I didn't know about the elegant ``(B>0)`` syntax possibility or the piecewise option. Very helpful. I also didn't know there was a discussion forum; I'll ask on there next time. Thank you both.

**Comment by yarden** [comment]
P.S. Where is the discussion list? I could not find it via the documentation pages.

**Comment by kirichoi** [comment]
The link to the discussion forum can be found on [here](https://tellurium.readthedocs.io/en/latest/appendix.html#contact) and [here](http://tellurium.analogmachine.org/contact/).

**Comment by hsauro** [comment]
That means it's not very obvious.

Herbert

**Comment by yarden** [comment]
re docs: I suggest moving it up front because it's a wonderful resource and I wouldn't have thought to look for it under "Appendix" (or "Contact"). 

@luciansmith - thank you again for your answer. I ran into an issue with your suggestion that seems like a bug so I am following up on it here. When I use the ``piecewise`` function and simulate the model from t=0 to t=1000, I get what appears to be the right answer:

```
MODEL_STR = '''
const deg_k = 0.01
var A = 2.0
var B = 1.0

// A degrades B
A + B -> A; deg_k * A * piecewise(1,B>0,0)
'''

model = te.loada(MODEL_STR)
t_start = 0.0
t_end = 1000.0
result = model.simulate(start=t_start, end=t_end)
var_names = model.timeCourseSelections
print var_names
print "model: "
print model
plt.figure()
for var in var_names:
    if var == "time": continue
    plt.plot(result["time"], result[var], label=var)
plt.axhline(y=0.0, linestyle='--')
plt.legend()
```

It yields:

![image](https://user-images.githubusercontent.com/96318/34679263-725fd378-f463-11e7-9d56-74dd0280cae9.png)

which is correct. However, it seems unstable; if I simulate the results instead from t=0 to t=300, I get negative values for ``B``:

```
model = te.loada(MODEL_STR)
t_start = 0.0
t_end = 300.0
result = model.simulate(start=t_start, end=t_end)
...[same as above]...
```

gives:

![image](https://user-images.githubusercontent.com/96318/34679373-bce90a9a-f463-11e7-8561-96043ab494cd.png)

If I use the ``(B > 0)`` or ``piecewise`` solution in other, more complex models, it also yields errors such as:

```
RuntimeError: CVODE Error: CV_TOO_MUCH_WORK: The solver took mxstep (20000) internal steps but could not reach tout.; In virtual double rr::CVODEIntegrator::integrate(double, double)
```

Those models are much bigger; the simplest example of "wrong" behavior I have for now is what's above. I'm using ``tellurium '1.3.4'`` on Mac OS X. Roadrunner info:

```
$ python -c "import roadrunner; print roadrunner.__version__"
1.4.8; Compiler: clang "6.0 (clang-600.0.56)", C++ version: 199711; JIT Compiler: LLVM-3.5; Date: Aug  9 2016, 12:34:56; LibSBML Version: 5.13.0
```

**Comment by luciansmith** [comment]
This looks like the underlying simulator is having problems seeing the breakpoint when B goes negative--even to the point of continuing to degrade B even when it's already less than zero, which is really weird!

I personally am more on the model design end than the simulator end, so I'm going to have to bounce the question back to someone who knows the roadrunner code--Herbert?  Someone else?  I remember Andy talking about getting roadrunner to accept Booleans, but I don't know if he did any stress testing for models such as this one.

At any rate, it looks like a straight-up bug in the simulator to me, though sharp edges like this might give it trouble.

If you try one of the event-based approaches, do those work more robustly?  IIRC, the event handling code is separate from some of the other parts, which might be to our advantage in this case.

**Comment by hsauro** [comment]
I just tried the simulation from 0 to 1000 and 0 to 300 and I get the same
result, B is clipped to zero. I don't get a negative B.

See image:

https://i.imgur.com/VcjD4Ay.png

Can you call this:

print te.getVersionInfo()

For me it yields:

[('tellurium', '2.0.12'), ('roadrunner', '1.4.24'), ('antimony', '2.9.4'),
('libsbml', '5.15.0'), ('libsedml', '402'), ('phrasedml', '1.0.8'),
('pySBOL', '2.2.0')]

Herbert

**Comment by 0u812** [comment]
@yarden I also get the same result as Herbert. Installing either the latest [notebook or pip version of Tellurium for Mac](http://tellurium.readthedocs.io/en/latest/installation.html) will probably fix your issue with negative quantities.

**Comment by kirichoi** [comment]
`tellurium '1.3.4'` is a very outdated version as of now. As Kyle suggested, using the most recent notebook version or updating packages through pip will likely solve the issue.

**Comment by yarden** [comment]
Printing the version as Herbert suggested gives this:

```
$ python -c "import tellurium as te; print te.getVersionInfo()"
Warning: No module named sbml2matlab
Warning: No module named pygraphviz
/Users/yarden/anaconda/lib/python2.7/site-packages/tellurium/notebooks/__init__.py:16: UserWarning: Notebook tools are not imported, due to missing dependencies.
  warnings.warn("Notebook tools are not imported, due to missing dependencies.")
[('tellurium', '1.3.4'), ('roadrunner', '1.4.8; Compiler: clang "6.0 (clang-600.0.56)", C++ version: 199711; JIT Compiler: LLVM-3.5; Date: Aug  9 2016, 12:34:56; LibSBML Version: 5.13.0'), ('antimony', 'v2.8.0'), ('snbw_viewer', 'No information for sbnw viewer'), ('libsbml', '5.13.0'), ('libsedml', '401'), ('phrasedml', 'v1.0.3')]
```

I will try upgrading tellurium.

**Comment by kirichoi** [comment]
Just to let everyone know, I have updated the README file as well as our website so that people can find the google group page more easily.
