### ISSUE TITLE
Can't plot phase plots anymore!

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#329]
Looks like I can no longer do phase plots with the current version.  The following example comes from my blog Nov 16, 2016, something has happenned since to change the behavior.  This is an important bug that needs fixing for the next release. 

I assume the alternative in the mean time is to use the slicing syntax which will really throw my students:

plt.plot (m[:,0], m[:,1])

I noted that te.plotArray (m) still works but te.plotWithLegend() doesn't. I'll use te.plotArray (m) for now with the students. Wish plotWithLegend() still worked.

I noticed that if I remove (line 66/67) from engine.py:

        #if m.colnames[0] != 'time':
        #    raise RuntimeError('Cannot plot timecourse - first column is not time')

it works again. Any side effects before of this?

Currently running:

[('tellurium', '2.0.12'),
 ('roadrunner', '1.4.24'),
 ('antimony', '2.9.4'),
 ('libsbml', '5.15.0'),
 ('libsedml', '402'),
 ('phrasedml', '1.0.8'),
 ('pySBOL', '2.2.0')]

import tellurium as te
r = te.loada ('''
  v1: $Xo -> S1; k1*Xo;
  v2:  S1 -> S2; k2*S1*S2^h/(10 + S2^h) + k3*S1;
  v3:  S2 -> $w; k4*S2;      

  # Initialize
  h  = 2; # Hill coefficient
  k1 = 1; k2 = 2; Xo = 1;
  k3 = 0.02; k4 = 1;
  S1 = 6; S2 = 2
''')

m = r.simulate (0, 80, 500, ['S1', 'S2'])
r.plot()

Gives the error:

RuntimeError: Cannot plot timecourse - first column is not time

**Comment by kirichoi** [comment]
You can see why that snippet of code is there but it does feel like the restriction is too strict. I will change it to warnings asking the user to double check the selection unless it was intentional.
Also, `te.plotWithLegend() ` should still work. Could you check what kind of error it returns?

**Comment by hsauro** [comment]
Do we need a warning if someone wants to plot a phase plot?

plotWithLegend generates the folllowing error:

    return r.plot(result=result, loc=loc, show=show, **kwargs)

AttributeError: 'NamedArray' object has no attribute 'plot'

**Comment by kirichoi** [comment]
Fixed by commit c0d7e2e2b232f68444c79822b75deae676bb55ef
