### ISSUE TITLE
Add testing suite

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/tellurium#33]
Add testing suite for tellurium integrating other testing suites.

**Comment by matthiaskoenig** [comment]
A test suite was added.
The test suite runs the roadrunner tests as a subset (one unit test).
Tests can be run via
```{python}
import tellurium.tests.test_runner as tetest
runner = tetest.TestRunner()
runner.te_passes_tests()
```

**Comment by kirichoi** [comment]
Refer #73

**Comment by matthiaskoenig** [comment]
There is a comprehensive test suite (currently with coverage of 78% of code base).
