### ISSUE TITLE
Fix plotWithLegend

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/tellurium#330]
Even though the function is deprecated, it should still work.

**Comment by kirichoi** [comment]
This is none-issue. `te.plotWithLegend()` still works. 
Run by:
`te.plotWithLegend(rrInstance)` or `te.plotWithLegend(result=NamedArray)`
not `te.plotWithLegend(NamedArray)`

**Comment by hsauro** [comment]
My mistake.

H
