### ISSUE TITLE
issue with events and conserved moiety analysis

### ISSUE THREAD

**Issue by yarden** [sys-bio/tellurium#338]
Hello,

When trying to run this [example] (http://tellurium.readthedocs.io/en/latest/notebooks.html?highlight=events#add-plot-elements) from the docs:

```
r = te.loada ('''
   $Xo -> S1; k1*Xo;
   S1 -> $X1; k2*S1;

   k1 = 0.2; k2 = 0.4; Xo = 1; S1 = 0.5;
   at (time > 20): S1 = S1 + 0.35
''')

# Simulate the first part up to 20 time units
m = r.simulate (0, 50, 100, ["time", "S1"])
```

I got the error:

```
RuntimeError: Cannot perform moeity conversion when floating species have events. The floating species, S1 has event _E0.
 To disable conserved moeity conversion, either 
	 a: set [Your roadrunner variable].conservedMoietyAnalysis = False, 
	 before calling the load('myfile.xml') method, or
	 b: create a LoadSBMLOptions object, set the conservedMoieties property 
	 to False and use this as the second argument to the RoadRunner 
	 constructor or load() method, i.e. 
	 o = roadrunner.LoadSBMLOptions()
	 o.conservedMoieties = False
	 r = roadrunner.RoadRunner('myfile.xml', o)
```

Since I'm loading an Antimony program, and not an XML file, I don't know how to turn off conserved moiety analysis. To do what the error suggests in option (a) would require the model to be loaded, but the error occurs in the call to ``te.loada``. Option (b) seems also not to apply to loading of Antimony code. Is there a way around this? Thanks!

**Comment by hsauro** [comment]
This is odd, you must have the conserved moiety option on somehow. By
default it's off. Try setting the option to false.

r.conservedMoieties = False

When I'm at my desktop computer I'll try the model aswell, but this model
should compile without this error message. I use these kinds of small
examples all the time in class.

Herbert

**Comment by hsauro** [comment]
Yarde, could you call the following:

roadrunner.Config.getValue
(roadrunner.Config.LOADSBMLOPTIONS_CONSERVED_MOIETIES)

and tell me whether it is true or false?

If its true then call

roadrunner.Config.setValue
(roadrunner.Config.LOADSBMLOPTIONS_CONSERVED_MOIETIES, True)

My only explanation is that your config option was changed somehow.
Hopefully this should set it back to false

Herbert

**Comment by yarden** [comment]
Thanks, Herbert, you were right; I had an importing module that set ``roadrunner.Config.LOADSBMLOPTIONS_CONSERVED_MOIETIES`` to True. I didn't think it would matter because the name of the flag made it seem like it only applies to SBML models, whereas I was loading a model written directly in Antimony.

**Comment by hsauro** [comment]
True, the config name does suggest that. But remember that antimony is
first converted to sbml then loaded into roadrunner.

Herbert

**Comment by luciansmith** [comment]
If it wasn't clear elsewhere: under the hood, Antimony models are converted to SBML, and those SBML models are then sent to roadrunner.  Everything is SBML in the end ;-)

**Comment by yarden** [comment]
I really like that everything is SBML under the hood to prevent discrepancies between SBML and Antimony syntax. I didn't realize that. Thanks for clarifying.
