### ISSUE TITLE
triggering events at t = 0

### ISSUE THREAD

**Issue by yarden** [sys-bio/tellurium#339]
Hello,

I noticed a quirk with event handling that seems like a bug (but might be the intended behavior). Consider this model:

```
M = '''
A -> ; 0.01 * A
at (time >= 0): A = 50.0
'''
model = te.loada(M)

t_start = 0.0
t_end = 200.0
model.integrator = 'gillespie'
model.integrator.seed = 123
rr_results = model.simulate(t_start, t_end)
```

It does not simulate the degradation of ``A``. There's no initial value provided to ``A``, so it defaults to ``0.0`` and the event is not triggered in spite of ``time >= 0``. I thought this was specific to Gillespie (which can make sense under some implementations) but it's true for deterministic simulation too. If I set an initial value for A (``A = 50.0``), then it of course works, but it seems like ``t >= 0`` should be handled as a special case.

**Comment by luciansmith** [comment]
This is actually the correct behavior.  An event only fires when its trigger changes from false to true: if it starts off true and never becomes false, it will never fire.

You can change the initial state of the trigger in Antimony by using the syntax 't0=false':

    M = '''
    A -> ; 0.01 * A
    at (time >= 0), t0=false: A = 50.0
    '''

(In SBML, this becomes an 'initialValue="false"' flag on the trigger.)

**Comment by yarden** [comment]
Right, I forgot about this default behavior, thank you.
