### ISSUE TITLE
Tellurium doc not working

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/tellurium#34]
Sourceforge is having issue with their website and Tellurium documents are not working at all currently:
http://svn.code.sf.net/p/libroadrunnerdocs/code/tellurium/html/index.html
Time to move to github.

**Comment by luciansmith** [comment]
Well, sourceforge had a recent big failure, so this is related to that.
Things have been coming back up slowly over the course of the week; looks
like code repositories are the next on the list.  Sourceforge still has the
download tracking that github doesn't, plus the fact that it doesn't rely
on git, which is another major bonus.

**Comment by kirichoi** [comment]
What I am suggesting is moving the documentation only. We can move documentation to tellurium github repo and change to link in tellurium website.

**Comment by luciansmith** [comment]
Right, but we can't do that until sourceforge is back up, and once
sourceforge is back up, we won't have the problem any more ;-)

It would be worth moving if we thought that sf was likely to have more
outages of this sort in the future, but I don't (yet) believe that this
will be the case.
