### ISSUE TITLE
Discovered a file setuptools.pth that contains path to folder on Kiri's machine

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#341]
I was looking at setuptools.pth in site-packages and found the contents to be:

c:\users\kiri choi\projects\tellurium-winpython-installer\tellurium-winpython-2.7.13.0-win64-2.0.3p\python-2.7.13.amd64\lib\site-packages

Is this correct?

**Comment by kirichoi** [comment]
My bad. This is fixed.
