### ISSUE TITLE
Consider using Sublime Text 3 as IDE (with miniconda3)

### ISSUE THREAD

**Issue by eugenio** [sys-bio/tellurium#345]
As an enhancement would you consider supporting Sublime Text 3 as an IDE? It already has support for conda enviroments and matplot plotting library trough packages...

**Comment by matthiaskoenig** [comment]
You basically can use any IDE you want to develop tellurium code based on the available pip package.
I am basically using pycharm to develop tellurium, you could do the same with Sublime Text 3 right now. Just create a python virtualenv and install the pip package in it via
```
pip install tellurium
```
This should also work for the miniconda environment.

**Comment by eugenio** [comment]
@matthiaskoenig  yes I did that but, unfortunately, I haven't been able to visualize any plot. Thus, I thought some support is missing...
```
import tellurium as te
te.setDefaultPlottingEngine('matplotlib')

model = """
model test
    compartment C1;
    C1 = 1.0;
    species S1, S2;

    S1 = 10.0;
    S2 = 0.0;
    S1 in C1; S2 in C1;
    J1: S1 -> S2; k1*S1;

    k1 = 1.0;
end
"""
# load models
r = te.loada(model)

# simulate from 0 to 50 with 100 steps
r.simulate(0, 50, 100)
# plot the simulation
r.plot()
```

This is the script  I'm trying to plot from. I tried running the code from sublime and from a terminal within the conda environment with no plot being generated whatsoever.

**Comment by kirichoi** [comment]
Could you try a workaround using something like:

```
import tellurium as te
import matplotlib.pyplot as plt

model = """
model test
    compartment C1;
    C1 = 1.0;
    species S1, S2;

    S1 = 10.0;
    S2 = 0.0;
    S1 in C1; S2 in C1;
    J1: S1 -> S2; k1*S1;

    k1 = 1.0;
end
"""
# load models
r = te.loada(model)

# simulate from 0 to 50 with 100 steps
result = r.simulate(0, 50, 100)
# plot the simulation
plt.plot(result[:,0], result[:,1:])
plt.show()
```

**Comment by eugenio** [comment]
@kirichoi  thanks for the suggestion, I tried that but it didn't work...

I was able to verify that the matplotlib installation works via interactive session of python:
the following code gives the expected plot
```
import matplotlib.pyplot as plt
plt.plot([1,2,3,4])
plt.ylabel('some numbers')
plt.show()
```
![test](https://user-images.githubusercontent.com/292452/37569852-6627f0a2-2ae8-11e8-8d2d-dcc849b3b155.png)

**Comment by kirichoi** [comment]
Two things:
1) Could you verify which version of Tellurium you are using? i.e. `te.__version__`
2) Could you plot 2D arrays using plt.plot? Something like 
```
plt.plot([[1,2,3,4],[5,6,7,8]])
plt.show()
```
should work.

**Comment by eugenio** [comment]
1. gives :

```
>>> import tellurium as te
>>> te.version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tellurium' has no attribute 'version'
>>> 
```
2. give successfull plot of 4 lines

**Comment by kirichoi** [comment]
My bad, it should be `te.__version__`
Anyway, this is odd because the function you are using to plot is identical. Even if it is an issue with the simulator, I think `plt.plot()` should return with at least an empty plot.

**Comment by eugenio** [comment]
@kirichoi  no problem, here's the output of the last command:

```
>>> import tellurium as te
>>> te.__version__
'2.0.14'
>>> 
```

**Comment by kirichoi** [comment]
Could you double check that there are some values in `result` object? Something like `print(result)` should do.

**Comment by kirichoi** [comment]
Well, then I am lost. This might be a problem with matplotlib in sublime environment. Could you check that something like `plt.plot(result[:,1])` or `plt.plot(result[:,1:])` works?

**Comment by eugenio** [comment]
Umh, I don't think it's a problem of sublime text environment directly as it's just a wrapper around a miniconda environment. Is there any special tricks to use tellurium in a conda environment?

**Comment by kirichoi** [comment]
The problem is that you are seeing different results when you are trying to run something like `plt.plot(result[:,0], result[:,1:])` and `plt.plot([[1,2,3,4],[5,6,7,8]])`. These two calls are practically identical. One is taking a numpy array and other a Python list. One possibility might be something to do with the default backend in sublime but I do not own sublime text so I can't test much :/

**Comment by kirichoi** [comment]
Maybe you should force certain backend by placing
```
import matplotlib
matplotlib.use('TkAgg')
```
before importing Tellurium or any other packages.

**Comment by kirichoi** [comment]
Also, if you could look for some error messages, that would be great. It seems like sublime text is not capturing output from Python properly.

**Comment by eugenio** [comment]
@kirichoi  I was able to get the graph plotted with the following code:
```
import matplotlib
matplotlib.use('TkAgg')

import matplotlib.pyplot as plt
import tellurium as te

model = """
model test
    compartment C1;
    C1 = 1.0;
    species S1, S2;

    S1 = 10.0;
    S2 = 0.0;
    S1 in C1; S2 in C1;
    J1: S1 -> S2; k1*S1;

    k1 = 1.0;
end
"""
# load models
r = te.loada(model)

# simulate from 0 to 50 with 100 steps
result = r.simulate(0, 50, 100)

r.plot()
```
but it trows some errors:

```
/home/*****/miniconda3/envs/tellurium/lib/python3.6/site-packages/tellurium/tellurium.py:46: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'TkAgg' by the following code:
  File "/home/*******/**********************/synthetic biology/generic-bioelectrochemical-capable-strain/prova.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/home/*******/miniconda3/envs/tellurium/lib/python3.6/site-packages/matplotlib/pyplot.py", line 71, in <module>
    from matplotlib.backends import pylab_setup
  File "/home/******/miniconda3/envs/tellurium/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 16, in <module>
    line for line in traceback.format_stack()


  matplotlib.use('Agg')
```

**Comment by kirichoi** [comment]
Aha, so the issue was basically sublime text not supporting certain matplotlib backends. Glad to hear you got plotting working at least. We will try to add some codes to circumvent this issue.

@0u812:  [This line](https://github.com/sys-bio/tellurium/blob/master/tellurium/tellurium.py#L39) sets Agg as the default backend. Do you think it is possible to change it to TkAgg whichout causing issue on Tellurium notebook?

**Comment by eugenio** [comment]
@kirichoi great!

**Comment by kirichoi** [comment]
Commit c5172b16447d494f6ba51d3c091198ea6894ef62 should have fixed this issue.
