### ISSUE TITLE
This script no longer works

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#346]
I obtained this script from my modeling textbook but when I tried to run it I got an error. I tried to fix the error but then got more error messages:

    return method(self, value)
TypeError: in method 'SimulateOptions_start_set', argument 2 of type 'double'

Running:

[('tellurium', '2.0.12'),
 ('roadrunner', '1.4.24'),
 ('antimony', '2.9.4'),
 ('libsbml', '5.15.0'),
 ('libsedml', '402'),
 ('phrasedml', '1.0.8'),
 ('pySBOL', '2.2.0')]

import tellurium as te
import matplotlib.pyplot as plt

import roadrunner
roadrunner.Config.setValue(roadrunner.Config.SIMULATEOPTIONS_INTEGRATOR, "GILLESPIE")

newModel = '''
    A -> B;  k1*A;
    B -> A;  k2*B;
    k1 = 0.2; k2 = 0.4;
'''

starting = 6000 # 10 zepto molar 10^(-21) = 6000 molecules
r = te.loadAntimonyModel(newModel)
r.model["init(A)"] = starting
r.model["init(B)"] = 0
m1 = r.gillespie(rr, 0, 12, ["time", "A", "B"])

**Comment by kirichoi** [comment]
I think the script itself is broken. From [RoadRunner doc](https://sys-bio.github.io/roadrunner/python_docs/api_reference.html?highlight=gillespie#RoadRunner.RoadRunner.gillespie), the correct notation is `r.gillespie(start, end, step, seletions)` which is identical to `simulate()`.

**Comment by kirichoi** [comment]
Gillespie does not support `start, end, selection` which was restored in `simulate()` and if you want it back, please file a new issue.

**Comment by hsauro** [comment]
What's the proper way to run a Gillespie simulation? I used the above a lot
in the textbook. I need to update many of the scripts since a lot has
changed in the API since the book was published and quite a few of the
published scripts no longer work.

Herbert

**Comment by kirichoi** [comment]
`r.gillespie(start, end, step, selections)` is the proper way now. It is consistent with `simulate()` which is the way it should be.
