### ISSUE TITLE
This script not longer works

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#347]
The following script which I obtained from my modeling textbook no longer works. The issue appears to be with te.plotWithLegend (rr, result)

The error message is:

  line 66, in figureFromTimecourse
    if m.colnames[0] != 'time':
AttributeError: 'numpy.ndarray' object has no attribute 'colnames'

Running:

[('tellurium', '2.0.12'),
 ('roadrunner', '1.4.24'),
 ('antimony', '2.9.4'),
 ('libsbml', '5.15.0'),
 ('libsedml', '402'),
 ('phrasedml', '1.0.8'),
 ('pySBOL', '2.2.0')]

import tellurium as te
import numpy as np

# Coherent Type I Genetic Network, noise filter
cell = '''
    $G2 -> P2; Vmax2*P1^4/(Km1 + P1^4);
    P2 -> $w;  k1*P2;
    $G3 -> P3; Vmax3*P1^4*P2^4/(Km1 + P1^4*P2^4);
    P3 -> $w;  k1*P3;

    Vmax2 = 1; Vmax3 = 1;
    Km1 = 0.5; k1 = 0.1;
    P1 = 0;    P2 = 0;    P3 = 0;
'''
rr = te.loadAntimonyModel(cell)
rr.getSteadyStateValues()
print rr.model.getFloatingSpeciesConcentrations()

# Pulse width
# Set to 1 for no effect
# Set to 4 for full effect
width = 1
rr.P1 = 0.3
m1 = rr.simulate(0, 10, 100, ["time", "P1", "P3"])
rr.P1 = 0.7 # input stimulus
m2 = rr.simulate(10, 10 + width, 100, ["time", "P1", "P3"])
rr.P1 = 0.3
m3 = rr.simulate(10 + width, 40, 100, ["time", "P1", "P3"])
m = np.vstack((m1, m2))
result = np.vstack((m, m3))
te.plotWithLegend(rr, result)

**Comment by kirichoi** [comment]
Basically, when `vstack` is called, the colnames are striped off. colnames are used to check that the array you pass through is actually formatted correctly. I don't think we should remove this check btw, the original script is already problematic because it does not have any information on time and its scale passed to plot.

**Comment by hsauro** [comment]
What's the best way to splice two simulations together and plot them with a legend? I used the above approach a lot but if it doesn't work anymore I need another way to do.

**Comment by kirichoi** [comment]
vstack or concatenate will work fine for splicing. For plotting, something like:
```
plt.plot(result[:,0], result[:,1:])
plt.legend(["P1","P3"])
plt.show()
```
will do. In this case, notice that you are manually specifying x value and y values.

**Comment by hsauro** [comment]
I'd like a simpler way for novice users, slicing is a bit scary for many
biologists.

H

**Comment by kirichoi** [comment]
If one does not wish to use events, I don't think there are good alternatives. TBH, array manipulation is the basic of numpy basics, so it might be something they have to go through unfortunately.

**Comment by hsauro** [comment]
The other thing I noticed is that plotWithLegend is deprecated anyway,
along with plotArray.

Hence what I will do is addplotWithLegend (without the restriction) as part
of my own personal set of utilities (along with the others I've created)
which people can choose to download if need be. That way I can also
continue to use these methods in my textbook.

Herbert
