### ISSUE TITLE
New install defaults to Internal Console tab

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#35]
A new install defaults to Internal Console tab instead of IPython. This means that when a script is run, there are lots of errors. Default tab should be IPython console. I am sure this confuses a lot of people. Must be fixed in next release if not sooner.

**Comment by kirichoi** [comment]
This is most certainly an issue with updated Spyder causing problem with older settings. It should not cause problems on new users but I will look into solving it in the next release.

**Comment by hsauro** [comment]
I can try installing it on a clean machine to see how it goes.

H

**Comment by kirichoi** [comment]
Not reproducible in Tellurium 1.2.3
