### ISSUE TITLE
getODEsFromModel throws NameError

### ISSUE THREAD

**Issue by willigott** [sys-bio/tellurium#360]
How to reproduce the issue

```
import tellurium as te

r = te.loada('''
  model pathway()
    S1 + S2 -> 2 S3; k1*S1*S2
    3 S3 -> 4 S4 + 6 S5; k2*S3^3
    k1 = 0.1;k2 = 0.1;
  end
''')

te.getODEsFromModel(r)
```

This will result in 

> NameError                                 Traceback (most recent call last)
> <ipython-input-4-4363372ef040> in <module>()
> ----> 1 te.getODEsFromModel(r)
> 
> /path/to/anaconda2/lib/python2.7/site-packages/tellurium/utils/misc.pyc in getODEsFromModel(sbmlModel)
>     114     from roadrunner import RoadRunner
>     115     if type (sbmlModel) == RoadRunner:
> --> 116        extractor = ODEExtractor (sbmlModel.getSBML())
>     117     else:
>     118        raise RuntimeError('The argument to getODEsFromModelAsString should be a roadrunner variable')
> 
> /path/to/anaconda2/lib/python2.7/site-packages/tellurium/utils/misc.pyc in __init__(self, sbmlStr)
>     175     def __init__(self, sbmlStr):
>     176 
> --> 177         self.doc = libsbml.readSBMLFromString (sbmlStr)
>     178         self.model = self.doc.getModel()
>     179 
> NameError: global name 'libsbml' is not defined

All one has to do is to add 

`import libsbml`

in `misc.py`

and then it works as expected:

```
print(te.getODEsFromModel(r))

v_J0 = k1*S1*S2
v_J1 = k2*pow(S3,3)

dS1/dt = -v_J0
dS2/dt = -v_J0
dS3/dt = 2.0*v_J0 - 3.0*v_J1
dS4/dt = 4.0*v_J1
dS5/dt = 6.0*v_J1
```

**Comment by kirichoi** [comment]
This issue is fixed by commit 0d98f138e756c9a467714a3127f44b1e7030a561

**Comment by willigott** [comment]
Thanks for the quick fix! 

Any reason why you do not import `libsbml` directly but `tesbml`? I just found #309 and there you write that you agreed on using `libsbml` rather than `tesbml`.

If I want to manipulate model components as rate laws, annotation etc, should I then always use `tesbml` or can I also do it via `libsbml`?

**Comment by kirichoi** [comment]
We have decided to distribute our own version of libsbml due to the fact that the official version might be compiled without few flags we would liked to use, I believe. Therefore, we suggest users to use tesbml instead of libsbml. I think this have caused a bit of headache, and we still have not 100% decided on how to manage this.
