### ISSUE TITLE
Where do I get documenation on simpleSBML?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#361]
On tellurium.analogmachine.org I couldn't find documentation on simpleSBML. Instead, I used the Wayback machine to get the docs from 2016.

Since simpleSBML is mentioned in the paper, can these docs be reinstated? All one needs is a link in the tellurium docs to the python sphinx docs at

http://sys-bio.github.io:80/simplesbml/

The latexexport docs are also missing but I need to check how functional latex export is first.

**Comment by kirichoi** [comment]
Fixed by commit https://github.com/sys-bio/tellurium/commit/0b3f0f85d1805a85ff1ca6d1529e7f640e50395f.
