### ISSUE TITLE
Not a bug but deprecate warning message 

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#376]
'plotWithLegend' is deprecated. Use 'r.plot' instead. Will be removed in tellurium v1.4

When I run this code I get the above deprecate message, even though I am running 2.018, warning should be removed. 

import tellurium as te
# Simulation of a simple closed system
rr = te.loada ('''
    A -> B; k1 * A;
    B -> A; k2 * B;
    A = 10; B = 0;
    k1 = 1; k2 = 0.5;
''')
result = rr.simulate(0, 6, 100)
te.plotWithLegend(rr, result)

**Comment by kirichoi** [comment]
Fixed with commit https://github.com/sys-bio/tellurium/commit/9cfc897af1d9ef682b59eafd3d429ded6dfed61a
