### ISSUE TITLE
ParameterScan does not work

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#384]
The following code shown in the docs crashes:

https://tellurium.readthedocs.io/en/latest/paramscan.html?highlight=legend#loading-a-model

import tellurium as te
from tellurium import ParameterScan as ps

cell = '''
    $Xo -> S1; vo;
    S1 -> S2; k1*S1 - k2*S2;
    S2 -> $X1; k3*S2;

    vo = 1
    k1 = 2; k2 = 0; k3 = 3;
'''
rr = te.loadAntimonyModel(cell)
p = ps.ParameterScan(rr)

p.startTime = 0
p.endTime = 20
p.numberOfPoints = 50
p.width = 2
p.xlabel = 'Time'
p.ylabel = 'Concentration'
p.title = 'Cell'

p.plotArray()

Error:

p = ps.ParameterScan(rr)

AttributeError: type object 'ParameterScan' has no attribute 'ParameterScan'

**Comment by kirichoi** [comment]
Fixed in latest doc
