### ISSUE TITLE
Make sure error messages from libRoadrunner go to ipython console

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#39]
THIS IS THE SAME BUG AS #38

Currently warning messages from libRoadrunner currently go to the go to legacy console window. They should be directed to the ipython console. Try this:

import tellurium as te

r = te.loada ('''
J1: $X0 -> S1; k1_X0;
J2: S1 -> $X1; k2_S1;
X0 = 1.0; S1 = 0.0; X1 = 0.0;
k1 = 0.4
''')

m = r.simulate (0, 4, 100, ["Time", "S1"])

There will be warning that k2 hasn't been initialized but this is hidden on the ordinary console window, it should show up in the ipython window.

**Comment by kirichoi** [comment]
This is an issue on IPython side. Refer to: https://github.com/ipython/ipython/issues/1230
FYI, Spyder uses IPython Qt Console as the default console. The issue is with the current implementation using zmq redirection.
