### ISSUE TITLE
Missing png image in docs

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#392]
There is a missing image at the following page:

_notebooks/core/_notebooks/core/tellurium_stochastic_files/tellurium_stochastic_6_0.png

https://tellurium.readthedocs.io/en/latest/_notebooks/core/tellurium_stochastic.html?highlight=gillespie

**Comment by kirichoi** [comment]
Any docs under `_notebooks` should be ignored. I would like to hide it from search but I don't think that's possible. All the relevant docs are incorporated under [Usage examples](https://tellurium.readthedocs.io/en/latest/notebooks.html) by commit 5ed2ead8db14c3629bfe1bcea7810cec54db882b. Still needs to be merged into `master` though.
