### ISSUE TITLE
Update Gillesipie call docs to:

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#396]
Update the current example found in the gillespie method to (surrounding docs remain unchanged):

  # Simulate from time zero to 40 time units using a variable size (classic Gillespie)
  result = rr.gillespie (0, 40)
  #  
  # Simulate on a grid with 10 points from start 0 to end time 40
  rr.reset()
  result = rr.gillespie (0, 40, 10)  
  #
  # Simulate from time zero to 40 time units using a variable step size
  # and a selection list. This means that the first column will be time 
  # and the second column species S1
  rr.reset()
  result = rr.gillespie (0, 40, selections=['time', 'S1'])  
  #
  # Simulate on a grid from time zero to 40 time units with 20 points
  # using the give selection list
  rr.reset()
  result = rr.gillespie (0, 40, 20, ['time', 'S1'])

**Comment by kirichoi** [comment]
Fixed via commit e598cde81adfd5ec40fb951e262c4ef43309d46a
