### ISSUE TITLE
r.model.getStateVectorRate() returning wrong vector

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#403]
r.model.getStateVectorRate() is returning the wrong vector which means that dv() is also returning the wrong vector since it depends on.getStateVectorRate.  getStateVectorRate() should also have been called getStateVectorRateOfChange since that's what it returns, it doesn't return the reasction rates.  

Consider the following code, dv() should return three values but it is only returning two values (E and P). It should return all three, E, P, and ES. 

import tellurium as te
r = te.loada("""
        
        J1: E + $S  -> ES ; kf*E*S
        J2: ES -> E + $S ; kr*ES
        J3: ES -> E + P ; r*ES
        kf = 1.0 ;
        kr = 1.0 ;
        r = 1.0 ;
        E = 1.0 ;
        S = 10.0 ;
        P = 0.0 ;
""")
r.conservedMoietyAnalysis = True
print r.steadyState()
print r.dv()
print r.model.getStateVectorRate()
print r.getFloatingSpeciesIds()

**Comment by hsauro** [comment]
One other thing about this model is that P is not fixed but it still finds the steady state!

**Comment by kirichoi** [comment]
I have pushed a fix for the issue with steady state few days ago but I will take another look. Also, I have moved the issue to [roadrunner](https://github.com/sys-bio/roadrunner/issues/498).
