### ISSUE TITLE
Don't import everything in tellurium.py

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#41]
Sometimes, one of the binary modules will crash the entire system, and there's no trail to pick up, no graceful exit. `tellurium.py` now imports pretty much everything (roadrunner, antimony, etc.) and it makes isolating the problem difficult. @kirichoi, is there a rationale for this and is it possible to not do it?

**Comment by kirichoi** [comment]
This is mostly a convenience feature. Tellurium uses modified scientific_startup.py script located under spyderlib. The settings file for Spyder is also modified to point to this file.

**Comment by hsauro** [comment]
What might be useful is to have a command line argument that allows someone
to limit the imports for debugging purposes.

H

**Comment by 0u812** [comment]
I don't think it makes sense to make a stripped down version of tellurium.py after all, since the script is mostly a set of convenience functions which call into respective libraries. Regarding the error, Kiri mentioned that the combine plugin imports tellurium, which in turn imports roadrunner and antimony, both binary packages, and that might be what triggers the error on some Macs. Closing this for now since I don't think it's germane. I sent Zachary stripped down versions of Tellurium earlier, he needs to respond before we can move forward.
