### ISSUE TITLE
plotarray comment is in the plot function, should be moved to plotarray

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#414]
I noticed that the plot function described in 'Plotting' also has a sentence at the end of the section on plotarray. This sentence should be moved to the plotarray function.

I don't know who wrote this part of the plotting docs, Kyle?

**Comment by kirichoi** [comment]
Fix by editing https://github.com/sys-bio/tellurium/blob/develop/docs/tellurium_methods.rst
