### ISSUE TITLE
In the start menu I can't distinguish between 3.6 and 2.7 versions of Telluirum

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#421]
In the start menu I can't distinguish between 3.6 and 2.7 versions of Tellurium. See image, is the circled tellurium 2.7 or 3.6? Can't tell without right click and select properties.  Add 2.7 or 3.6 to the name.

![image](https://user-images.githubusercontent.com/1054990/48106513-8421ac00-e1f0-11e8-8cd1-0b98ec5080ad.png)

**Comment by kirichoi** [comment]
Fixed in the latest version (version 2.1.5)
