### ISSUE TITLE
Invalid SBML is loaded into roadrunner

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#434]
The attached model is loaded into roadrunner without issue but actually it is an invalid SBML model. Try loading in to COPASI or antimony and it will fail to load.  The online validator also claims it is invalid. roadrunner should not be loading this model. 

Note I had to rename to the file to a log file for github to attach it.

[Glycolysis.log](https://github.com/sys-bio/tellurium/files/3019322/Glycolysis.log)

**Comment by fbergmann** [comment]
I don't think that is much of an issue. In fact newer versions of COPASI (like the 4.25 current one), will state that it is an error not to list all species used in a kinetic law, but we will still load it as modifier. I think it is fine to load models like that.

**Comment by fbergmann** [comment]
actually the model as is has no steady state as pyruvate is building up in both compartments. One would have to add some degradation reactions for the two to solve the issue (or modify their kinetics).

**Comment by fbergmann** [comment]
looking over the model again, it seems like libsbml is actually mistakenly flagging that reaction as invalid. There is a local parameter with the same name as the species. So that would be valid ... which means that there is nothing to do for roadrunner here :)

**Comment by luciansmith** [comment]
No, that is indeed invalid in L3v2.  The scope of a local parameter changed
to be the whole reaction object, not just the kinetic law.

**Comment by fbergmann** [comment]
is it? with species 'a', 'b' and 'h' ... and reaction a -> b, and local parameter h, with kl:  a + h. LibSBML should not complain about a missing modifier reference for 'h', since there is a local parameter 'h'.

**Comment by luciansmith** [comment]
In L3v2, you can't have a speciesReference to 'h' and a local parameter 'h'.  (Rule 21173: The id of a LocalParameter object must not be the same as the species attribute of any SpeciesReference in the same Reaction.)"  I don't know if it should also complain about the missing modifier reference, as it's already ambiguous.

In L3v1, it shouldn't complain about anything.

**Comment by fbergmann** [comment]
well .. this is a level 2 model :) ... and the point still holds that if anything is changed then it will not have to be in roadRunner, but rather in libSBML :) so yeah .. lets close this
