### ISSUE TITLE
Incorrectly identifies model as requiring MCA

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#440]
For a model with rate laws but not MCA calculations, roadrunner issues the incorrect error message when trying to compute the steady state:

RuntimeError: Metabolic control analysis only valid for primitive reaction kinetics models. This model has rate rules

It should complain in this case. The model was:

r = te.loada('''
    x' = k1/(1+y^n1) - k2*x;
    y' = k3/(1+x^n2) - k4*y;
    
    x = 4; y = -4;
    k1 = 12; k3 = 12; k2 = 2; k4 = 2
    n1 = 4; n2 = 4
''')
r.,steadyState()

**Comment by kirichoi** [comment]
Hmm, I am not getting any errors. Which version of libroadrunner are you using?

**Comment by hsauro** [comment]
Appear to happen with version:

te.getVersionInfo()
Out[574]: 
[('tellurium', '2.1.5'),
 ('roadrunner', '1.5.3'),
 ('antimony', '2.9.4'),
 ('libsbml', '5.15.0'),
 ('libsedml', '0.4.3'),
 ('phrasedml', '1.0.9'),
 ('pySBOL', '2.3.0')]

but is ok with the more recent version that has the newer libsbml

[('tellurium', '2.1.5'),
 ('roadrunner', '1.5.4'),
 ('antimony', '2.11.0'),
 ('libsbml', '5.18.1'),
 ('libsedml', '0.4.3'),
 ('phrasedml', '1.0.9'),
 ('pySBOL', '2.3.2')]

Once you've read we can close it, not an issues in the current version.
