### ISSUE TITLE
How does one clear the network viewer image?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#45]
After loading an sbml file to view using the viewer, how does one then clear the image?

**Comment by 0u812** [comment]
You mean clearing the model? I don't think I have a button for that yet. I can add it if you like.

**Comment by hsauro** [comment]
Yes that's right. The reason to suggest this (something I noticed today) is
that a visible network is distracting if someone starts working on a
different model and would just like to clear the screen. It is true that
they could just select another tab to hide the network but better if there
was a clear button.

H
