### ISSUE TITLE
Allow more flexibility with version of NumPy

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/tellurium#519]
tellurium requires a specific version of NumPy. If this isn't strictly necessary, it would be helpful to make this more flexible (e.g, `numpy>=1.19.3` so tellurium can be composed with a wider range of packages.

**Comment by luciansmith** [comment]
Yup--I had to fix the numpy version for a while because of a bug in Windows that wasn't fixed for several months, but those months have now passed, and we can relax the version of numpy again.  I actually thought this was already committed, but perhaps it got into a different branch.

**Comment by luciansmith** [comment]
Fixed!
