### ISSUE TITLE
getAntimony() call breaks on Notebook interface but not Spyder

### ISSUE THREAD

**Issue by chaytanc** [sys-bio/tellurium#525]
Using a model loaded from an xml file, all normal calls like .plot() work on the loaded model from SBML. However, the call r.getAntimony() fails with the exception 
"Antimony: Unable to read SBML string due to errors encountered when parsing the file.  Error(s) from libSBML: ..."
(the full exception is quite the stack dump but I can provide the whole thing if you want)
The exception ends with " listOfGlobalRenderInformation cannot be empty."
The same model loaded with Spyder and the same python-libsbml version loads the model and can perform the getAntimony call without errors.

**Comment by luciansmith** [comment]
Thank you for the report!  Can you provide a model that you're using that demonstrates this problem?

**Comment by luciansmith** [comment]
Looks like we lost @chaytanc , so I'm closing this for now.  If you find the model in question, I'm more than happy to re-open.
