### ISSUE TITLE
Cannot import tesbml

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#532]
This looks like an easy fix, some code in tellurium is still relying on tesbml, eg

te.getODEsFromModel(r)
Traceback (most recent call last):

  File "C:\Tellurium-Winpython-3.8\python-3.8.6.amd64\lib\site-packages\tellurium\utils\misc.py", line 175, in __init__
    import tesbml

ModuleNotFoundError: No module named 'tesbml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-440-4f84343b1321>", line 1, in <module>
    te.getODEsFromModel(r)

  File "C:\Tellurium-Winpython-3.8\python-3.8.6.amd64\lib\site-packages\tellurium\utils\misc.py", line 114, in getODEsFromModel
    extractor = ODEExtractor (roadrunnerModel.getSBML())

  File "C:\Tellurium-Winpython-3.8\python-3.8.6.amd64\lib\site-packages\tellurium\utils\misc.py", line 177, in __init__
    raise Exception("Cannot import tesbml. Try tellurium.installPackage('tesbml')")

Exception: Cannot import tesbml. Try tellurium.installPackage('tesbml')

**Comment by hsauro** [comment]
The fix is easy, change line 175 of misc.py to

 import libsbml

and line 179 to

self.doc = libsbml.readSBMLFromString (sbmlStr)

**Comment by luciansmith** [comment]
It seems like your tellurium isn't up to date--if you look at

https://github.com/sys-bio/tellurium/blob/develop/tellurium/utils/misc.py

the only place it mentions tesbml is:

            try:
                import libsbml
            except ImportError:
                import tesbml as libsbml

which is there just in case libsbml is not.

Which version of tellurium are you using?  It looks like I made that change
seven months ago, so I would have hoped it would make it into the latest...

**Comment by hsauro** [comment]
I'm running:

[('tellurium', '2.1.6'),
 ('roadrunner', '2.0.8'),
 ('antimony', '2.12.0.3'),
 ('libsbml', '5.19.0'),
 ('libsedml', '0.4.52'),
 ('phrasedml', '1.1.0')]

**Comment by luciansmith** [comment]
Yup--tellurium 2.2.0 should have this fix.

**Comment by hsauro** [comment]
Ok I see I’ve an old tellurium. Without a windows installer do I just do

pip install tellurium —upgrade

**Comment by luciansmith** [comment]
I seem to be unable to test this myself right now, but I believe you are correct.
