### ISSUE TITLE
Possible bug in reading COMBINE archive

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#54]
There might be a small bug in loading combine archives. Load the boris2 archive, save the two files, then run each of them, sometimes (I think there is a pattern) it plots the wrong graph. Works itself out the second time you run the models.

**Comment by kirichoi** [comment]
Could you post the plot? Does it seem to be from some other models?

**Comment by kirichoi** [comment]
Cannot reproduce. Close for now.
