### ISSUE TITLE
Is the documentation on the Gillepsie method correct?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#541]
The documentation on the Gillespie method seems to suggest that it can take as an argument the seed for the rnd. But trying to provide one generates an error.

m = r.gillespie (0, 50, seed=1234)

simulate() got an unexpected keyword argument 'seed'

https://tellurium.readthedocs.io/en/latest/tellurium_methods.html?highlight=gillespie#tellurium.tellurium.ExtendedRoadRunner.gillespie

![image](https://user-images.githubusercontent.com/1054990/131052167-4607330f-e87c-41cc-b610-895519c306f6.png)

**Comment by luciansmith** [comment]
It is correct now!  I'm not sure why the documentation said it before, but it was a good idea, so it's now implemented.
