### ISSUE TITLE
cannot install Tellurium on Mac (OS 10.12)

### ISSUE THREAD

**Issue by htahir2** [sys-bio/tellurium#547]
I am trying to install Tellurium on Mac (10.12). I have python 3.8.12 installed in a conda environment. 

I first activate the conda environment and then I use the following commands to install Tellurium:
conda install msgpack-python
pip install tellurium

Installation goes quite slow and then raises an error at the end. The following error appear while installing debugpy:
  Downloading debugpy-1.4.3-py2.py3-none-any.whl (4.1 MB)
     |████████████████████████████████| 4.1 MB 1.7 MB/s 
  Downloading debugpy-1.4.1-py2.py3-none-any.whl (4.2 MB)
     |████████████████████████████████| 4.2 MB 1.7 MB/s 
  Downloading debugpy-1.4.0-py2.py3-none-any.whl (4.2 MB)
     |████████████████████████████████| 4.2 MB 3.4 MB/s 
  Downloading debugpy-1.3.0-py2.py3-none-any.whl (4.2 MB)
     |████████████████████████████████| 4.2 MB 281 kB/s 
  Downloading debugpy-1.2.1-py2.py3-none-any.whl (4.1 MB)
     |████████████████████████████████| 4.1 MB 1.2 MB/s 
  Downloading debugpy-1.2.0-py2.py3-none-any.whl (4.1 MB)
     |████████████████████████████████| 4.1 MB 3.6 MB/s 
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/ht/miniconda3/envs/py38/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/Users/ht/miniconda3/envs/py38/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/Users/ht/miniconda3/envs/py38/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "/Users/ht/miniconda3/envs/py38/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/Users/ht/miniconda3/envs/py38/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/ht/miniconda3/envs/py38/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 383, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000

I have no clue what is happening. I even tried to use python version 3.9 but the same issue.

**Comment by luciansmith** [comment]
I agree that those are not very helpful error messages!  Sorry for the extra work it's causing you.

There are a couple issues--the first is that we have moved to using pip installs and not conda, and the second is that the most recent version of libroadrunner will only work with MacOS 10.15 or later.  (We might be able to extend this to 10.14, but not as early as 10.12).

However, you should still be able to install older versions of tellurium and everything should still work there.  I *believe* that tellurium 2.1.5 should still work on MacOS 10.12, and I think it might also have had a conda release.

There may be issues with the dependencies--when things get too out of date, that's when I've seen error messages like the ones you report.  Basically, it's trying to figure out which older versions of everything it can give you, but the interdependencies are too complicated, and it finally gives up.  If you figure out which specific versions of things to ask for, sometimes that can help it work out the rest.

**Comment by htahir2** [comment]
OK Thank you. I will try to install it on Windows machine or otherwise update Mac to 10.15.
