### ISSUE TITLE
Possible bug with r.removeSpecies ('Sx') were Sx is part of an assignment

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#549]
Possible bug with r.removeSpecies ('Sx') were Sx is part of an assignment

Calling this completely crashes roadrunner,

**Comment by luciansmith** [comment]
Despite being the one to create this problem originally, I cannot reproduce it.  Looking at the code, it looks like everything should work fine, and all my tests work fine.  I even went back to the colab notebook and everything worked fine there, too.  Was worth investigating, but whatever problem we ran into, 'removeSpecies' wasn't at the root of it.
