### ISSUE TITLE
Bug in latest tellurium install

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#550]
I installed the latest tellurium using pip and when I try to run a model (previously ok with an older tellurium)

# Traceback (most recent call last):
#  File "C:\Users\Herbert Sauro\Documents\Tellurium\liliOsc.py", line 41, in <module>
#    r.plot()
#RuntimeError: Object of type <class 'NamedArray'> appears to 
#be C subclassed NumPy array, void scalar, or allocated in a 
#non-standard way.NumPy reserves the right to change the size 
#of these structures. Projects are required to take this into 
#account by either recompiling against a specific NumPy version 
#or padding the struct and enforcing a maximum NumPy version.

**Comment by luciansmith** [comment]
Any time I get a subclass error like this, it's almost always due to having upgraded something but not restarted the kernel.  I assume this is what's going on here.  I know you had other issues trying to upgrade; if we can track them down we might be able to get that working more cleanly, too.
