### ISSUE TITLE
Support SBML Level 3 Version 2

### ISSUE THREAD

**Issue by UnkindPartition** [sys-bio/tellurium#553]
When trying to convert an SBML model to Antimony with tellurium 2.2.2.1, I get errors that indicate that tellurium is limited to SBML L3V1, e.g.:

```
<max> is not valid in SBML Level 3 Version 1.

The only permitted MathML 2.0 elements in SBML Level 2 are the following: <cn>, <ci>, <csymbol>, <sep>, <apply>, <piecewise>, <piece>, <otherwise>, <eq>, <neq>, <gt>, <lt>, <geq>, <leq>, <plus>, <minus>, <times>, <divide>, <power>, <root>, <abs>, <exp>, <ln>, <log>, <floor>, <ceiling>, <factorial>, <and>, <or>, <xor>, <not>, <degree>, <bvar>, <logbase>, <sin>, <cos>, <tan>, <sec>, <csc>, <cot>, <sinh>, <cosh>, <tanh>, <sech>, <csch>, <coth>, <arcsin>, <arccos>, <arctan>, <arcsec>, <arccsc>, <arccot>, <arcsinh>, <arccosh>, <arctanh>, <arcsech>, <arccsch>, <arccoth>, <true>, <false>, <notanumber>, <pi>, <infinity>, <exponentiale>, <semantics>, <annotation>, and <annotation-xml>. SBML L3V2 added <implies>, <max>, <min>, <rem> and <quotient>.
Reference: L3V1 Section 3.4.1

<rem> is not valid in SBML Level 3 Version 1.

The only permitted MathML 2.0 elements in SBML Level 2 are the following: <cn>, <ci>, <csymbol>, <sep>, <apply>, <piecewise>, <piece>, <otherwise>, <eq>, <neq>, <gt>, <lt>, <geq>, <leq>, <plus>, <minus>, <times>, <divide>, <power>, <root>, <abs>, <exp>, <ln>, <log>, <floor>, <ceiling>, <factorial>, <and>, <or>, <xor>, <not>, <degree>, <bvar>, <logbase>, <sin>, <cos>, <tan>, <sec>, <csc>, <cot>, <sinh>, <cosh>, <tanh>, <sech>, <csch>, <coth>, <arcsin>, <arccos>, <arctan>, <arcsec>, <arccsc>, <arccot>, <arcsinh>, <arccosh>, <arctanh>, <arcsech>, <arccsch>, <arccoth>, <true>, <false>, <notanumber>, <pi>, <infinity>, <exponentiale>, <semantics>, <annotation>, and <annotation-xml>. SBML L3V2 added <implies>, <max>, <min>, <rem> and <quotient>.
Reference: L3V1 Section 3.4.1
```

It would be nice if tellurium supported SBML L3V2, which adds these operators.

**Comment by matthiaskoenig** [comment]
You can load the SBML L3V2 model directly with 

```
r = RoadRunner(model.sbml)
```
without using antimony. `max` and `min` should work. I don't know about `rem`.

**Comment by UnkindPartition** [comment]
Thanks, but I was hoping to use the Antimony export to make sure the SBML model is read/interpreted correctly. Is there a way to "view" the model representation in some form when using RoadRunner?

**Comment by matthiaskoenig** [comment]
You could have a look at https://sbml4humans.de . Perhaps the model report
is what you are looking for. Also roadrunner/tellurium can show the ode
system as far as I remember. This could be what you want.

**Comment by luciansmith** [comment]
If you only want Antimony to check things, you could load your model using SBML, and export to Antimony:

```
r = RoadRunner(model.sbml)
print(r.getCurrentAntimony())
```

But while that should solve your immediate problem, the more salient point is that Antimony should export to SBML L3v2 if it has any l3v2 features!  In fact, it should probably use l3v2 by default.  Thanks for the report; I'll file an issue on the Antimony page as well.

**Comment by luciansmith** [comment]
https://github.com/sys-bio/antimony/issues/55 filed.

**Comment by eltix** [comment]
@luciansmith @matthiaskoenig 

We've been confronted with the same problem when trying to get the Antimony representation of an SBML model with L3V2 math elements:

```python
import tellurium

model = tellurium.loadSBMLModel("L3V2.xml")
model.getAntimony()      
```
leads to:
```                                                                                                                                                                                                                                                                                   
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
[...]
Exception: Antimony: 5 SBML error(s) when creating module 'doc0'.  libAntimony tries to catch these errors before libSBML complains, but sometimes cannot.  Error message(s) from libSBML:

The only permitted MathML 2.0 elements in SBML Level 2 are the following: <cn>, <ci> ...
Reference: L3V1 Section 3.4.1
 <max> is not valid in SBML Level 3 Version 1.
```

We do not understand your workaround instructions:
```
r = RoadRunner(model.sbml)
print(r.getCurrentAntimony())
```
as `sbml` is not an attribute of `model`.

Is there any way to produce the `Antimony` representation of an SBML model that has `L3V2` math elements?

**Comment by luciansmith** [comment]
'model.sbml' was supposed to just mean 'the model in sbml form', which can be either a string or a filename.

I filed the antimony bug mentioned above to switch to l3v2 models by default a while back, but haven't actually released a new version with that yet.  There is code that's supposed to deal with max and min in Roadrunner, but it looks like Antimony still runs a validation step assuming L3v1, so you won't be able to view it until I fix that.  In the meantime, you can at least simulate models with max/min in them:

```python
r = te.loads("C:/Users/Lucian/Desktop/sbml-test-suite/cases/semantic/01275/01275-sbml-l3v2.xml")
r.simulate(0, 10, 100, ["time", "p1", "p2", "p3"])
r.plot()
```

**Comment by eltix** [comment]
Thank you @luciansmith 

> 'model.sbml' was supposed to just mean 'the model in sbml form', which can be either a string or a filename.

Then I confirm that 
```
r = RoadRunner(<path/to/model.xml>)
r.getCurrentAntimony()
```
does not work either.

> Antimony still runs a validation step assuming L3v1, so you won't be able to view it until I fix that

Ok, we will wait for the fix then :) 

> In the meantime, you can at least simulate models with max/min in them

Yes that works fine indeed.

**Comment by luciansmith** [comment]
OK, Antimony is now built (but not officially released) that defaults to l3v2.  If you want to experiment on your own, see

https://dev.azure.com/TheRoadrunnerProject/Antimony/_build/results?buildId=2105&view=artifacts&pathAsName=false&type=publishedArtifacts

or you can wait for the next Antimony release.  Thanks for the report and feedback!

**Comment by eltix** [comment]
Thank you @luciansmith for the hard work! We will wait for the next release.

**Comment by luciansmith** [comment]
Version 2.13.4 now uses SBML l3v2 by default!  Do let me know if you have any issues with it, and thanks again for your comments and reqest.

**Comment by eltix** [comment]
Thank you @luciansmith
