### ISSUE TITLE
libncurses5 no longer available on Ubuntu23.10

### ISSUE THREAD

**Issue by cfblaeb** [sys-bio/tellurium#574]
Hi,

libncurses5 has been removed from ubuntu (and I believe debian).
Any chance you can make it work with libncurses6?

**Comment by luciansmith** [comment]
We're working on this--with any luck, we'll be able to remove the ncurses dependency entirely.

**Comment by luciansmith** [comment]
libroadrunner 2.5.0 now doesn't require libncurses at all!  If you update, you should get the latest from pypi.
