### ISSUE TITLE
Output selection on model with compartment volume set causes scaling of initial species concentrations.

### ISSUE THREAD

**Issue by SchwarzMarek** [sys-bio/tellurium#581]
Hello,
I'm currently confused by following behavior.

Consider following code:
```
#import tellurium as te

mt = '''
    S1 + S2 -> P1;  k1*S1*S2 - k_1*P1
    P1 -> P2;       k2*P1    - k_2*P2
    k1 = 0.1; k_1 = 0.01; k2 = 0.1; k_2 = 0.01
    S1 = 10
    S2 = 10
    default_compartment = 10
'''

rr = te.loada(mt)
res1 = rr.simulate()
rr.plot(res1)

rr.reset()
rr.selections = ['time'] + rr.getFloatingSpeciesIds()
res2 = rr.simulate()
rr.plot(res2)
```

![tellurium_question](https://github.com/sys-bio/tellurium/assets/25510773/6fb9252e-8916-4d8c-b128-bd02558cbc70)

I don't understand, why selecting which variables will go into the output array, should cause the simulator to scale the initial species concentrations by the value of default_compartment volume?

My `tellurium` version is `2.2.8`, on python `3.11`.

Best
Marek

**Comment by hsauro** [comment]
I haven’t tried the code yet but I wonder if it’s because it’s interpreting
for example the Id ‘S1’ in the selection list as an amount?

I’m not sure if there is a method that returns the list of concentrations
ids, eg ‘[S1]’

**Comment by luciansmith** [comment]
As Herbert said, '[S1]' is the concentration of S1, which you set to be 10.  (Species levels are set to be concentrations by default in Antimony.)  'S1' is the amount of S1, which is 100.  

There is indeed a method that returns a list of concentrations:

rr.getFloatingSpeciesConcentrationIds()

If you use that instead of your current 'getFloatingSpeciesIds', you'll get the same result both times.

**Comment by SchwarzMarek** [comment]
Thank you both for the quick response. I've totally missed the `getFloatingSpeciesConcentrationIds()` function.
From my reading of the documentation I've thought, that everything is in concentrations, until otherwise specified and it didn't occur to me, that it is possible to obtain species amounts just by different format of requested IDs.

I also suggest, that the example https://tellurium.readthedocs.io/en/latest/notebooks.html#bistable-system
would be altered, as the selections include "S1" as the species amount but the description on the picture then lists "[S1]" as concentration. I understand that in this case (compartment volume = 1) these are the same numbers, but I think it could clarify potential confusion for others.
Best
Marek

**Comment by hsauro** [comment]
Agreed, Lucian or Adel, can you update the docs as suggested by Marek.

**Comment by luciansmith** [comment]
Done!  @SchwarzMarek , let me know if you find other bits of the documentation confusing, and I'll keep an eye out for this issue moving forward as well.
