### ISSUE TITLE
Is it possible to create a discussion tab?

### ISSUE THREAD

**Issue by LifeWorks** [sys-bio/tellurium#587]
There are some questions and discussions that might not be suitable for creating issues. The discussion can be enabled in the repository setting.

**Comment by luciansmith** [comment]
https://github.com/sys-bio/tellurium/discussions works for me, though I'm an admin.  I created a new discussion; can you make a new one as well?

**Comment by LifeWorks** [comment]
Yes, I created one. It works! Thanks, Lucian!
