### ISSUE TITLE
Import SBML, add editor tab to end of tab list

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#61]
Import SBML, add editor tab to end of tab list

**Comment by kirichoi** [comment]
Upon further inspection, this seems to be the default behavior of Spyder.
The editor widget is coded in a way that sorts the windows according to the path. This can be turned off through preferences, though that will simply change the sorting to be based on the alphabetical order of the filenames (Uppercase first).
Might be able to force put editor at the end of the tabs without changing spyderlib, but I don't think that is a good idea as it breaks the consistency.
