### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#66]
Hi all, 
linux support is not really existing for tellurium. I would like better support and as far as I remember also some other guy at Harmony asked for linux support.
At a bar minimum make the python package work with linux even if there is no full support of the spyder IDE in linux with tellurium.

**installation information**
At least provide some basic info on how to install tellurium library as long as the full spyder support is not available on the homepage (and no downloadable version for linux is there).
## Something in the direction of:

The tellurium python bindings can be installed from source via the `setup.py` mechanism in linux.

```
git clone https://github.com/sys-bio/tellurium.git tellurium
cd tellurium
sudo python setup.py install
```

The tellurium package can be used via

```
import tellurium as te
```

---

**version info broken in linux**
The pip package should have a `__version__` variable, so one can do

```
import tellurium as te
print(te.__version__)
```

In addition calling `te.getVersionInfo()` the following errors occur:

```
/home/mkoenig/git/tellurium/tellurium/tellurium.pyc in getVersionInfo()
     76 #\return Returns a string representing the version number
     77 def getVersionInfo():
---> 78     print "telluirum Version: ", getTelluriumVersion()
     79     print "RoadRunner version:", roadrunner.getVersionStr()
     80     print "Antimony version:", antimony.__version__

/home/mkoenig/git/tellurium/tellurium/tellurium.pyc in getTelluriumVersion()
     91 def getTelluriumVersion():
     92     import os
---> 93     f = open(os.path.dirname(tellurium.__file__) +'/VERSION.txt', 'r')
     94     ver = f.read().rstrip()
     95     f.close()

IOError: [Errno 2] No such file or directory: 'tellurium/VERSION.txt'
```

`os.path.join` should be used. Handle path operations and file locations OS independent.

**tellurium-examples**
There are some smaller issues with the tellurium-examples
You should probably already prepare for python 3 and use 
`from __future__ import print_function, division`
All your print statements won't work in the current form in python 3. 

All the figures created in the examples are unreadable due to much too large axis labels for me.

```
python diffevo.py 

/usr/local/lib/python2.7/dist-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:105: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
```

The multiply overflow seems a bit strange.

```
python monte.py 

/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
```

The best 
Matthias

**Comment by 0u812** [comment]
Hi @matthiaskoenig, I agree that Linux should be a supported platform. Herbert and I have talked about different possible approaches recently, and we are currently favoring an Anaconda-based solution (i.e. we would make conda packages for Win/Mac/Linux). This would give us fairly widespread support since we wouldn't have to target each distro's package format (.deb,.rpm,etc.).

The idea is that we would provide Anaconda packages for roadrunner, antimony, and the tellurium helper scripts in this repository. The tellurium package would have roadrunner and antimony listed as dependencies so users would only have to run `conda install tellurium` to get all three. We wouldn't be tied to the Spyder IDE with this approach - users would be free to choose their own Python development environment.

How does this solution sound to you? Are there any other packages we develop that you would need (e.g. SBOL etc.)? Our timeframe for implementing this would be some time in the next few months. Would that work for you? If you need a deployment sooner we could possibly prioritize this project. Please let me know what your thoughts are.

**Comment by 0u812** [comment]
I filed the technical problems you mentioned under respective tickets so we can keep this issue focused on Linux support in general.

**Comment by matthiaskoenig** [comment]
Hi Kyle,
I have no problem installing roadrunner, antimony and tellurium separately.
This works currently for me and could get tellurium working with
```
python setup.py install
```

About anaconda: I definitely prefer something which I can install
separatley without many dependencies, for instance to build custom
virtualenv. Than it is possible to just update some dependency when some
bug was fixed. With anaconda there is a lot which I don't want/need.

Currently, my problem with tellurium is mainly that I do not know what is
missing from the spyder IDE on linux if I do the minimal install of
antimony, roadrunner, tellurium
I think not much, but will have a look at the windows version when I find a
windows computer somewhere.

The focus on the linux support should be to make sure that all the
tellurium python code is working on linux.
The install like it is right now works for me.

For timeline considerations:
I care about roadrunner 95%, tellurium & antimony is not so essential.
Roadrunner is my workhorse, the rest is more of decoration.
As long as the integrator is fast and reliable, I can write any custom
functionality in python on my own.

SBOL is too far away from my work right now, but perhaps will be intersting
in the distant future..

Matthias


On Fri, Jan 15, 2016 at 7:24 PM, Kyle Medley <notifications@github.com>
wrote:

> I filed the technical problems you mentioned under respective tickets so
> we can keep this issue focused on Linux support in general.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sys-bio/tellurium/issues/66#issuecomment-172043024>.
>



-- 
Matthias König
Email: konigmatt@googlemail.com
Tel: + 49 30 20938450
Tel: + 49 176 81168480
  https://www.livermetabolism.com/contact.html
Humboldt-University Berlin, Institute for Theoretical Biology, Junior Group
König
Charité Berlin, Institute of Biochemistry, Computational Systems
Biochemistry <http://www.charite.de/sysbio/people/koenig/>

**Comment by matthiaskoenig** [comment]
I could test and document most of the tellurium functionality in linux. The only things I cannot get running so far are

`sbml2matlab` (see https://github.com/sys-bio/sbml2matlab/issues/1)
`telplugins` (see https://github.com/sys-bio/rrplugins/issues/28)

It would be amazing if these could be fixed, than I have the full tellurium stack running on linux and could test plugins & matlab support.

**Comment by hsauro** [comment]
We can get the sbml2matlab working, that shouldn't be difficult, the
bifurcation package might take some effort but Kyle has it working on the
Mac so maybe not.

Herbert

**Comment by burgerga** [comment]
I am trying to get it working on Linux, but it's not straightforward. The instructions should probably mention to use Anaconda2 (I was trying with 3).

With 2 it's working but I get:

```
/home/gerhard/anaconda2/lib/python2.7/site-packages/tellurium/notebooks/__init__.py:16: UserWarning: Notebook tools are not imported, due to missing dependencies.
  warnings.warn("Notebook tools are not imported, due to missing dependencies.")
```

I had to dive into the source (https://github.com/sys-bio/tellurium/blob/master/tellurium/notebooks/__init__.py) to get the reason:

```
"""
notebook imports
"""
import warnings

try:
    import ipywidgets
    import IPython

    from notebooktools import *
    from ontologysearch import OntologySearch
    from parameterslider import ParameterSlider
    from speciessearch import SearchBySpeciesForm

except ImportError:
    warnings.warn("Notebook tools are not imported, due to missing dependencies.")
```

I could install `notebooktools` with pip, but I could not find `ontologysearch` anywhere...

**Comment by hsauro** [comment]
I agree, the instructions need to be improved. For some reason there is
resistance to adding detailed instructions, I think the developers assume
users can work out the details themselves which I think is a bit
optimisitic.

I've cced this to the developer in the hope they'll improve the docs.

Herbert

**Comment by djinnome** [comment]
Hi Herbert and Gerhard,

  The reason `ontologysearch` won't import is because it depends upon bioservices, which is a separate package that needs to be installed through pip.

https://github.com/sys-bio/tellurium/blob/master/tellurium/notebooks/ontologysearch.py#L9

**Comment by matthiaskoenig** [comment]
this is solved with pip packages
