### ISSUE TITLE
Update NOTICE.txt and NEWS.txt to reflect changes

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#73]
NOTICE.txt and NEWS.txt do not reflect the status of v1.3.0.

There should be a very short document which describes the process of making a release. This should especially contain information about:
* which files have to be updated (VERSION.txt, NOTICE.txt, NEWS.txt, ...?)
* which tests have to be run successfully to accept as valid commit/release (?)
Especially the tests are unclear for me right now.
- where are the tests located? How are the tests run for tellurium?

In addition there should be a `master` and `develop` branch, with the master having the status of the latest release and the developing happening in the developing branch (develop version is in develop).

**Comment by kirichoi** [comment]
Other issues will be merged with #55 and #33

**Comment by matthiaskoenig** [comment]
I am closing this. 
Files were updated by Kiri and update is now part of the release checklist #75. So should not happen again.
