### ISSUE TITLE
Testing documentation & guidlines

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#77]
Which tests have to be run to make sure a tellurium commit is valid?
I could not find anything about testing in the repository.

This should be documented, i.e.
- how to run tests
- how to write tests

**Comment by matthiaskoenig** [comment]
see also #33

**Comment by matthiaskoenig** [comment]
unittests are implemented for core functionality
Testing documentation and guidelines are available in
https://github.com/sys-bio/tellurium/blob/master/tellurium/tests/README.md

unittests have to be run successfully before commiting !

**Comment by hsauro** [comment]
This was supposed to be documented a long time ago!

Herbert

**Comment by 0u812** [comment]
Running this from within Spyder on the Mac results in the following error message:
```
>>> import tellurium.tests.test_runner as tetest
>>> runner = tetest.TestRunner()
>>> runner.te_passes_tests()
...
(output of roadrunner tests)
...
<unittest.runner.TextTestResult run=135 errors=13 failures=0>
/Volumes/Tellurium-1.3.2-Spyder-2.3.8-OSX/Spyder-Py2.app/Contents/Resources/lib/python2.7/matplotlib/figure.py:397: UserWarning: matplotlib is currently using a non-GUI backend, so cannot show the figure
  "matplotlib is currently using a non-GUI backend, "
```

**Comment by 0u812** [comment]
Also, running the tests seem to prevent matplotlib from working at all. I don't get any output from the `RoadRunner.plot()` function after running the tests.

**Comment by matthiaskoenig** [comment]
Sorry. Redirecting the gui interface while running the test. So one can
plot in the tests without creating the images. Have to restore at end of
test runner. Will fix this.

**Comment by 0u812** [comment]
Great, thanks so much for your help!

On February 27, 2016 3:49:41 AM PST, "Matthias König" <notifications@github.com> wrote:
>Sorry. Redirecting the gui interface while running the test. So one can
>plot in the tests without creating the images. Have to restore at end
>of
>test runner. Will fix this.
>On Feb 27, 2016 12:13 AM, "Kyle Medley" <notifications@github.com>
>wrote:
>
>> Also, running the tests seem to prevent matplotlib from working at
>all. I
>> don't get any output from the RoadRunner.plot() function after
>running
>> the tests.
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/sys-bio/tellurium/issues/77#issuecomment-189521602>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/tellurium/issues/77#issuecomment-189621698

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.
