### ISSUE TITLE
unzipy used in SedmlToRr but not defined

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#80]
unzipy is used in SedmlToRr but not defined anywhere. 
This worked due to the very bad practise of defining imports within functions (as long as there is no test for the function, the code can be imported even if the import is not full-filled). Writing all import at the header of files will make sure the imports work.

I could find unzipy it in the the package:
https://github.com/sys-bio/sedml2py
which also contains a SedmlToRr ?!. This is very bad pratise. The code should only be in one place not in 2 different repositories. This has to be resolved.

Solution:
 remove `SedmlToRr.py` from tellurium, merge the changes of the file in `sedml2py` and than import sedml2py in tellurium.

**Comment by kirichoi** [comment]
Changes in SedmlToRr script will be directly pushed to Tellurium. The repo is deprecated at this point.
