### ISSUE TITLE
Make sedml2py accept string

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/tellurium#83]
Make sedml2py accept raw SED-ML string

**Comment by matthiaskoenig** [comment]
Hi Kiri,
always add a test if you can after implementing things.
See `test_via_sedml_string` in `test_sedml`

I renamed the SedmlToRr -> tesedml so it conforms with the naming of the rest.
M

**Comment by kirichoi** [comment]
@matthiaskoenig: Thanks for pointing it out!
