### ISSUE TITLE
Add export to pgfplots (latex)

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#9]
Add a pgfToPlot() method.

This could be implemented via an additional plotting engine.

See
http://pgfplots.sourceforge.net/

> PGFPlots draws high--quality function plots in normal or logarithmic scaling with a user-friendly interface directly in TeX. The user supplies axis labels, legend entries and the plot coordinates for one or more plots and PGFPlots applies axis scaling, computes any logarithms and axis ticks and draws the plots. It supports line plots, scatter plots, piecewise constant plots, bar plots, area plots, mesh-- and surface plots, patch plots, contour plots, quiver plots, histogram plots, polar axes, ternary diagrams, smith charts and some more. 

edit Matthias: added clarification and link

**Comment by matthiaskoenig** [comment]
What should this method do? Not clear.

**Comment by matthiaskoenig** [comment]
Can this be closed? 
Not clear what it means and seems outdated. Please close or update.

**Comment by hsauro** [comment]
I'd like. Amthod thst outomarically create pfgplot code for direct pasting
into latex documents. Pgfolot is a great plotting package for latex. Keep
open for now if possible, it's a long term project.

Herbert

**Comment by matthiaskoenig** [comment]
I have added some clarification to the issue.

**Comment by hsauro** [comment]
This might be a project I can do as I am familiar with pgfplots.

Herbert

**Comment by luciansmith** [comment]
Do we still want pgfplot export from tellurium?

**Comment by hsauro** [comment]
Let's close this for now.

**Comment by luciansmith** [comment]
Done!
