### ISSUE TITLE
What are the "Total unknown tests: 6" in the runTester() routine?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#90]
I ran the runTester() routine and it gave this summary output:

Total failed tests:      0 
Total unknown tests:     6 
Total passed tests:      385

what are the 6 unknown tests?

**Comment by 0u812** [comment]
This is actually a roadrunner issue. The unknown tests come from things like "Get Reaction Rates Ex", which tests the C API method getReactionRatesEx, which isn't exposed to Python hence there is no test for it. I should just add Python stubs for each of the "Ex" tests that automatically pass, there's no reason to make it look like they represent gaps in the coverage.

**Comment by 0u812** [comment]
See https://github.com/sys-bio/roadrunner/issues/299
