### ISSUE TITLE
Update setSeed / getSeed to use roadrunner integrator api

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#93]
Please use the following syntax for getting and setting the seed:
```
r.getIntegrator().getValue('seed')
r.getIntegrator().setValue('seed')
```

**Comment by hsauro** [comment]
I'd like two helper methods to shorten these to

r.setSeed and r.getSeed.

given how often they might be used. We've had the short versions since the
beginning, I'd like to keep them.

H

**Comment by kirichoi** [comment]
Just checked with the most recent release of roadrunner and tellurium. Everything seems to work well. The next release of tellurium will flawlessly execute Matthias' examples.
