### ISSUE TITLE
Improved SED-ML support

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#95]
Hi all,
I would like to implement in the next few weeks a better SED-ML support in Tellurium. 
Currently the `tesedml.py` is a complete mess and in my opinion beyond repair. It will be much more work to refactor this than to rewrite it from scratch (I just tried and gave up after 30 min).

The main feature of tesedml is to provide a python code factory which generates executable tellurium python code from given SED-ML files. The new implementation would have the following features
- python code generation based on template language (jinja2 http://jinja.pocoo.org/docs/dev/), i.e. there is a python code template which is only filled with the values from models, simulations, tasks, ...
- clear representation and separation of models, simulation, tasks, datagenerators and output
- increased coverage of SED-ML, i.e. to represent as much as possible of the current specification and having a clear list/overview which parts of SED-ML are supported.
- support of model changes (modfying the SBML tree with the changes and using the changed models for loading)
- full support of all phrasedml constructs

Tellurium would have `jinja2` as additional dependency.
Let me know what you think and if this fits in the future plans of tellurium.

Matthias

**Comment by hsauro** [comment]
I think this is worth pursuing. The key for me is the ability to convert a
combine archive either in to editable and understandable Python (has to be
understandable by ordinary Python users!) and the antimony/phrased
conversion, this is allow users to update the combine archive with minimal
effort. I'm giving a demo of reproducibility in tellurium today but a more
extensive talk later in the year at EMBS. I.e. We need to retain the above
functionality.

Herbert

**Comment by kirichoi** [comment]
I support this. I have been working on tesedml trying to improve it from its original state but it is very difficult to expand due to the way it is initially implemented.

**Comment by matthiaskoenig** [comment]
Yes, the python code will be readable (almost the same like now).
It will generate the 'best practise code', i.e. the code humans would write
to do the same thing in an optimal way in tellurium.
Only the python code generator will be changed.

The nice thing with a template language is that multiple templates can be
implemented. I.e. with the same code base (but different template) python
code & executable notebooks can be generated. I.e. one does not only get
executable python code but jupyter nootebooks which are on the fly
executed, perform all tasks/simulations, generate all images, and write it
to an HTML report with all results.
One gets:
combine_archive (model/antimony + sedml/phrasedml) -> python code + jupyter
notebook (executed) -> to HTML report (all figures)



On Mon, Feb 22, 2016 at 6:36 PM, Kiri Choi <notifications@github.com> wrote:

> I support this. I have been working on tesedml trying to improve it from
> its original state but it is very difficult to expand due to the way it is
> initially implemented.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sys-bio/tellurium/issues/95#issuecomment-187282943>.
>



-- 
Matthias König
Junior Group Leader LiSym - Systems Medicine of the Liver
Humboldt-University Berlin, Institute for Theoretical Biology
  https://www.livermetabolism.com
konigmatt@googlemail.com
Tel: +49 30 20938450
Tel: +49 176 81168480

**Comment by hsauro** [comment]
Ok, this sounds good. I like the HTML option.

Out of curiosity can the templates be used to target other languages?

Herbert

**Comment by matthiaskoenig** [comment]
Yes other languages are possible. Is mainly filling in data pieces into
predefined templates. Of course one needs at least roadrunner language
bindings for the execution (and other helper functions) to create the
outputs and plots. One would than not import matplotlib but a corresponding
library in the template for the target language.

**Comment by matthiaskoenig** [comment]
Tellurium has now full SED-ML support with the exception of the XMLChanges on models.
I.e. whatever Combine Archive with SEDML files and SBML files should be executable in tellurium

@kirichoi @0u812 Could you test this on Windows/Mac respectively and try to create a build. The additional python dependencies are 
- jinja2
- pandas
(listed in requirements.txt)

A list of examples is given in the docs (attached, click on index.html -> Examples -> SED-ML), 
[tellurium-doc.zip](https://github.com/sys-bio/tellurium/files/161533/tellurium-doc.zip)
in the notebooks (`examples/notebooks/core/phrasedml.inpy`) or in the tellurium examples
```
examples/tellurium-files/phrasedml
```
subfolder.

Here for instance how to reproduce the L1V2 SEDML specification example:
```
from __future__ import print_function
import tellurium as te
from tellurium.sedml import tesedml
import phrasedml

# Get SBML from URN and set for phrasedml
urn = "urn:miriam:biomodels.db:BIOMD0000000012"
sbmlStr = te.temiriam.getSBMLFromBiomodelsURN(urn=urn)
phrasedml.setReferencedSBML(urn, sbmlStr)

# <SBML species>
#   PX - LacI protein
#   PY - TetR protein
#   PZ - cI protein
#   X - LacI mRNA
#   Y - TetR mRNA
#   Z - cI mRNA

# <SBML parameters>
#   ps_a - tps_active: Transcrition from free promotor in transcripts per second and promotor
#   ps_0 - tps_repr: Transcrition from fully repressed promotor in transcripts per second and promotor

phrasedmlStr = """
    model1 = model "{}"
    model2 = model model1 with ps_0=1.3E-5, ps_a=0.013
    sim1 = simulate uniform(0, 1000, 1000)
    task1 = run sim1 on model1
    task2 = run sim1 on model2

    # A simple timecourse simulation
    plot "Figure 1.1 Timecourse of repressilator" task1.time vs task1.PX, task1.PZ, task1.PY

    # Applying preprocessing
    plot "Figure 1.2 Timecourse after pre-processing" task2.time vs task2.PX, task2.PZ, task2.PY

    # Applying postprocessing
    plot "Figure 1.3 Timecourse after post-processing" task1.PX/max(task1.PX) vs task1.PZ/max(task1.PZ), \
                                                       task1.PY/max(task1.PY) vs task1.PX/max(task1.PX), \
                                                       task1.PZ/max(task1.PZ) vs task1.PY/max(task1.PY)
""".format(urn)

# [1] convert to SED-ML & run
# convert to SED-ML
sedmlStr = phrasedml.convertString(phrasedmlStr)
if sedmlStr == None:
    print(phrasedml.getLastError())

# Run the SED-ML file
te.executeSEDML(sedmlStr)
```

![plot_0](https://cloud.githubusercontent.com/assets/900538/13573308/6e9e6790-e47f-11e5-8dc2-0187cbd55e9e.png)
![plot_1](https://cloud.githubusercontent.com/assets/900538/13573309/6e9e96ca-e47f-11e5-9114-c6e40f51d9fb.png)
![plot_2](https://cloud.githubusercontent.com/assets/900538/13573311/6ea0e1be-e47f-11e5-81ce-5311bc55565b.png)

Here for instance the parameterScan2D
```
import tellurium as te

antimonyStr = '''
// Created by libAntimony v2.9
model *parameterScan2D()

  // Compartments and Species:
  compartment compartment_;
  species MKKK in compartment_, MKKK_P in compartment_, MKK in compartment_;
  species MKK_P in compartment_, MKK_PP in compartment_, MAPK in compartment_;
  species MAPK_P in compartment_, MAPK_PP in compartment_;

  // Reactions:
  J0: MKKK => MKKK_P; (J0_V1*MKKK)/((1 + (MAPK_PP/J0_Ki)^J0_n)*(J0_K1 + MKKK));
  J1: MKKK_P => MKKK; (J1_V2*MKKK_P)/(J1_KK2 + MKKK_P);
  J2: MKK => MKK_P; (J2_k3*MKKK_P*MKK)/(J2_KK3 + MKK);
  J3: MKK_P => MKK_PP; (J3_k4*MKKK_P*MKK_P)/(J3_KK4 + MKK_P);
  J4: MKK_PP => MKK_P; (J4_V5*MKK_PP)/(J4_KK5 + MKK_PP);
  J5: MKK_P => MKK; (J5_V6*MKK_P)/(J5_KK6 + MKK_P);
  J6: MAPK => MAPK_P; (J6_k7*MKK_PP*MAPK)/(J6_KK7 + MAPK);
  J7: MAPK_P => MAPK_PP; (J7_k8*MKK_PP*MAPK_P)/(J7_KK8 + MAPK_P);
  J8: MAPK_PP => MAPK_P; (J8_V9*MAPK_PP)/(J8_KK9 + MAPK_PP);
  J9: MAPK_P => MAPK; (J9_V10*MAPK_P)/(J9_KK10 + MAPK_P);

  // Species initializations:
  MKKK = 90;
  MKKK_P = 10;
  MKK = 280;
  MKK_P = 10;
  MKK_PP = 10;
  MAPK = 280;
  MAPK_P = 10;
  MAPK_PP = 10;

  // Compartment initializations:
  compartment_ = 1;

  // Variable initializations:
  J0_V1 = 2.5;
  J0_Ki = 9;
  J0_n = 1;
  J0_K1 = 10;
  J1_V2 = 0.25;
  J1_KK2 = 8;
  J2_k3 = 0.025;
  J2_KK3 = 15;
  J3_k4 = 0.025;
  J3_KK4 = 15;
  J4_V5 = 0.75;
  J4_KK5 = 15;
  J5_V6 = 0.75;
  J5_KK6 = 15;
  J6_k7 = 0.025;
  J6_KK7 = 15;
  J7_k8 = 0.025;
  J7_KK8 = 15;
  J8_V9 = 0.5;
  J8_KK9 = 15;
  J9_V10 = 0.5;
  J9_KK10 = 15;

  // Other declarations:
  const compartment_, J0_V1, J0_Ki, J0_n, J0_K1, J1_V2, J1_KK2, J2_k3, J2_KK3;
  const J3_k4, J3_KK4, J4_V5, J4_KK5, J5_V6, J5_KK6, J6_k7, J6_KK7, J7_k8;
  const J7_KK8, J8_V9, J8_KK9, J9_V10, J9_KK10;
end
'''

phrasedmlStr = '''
  model_3 = model "parameterScan2D"
  sim_repeat = simulate uniform(0,3000,100)
  task_1 = run sim_repeat on model_3
  repeatedtask_1 = repeat task_1 for J1_KK2 in [1, 5, 10, 50, 60, 70, 80, 90, 100], reset=true
  repeatedtask_2 = repeat repeatedtask_1 for J4_KK5 in uniform(1, 40, 10), reset=true
  plot repeatedtask_2.J4_KK5 vs repeatedtask_2.J1_KK2
  plot repeatedtask_2.time vs repeatedtask_2.MKK, repeatedtask_2.MKK_P
'''

# phrasedml experiment
exp = te.experiment(antimonyStr, phrasedmlStr)
exp.execute(phrasedmlStr)
```
![plot_0](https://cloud.githubusercontent.com/assets/900538/13573426/fbfaf496-e47f-11e5-91f3-00d759b0b127.png)
![plot_1](https://cloud.githubusercontent.com/assets/900538/13573425/fbfb1264-e47f-11e5-8b2e-804351fda587.png)

This supports much more than COPASI, SED-ML Webtools or JWS online ;)

**Comment by matthiaskoenig** [comment]
I leave this open until a mac & win build exists.

**Comment by kirichoi** [comment]
A quick check on Windows raises some problems related to jinja2 that leads to the kernel dying.
The problems seems to be coming from translating sedml to python through toPython() function, especially on pysedml = template.render(c).
I will see what can be done about it.

**Comment by matthiaskoenig** [comment]
@kirichoi You made the release, I assume you got things working with jinja2. 
If the new sedml implementation is workin in win/mac you can close this issue.

**Comment by kirichoi** [comment]
The issue is not resolved, and this change is not included in version 1.3.2

**Comment by kirichoi** [comment]
Pinpointed the source of error. It seems to be due to libsbml.
@matthiaskoenig : could you let me know which version of libsbml you are using?

**Comment by kirichoi** [comment]
Temporally solved the issue by reverting back to libSBML 5.11.4. Probably some issue with the building process. However, the second script raises:
`AttributeError: 'module' object has no attribute 'addDotXMLToModelSources'`
Current stable libphrasedml does not seem to have any function named `addDotXMLToModelSources`

@luciansmith : I see the function defined in the source. Any plan to release a new version of phrasedml?

**Comment by matthiaskoenig** [comment]
Hi Kiri,

this is the latest phrasedml develop (Lucian fixed some issues needed for
the sedml support).
The addDotXMLModelSources was one of them. It handles mainly the issue that
the antimony models do not have xml in their names, but the respective SBML
files in the COMBINE have. So the model references have to be updated in a
clean way in the SEDML.
Also using latest antimony develop.
phrasedml and antimony should be no problem, Lucian can create new releases
(there should be a fast release cycle, so the changes of antimony and
phrasedml get asap into tellurium).

Using also latest libsbml develop (so here at least the latest stable
version should always be packed with tellurium & will put try/catch things
around everything which is in develop but not latest release).
Matthias





On Thu, Mar 24, 2016 at 8:39 AM, Kiri Choi <notifications@github.com> wrote:

> Temporally solved the issue by reverting back to libSBML 5.11.4. Probably
> some issue with the building process. However, the second script raises:
> AttributeError: 'module' object has no attribute 'addDotXMLToModelSources'
> Current stable libphrasedml does not seem to have any function named
> addDotXMLToModelSources
>
> @luciansmith <https://github.com/luciansmith> : I see the function
> defined in the source. Any plan to release a new version of phrasedml?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sys-bio/tellurium/issues/95#issuecomment-200705462>
>



-- 
Matthias König
Junior Group Leader LiSym - Systems Medicine of the Liver
Humboldt-University Berlin, Institute for Theoretical Biology
  https://www.livermetabolism.com
konigmatt@googlemail.com
Tel: +49 30 20938450
Tel: +49 176 81168480

**Comment by kirichoi** [comment]
Rebuilt libSBML, everything works fine. As soon as new stable version of phrasedml is released, I think updated SEDML scripts will be fully supported.
For both libSBML and libSEDML, I will be using the latest stable version. I'm not so keen on putting develop version into the release.

**Comment by matthiaskoenig** [comment]
Perfect.
I agree.
libSBML & libSEDML latests stable versions (and we have to handle develop
features via try/catch or similar constructs to make sure it always works
with latest stable).
phrasedml & antimony latest stable, but having fast release cycles (just
count up 1.0.4, 1.0.5, ...), so that if issues are fixed they are fast in
the tellurium version.
M

On Thu, Mar 24, 2016 at 9:51 AM, Kiri Choi <notifications@github.com> wrote:

> Rebuilt libSBML, everything works fine. As soon as new stable version of
> phrasedml is released, I think updated SEDML scripts will be fully
> supported.
> For both libSBML and libSEDML, I will be using the latest stable version.
> I'm not so keen on putting develop version into the release.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sys-bio/tellurium/issues/95#issuecomment-200739257>
>



-- 
Matthias König
Junior Group Leader LiSym - Systems Medicine of the Liver
Humboldt-University Berlin, Institute for Theoretical Biology
  https://www.livermetabolism.com
konigmatt@googlemail.com
Tel: +49 30 20938450
Tel: +49 176 81168480

**Comment by 0u812** [comment]
While I generally agree with using the stable version of a given software package, I have been forced to use the trunk for both Antimony and phraSED-ML whenever I deploy them because the stable version usually does not build on Linux or Mac. Furthermore, since they are versioned using SVN, the "stable" release is just an archive, so you can't patch it in a version-controlled way. Hence, any changes need to be made to the trunk. Just something to be aware of.

**Comment by luciansmith** [comment]
Yeah, for Antimony and phrasedml, the trunk *is* the stable version, basically.  If the trunk isn't stable, that's a bug.

For both, by the way, if you want the new 'don't write a timestamp to the files' options to work, you'll need the SVN version of libsbml.  If you don't care about timestamps, you should be able to use the latest stable release; I've wrapped the new commands in #ifdef's that test the libsbml version number.

**Comment by 0u812** [comment]
I think we need to have a better solution than assuming the trunk is stable because that's not a good approach to reproducibility and reliability. We need to have release versions of our software that are consistent across platforms. Moreover, we need to be able to say "this figure was made with Antimony/phraSED-ML x.y" in papers, and people ought to be able to install it via conda and it should have identical behavior to the one used to make the figure. In git, I would use branches and tags for this. I'm not familiar with how to address this in svn repositories. Whatever the case, I think we need to move toward a better way of handling releases across our software projects.

**Comment by luciansmith** [comment]
SVN also has branches and tags.  If you think it's worth the effort, go for it.  Tags are almost certainly your best bet--tag it; pull it into tellurium; update CMake (and the API .h file) with a new version number.

**Comment by 0u812** [comment]
I can't take on maintenance of additional projects, but if you create a release in the future please do tag it 1.0.4-rc1, 1.0.4-rc2 and so on until we have a final release that works on all platforms.

**Comment by luciansmith** [comment]
Yeah, and I'm strictly volunteer at this point, too.

**Comment by matthiaskoenig** [comment]
Yes, I share Kyles view here completely.
We have to get to a point were things are reproducible from the software
side. This will take some time and effort, but should be the ultimate goal.
And due to the packing via conda we could get there I quit fast.

For instance every COMBINE archive we write (especially if in it a the
outputs like plots and reports, i.e. an executed COMBINE archive with
tellurium) it has to be completely clear with which release/combination of
libraries this was created. And it should be straight forward for someone
to exactly get this combination of libraries (release of tellurium) for
their respective platform (mac, win, linux).
It should be as easy as:
- this is the hash/code/version of the release, for instance 5.6.7, so I
have to install http://something/5.6.7/mac to reproduce the result

M



On Thu, Mar 24, 2016 at 8:17 PM, Lucian Smith <notifications@github.com>
wrote:

> Yeah, and I'm strictly volunteer at this point, too.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sys-bio/tellurium/issues/95#issuecomment-200980964>
>



-- 
Matthias König
Junior Group Leader LiSym - Systems Medicine of the Liver
Humboldt-University Berlin, Institute for Theoretical Biology
  https://www.livermetabolism.com
konigmatt@googlemail.com
Tel: +49 30 20938450
Tel: +49 176 81168480

**Comment by hsauro** [comment]
Note however if a computational experiment can only be repeated using
exactly the same code then it is not reproducible according to the
definition of reproducibility it is instead repeatable. Information on what
version of the software was used is required for repeatability.

There is a general distinction in the literature and standards bodies
between repeability (also called replicatability) and reprodicibility.
Repeatability is where the same experiment is carried out using the same
material, software, equipment etc and the same result is obtained. An
experiment is reproducible if the same results are obtained using different
equipment, software, materials, etc. What's nice about using something like
SBML and SEDML is that the software that represents the model has to be
recreated each time the SBML/SEDML is loaded. One could argue that running
SBML/SEDML on different platforms automatically tests reproducibility.  I
see that the wikipedia page for reproducibility has this wrong and this has
been noted in some comments in the talk page. The wikipedia repeatability
page is better.

See http://www.nist.gov/pml/pubs/tn1297/upload/tn1297s.pdf page 14, section
D112 and D113

for definition from a standards body.

Herbert

**Comment by matthiaskoenig** [comment]
Yes. Everything should be reproducible from the sedml and sbml. But we will
(like everybody else) have bugs in the simulator & sedml code in every
version. We have to be able to repeat our errors to get the same results.
Reproducible are the parts which we can show to be identical with other
tools.

**Comment by 0u812** [comment]
I tried this example on the Mac with Spyder. It crashes the IPython kernel. I installed bioservices from bioconda, which is pretty much the only option for installing bioservices on the Mac. @matthiaskoenig?

**Comment by 0u812** [comment]
Btw I get one line of `INFO:root:Initialising BioModels service (WSDL)` and then it dies.

**Comment by kirichoi** [comment]
How about the second example? That does not use bioservices package

**Comment by 0u812** [comment]
It's crashing in libsedml's statically linked copy of libsbml. I will update the libsbml version. @matthiaskoenig, can you tell us exactly what version of libsbml you used?

**Comment by 0u812** [comment]
I think I discovered why it crashes. In `tellurium/sedml/mathml.py`, there is a call to libsbml.formulaToL3String. It's passing in an ASTNode from libsedml.

In general, passing a pointer from one library to another via python will not work. I was able to get it to work in this case by using the exact same version of libsbml with the exact same compiler flags in both cases, but we definitely need to fix this. Libsedml links to its own copy of libsbml, which may be different than the one you can import in tellurium. A tiny change in compiler flags can completely break everything. Even the libsbml-experimental 5.13.0 package from conda is different enough that you can't use it.

@matthiaskoenig, can you fix this (we don't need the fix for this release)? The call that causes it to crash is `formula = libsbml.formulaToL3String(astnode)` on [line 107 of mathml.py](https://github.com/sys-bio/tellurium/blob/master/tellurium/sedml/mathml.py#L107). It's passing a libsedml object into libsbml.

**Comment by 0u812** [comment]
Both of these examples work on the Mac build now.

**Comment by matthiaskoenig** [comment]
I am always linking sedml against the libsbml version I am using, i.e. I
only have one libsbml version within Tellurium. When packing Tellurium the
same thing should be done, i.e. only one version of libsbml be packed.
@kyle Is this still an issue?

Just for information: It is important in which order to import libsbml and
libsedml in python
see https://github.com/fbergmann/libSEDML/issues/21
So always do a

import libsedml
reload(libsbml)

when using libsedml in python to avoid problems.



On Mon, May 16, 2016 at 3:45 AM, Kyle Medley <notifications@github.com>
wrote:

> Both of these examples work on the Mac build now.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sys-bio/tellurium/issues/95#issuecomment-219332548>
>



-- 
Matthias König
Junior Group Leader LiSym - Systems Medicine of the Liver
Humboldt-University Berlin, Institute for Theoretical Biology
  https://www.livermetabolism.com
konigmatt@googlemail.com
Tel: +49 30 20938450
Tel: +49 176 81168480

**Comment by 0u812** [comment]
I can foresee this causing problems when we switch to conda because the conda packages for libsbml and libsedml will not necessarily include the same libsbml version with the same compiler flags. I noticed that libsedml has a `formulaToString` method - are you familiar with it and do you know if it does the same thing as `libsbml.formulaToL3String`?

If we can't find a method in libsedml that does the same thing as  `libsbml.formulaToL3String`, we could ask Frank to add one. It would be fairly trivial since it just amounts to exposing that method of libsbml.

**Comment by luciansmith** [comment]
The main difference between libsbml's 'formulaToString' method and its 'formulaToL3String' method is that the second one will use 'x && y' vs 'and(x,y)', and make other, similar changes.  I don't know what 'formulaToString' does in libsedml, but I would guess it does the same thing as libsbml.

**Comment by matthiaskoenig** [comment]
I already implemented the new support, but never closed this issue.
All remaining SED-ML issues are in separate issues with the tag SEDML.
