### ISSUE TITLE
Tellurium diffevolution optimization

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#96]
In the `tellurium.optimization.diffevolution.py` is an implementation of the diffevolution algorithm. I could not find any usage or example which uses the code.
On the other hand In the paper tellurium-examples there is an example for diffevolution optimization, but this is based on the `scipy.optimize.differential_evolution` and does not use any of the tellurium code. 

The tellurium code should be updated to use the scipy.optimize function and some example should be added.

**Comment by hsauro** [comment]
The tellurium code should probably be removed.

H

**Comment by matthiaskoenig** [comment]
removed the obsolete diffevolution code.
